### ISSUE TITLE
Use the Github release system

### ISSUE THREAD

**Issue by KawaiiPotato** [ArcadeRenegade/SidebarDiagnostics#1]
https://help.github.com/articles/creating-releases/

As you can guess, you compile the binary and upload it to the release (Not the branch, mind you) then send it out.

**Comment by ArcadeRenegade** [comment]
Interesting. Can unauthencated users download the release?

**Comment by KawaiiPotato** [comment]
Yes, anyone, regardless of if they have an account or not, can download.

**Comment by ArcadeRenegade** [comment]
Perfect. Thanks.

**Comment by KawaiiPotato** [comment]
Please implement it ASAP... I actually haven't had the chance to download the program yet because of the flurry of new users :grinning:

**Comment by ArcadeRenegade** [comment]
Oh crap the download links aren't working huh? OK I'll try to do a github release now.

**Comment by ArcadeRenegade** [comment]
That worked great. Didn't know about that feature. Big thanks!
