### ISSUE TITLE
Hide To Show

### ISSUE THREAD

**Issue by TheDuck1234** [ArcadeRenegade/SidebarDiagnostics#10]
When it set to hide and set back to show it flicker out of control (like hide/show), when setting is saved it reset back to normal again, but crash sometime with this error:

![bug](https://cloud.githubusercontent.com/assets/4168154/12644874/475fa8b0-c5c6-11e5-89ef-38a041ac1586.jpg)

**Comment by ArcadeRenegade** [comment]
The settings crash is anytime you try to save the settings?

**Comment by ArcadeRenegade** [comment]
Should be fixed now.
