### ISSUE TITLE
missing dependency

### ISSUE THREAD

**Issue by MaliusArth** [ArcadeRenegade/SidebarDiagnostics#101]
OpenHardwareMonitorLib nuget dependency is missing

**Comment by ArcadeRenegade** [comment]
It is not on Nuget but you can find it on GitHub and their website.

https://github.com/openhardwaremonitor/openhardwaremonitor
http://openhardwaremonitor.org/

**Comment by MaliusArth** [comment]
It is on nuget and works for me after referencing the nuget package. I would recommend adding that to the repo so it builds right away after cloning (with all other deps updated too).
Also, as for open source deps the use of eg. Git-submodules can be used to automatically clone dependant repos.

**Comment by ArcadeRenegade** [comment]
Oh I see. The repo is a very old build though and doesn't have skylake
support. Could you explain the git submodules thing? I'm not sure how to do
that.

**Comment by ArcadeRenegade** [comment]
the nuget package is an old build, i mean.

**Comment by MaliusArth** [comment]
It's very easy. 
Take a look at this guide, it explains it quite nicely
https://chrisjean.com/git-submodules-adding-using-removing-and-updating/

**Comment by ArcadeRenegade** [comment]
Thanks! Submodules are very cool. I added Open Hardware Monitor as one.
