### ISSUE TITLE
Sidebar doesn't respect monitor numbering

### ISSUE THREAD

**Issue by j-rodshub** [ArcadeRenegade/SidebarDiagnostics#102]
**1. Your Operating System**
Windows 10

**2. App Version**
3.3.8

**3. Any Relevant Settings**
3 Screens - numbered 1,2,3 (left to right)
2x nVidia SLI - GTX980

**4. Steps to Reproduce**
I have the sidebar docked to the left side of Screen 2
Sometimes after Startup the Sidebar loads on Screen 3 instead of Screen 2, even though the setting hasn't changed

I notice that the Sidebar is loading sooner than almost every other app, and may be choosing a screen before my nVidia settings are applied, therefore it chooses the wrong monitor.

The Issue here is that once the nVidia settings are applied, it doesn't respect the updated screen numbering, so when I tell it to display on Monitor 2, it goes to 3 anyway. 

This isn't the only app that uses Screen numbers to keep things on the right display.  Fences does the same, and you can see it updating to the right screen after it loads.

In this image you can see that the Sidebar is clearly on Screen 3, even though the setting is set to Screen 2
![sidebar](https://cloud.githubusercontent.com/assets/19356109/15787025/a5b62a76-2974-11e6-985f-86164554f922.jpg)

**Comment by Simber1** [comment]
I have the same thing, seems the sidebar uses different numbers to windows/Nvidia control panel for each display.  

http://i.imgur.com/3dCvlNx.png
