### ISSUE TITLE
When you try to open volume control window by clicking the volume icon, half of it is hidden.

### ISSUE THREAD

**Issue by nicolashedger** [ArcadeRenegade/SidebarDiagnostics#104]
When you try to open volume control window by clicking the volume icon, half of it is hidden. It is properly displayed after 1-2 seconds.

![bug](https://cloud.githubusercontent.com/assets/649677/15988265/b989b230-3049-11e6-80cd-48d0d9fbe0fa.png)

**1. Your Operating System**
Microsoft Windows 10 Professional 1511

**2. App Version**
3.3.8

**3. Any Relevant Settings**
![settings](https://cloud.githubusercontent.com/assets/649677/15988213/ce7ee206-3048-11e6-9312-dc0857e7683f.png)

**4. Steps to Reproduce**
Left click on either volume control or network icon in the taskbar.

**Comment by ArcadeRenegade** [comment]
Unfortunately, this is a bug with Windows itself. I have been able to reproduce it but I cannot fix.
