### ISSUE TITLE
Error after each boot

### ISSUE THREAD

**Issue by AlexandreBT** [ArcadeRenegade/SidebarDiagnostics#106]
**1. Your Operating System**
W10 x64

I've uninstalled SD, but after each boot I've this error, do you know why ? 
Thanks :+1: 
![explorer_2016-06-30_11-14-59](https://cloud.githubusercontent.com/assets/206181/16484059/90c8f14a-3eb7-11e6-897a-c0c8df745b97.png)

**Comment by ArcadeRenegade** [comment]
Since you want it gone try deleting the install directory.

%localappdata%\SidebarDiagnostics
