### ISSUE TITLE
Error when activating click through setting

### ISSUE THREAD

**Issue by anandisrocking007** [ArcadeRenegade/SidebarDiagnostics#107]
**1.I use windows 10 32bit**

**2. My App Version is 3.8.8**

**3. Whenever i activate the click through option it shows an error message and this remains also after reboot the only way to remove this is either to uninstall it or to remove the setting.json file**

**4. If it is possible i would like if you would prevent the sidebar from disappearing when when i use aeropeek (The same function is also present in windows gadgets in windows 7) if would would really be handy. **

**Comment by ArcadeRenegade** [comment]
Could you provide a screenshot of the error message next time it pops up please?

**Comment by anandisrocking007** [comment]
Hi Thanks for replying here is the screenshot of the error any idea what is the problem......

[https://s31.postimg.org/nms20wtaj/Screenshot_2016_07_18_12_12_27.jpg](url)

**Comment by ArcadeRenegade** [comment]
Thanks for the report and screenshot. It is fixed in v3.4.0.
