### ISSUE TITLE
Video card doesn't update

### ISSUE THREAD

**Issue by Token81** [ArcadeRenegade/SidebarDiagnostics#108]
I replaced my video card - GTX 970 to GTX 980ti 
the sidebar polls the card OK, but still names it a 970

**1. Your Operating System**
W10
**2. App Version**
3.4.0
**3. Any Relevant Settings**
changed video card
**4. Steps to Reproduce**

**Comment by ArcadeRenegade** [comment]
Open Hardware Monitor hasn't been updated to fully support the new Nvidia
GPUs yet.

For the time being, you can manually rename your GPU in the settings. In
the settings, go to the monitors tab, click on GPU, click on your video
card's name, and enter the correct name.

**Comment by Token81** [comment]
both cards are from the same family - its a 980, not a 1080

**Comment by ArcadeRenegade** [comment]
Oh right. That is a bug with my app then. I'll look into it. 

For the time being, you can still manually rename it.

**Comment by ArcadeRenegade** [comment]
Thank you for the report. I applied a fix to prevent this from happening in the future.

You will still however have to manually rename the affected hardware to fix your current issue.
