### ISSUE TITLE
The Collapse Menu Bar setting doesn't apply until the sidebar is hovered over or reloaded

### ISSUE THREAD

**Issue by Simber1** [ArcadeRenegade/SidebarDiagnostics#109]
**1. Your Operating System**
Windows 10
**2. App Version**
Latest (?) 
**3. Any Relevant Settings**

**4. Steps to Reproduce**
1. Have "Collapse Menu Bar" turned off
2. Turn it on
3. Observe the fact it didn't do anything
4. Hover over the sidebar or reload the sidebar
5. Observe the fact that it now applied

same goes for On to off

Edit: Thought I had auto-update on, Didn't. Updated to v3.4.0 now and issue still happens

**Comment by ArcadeRenegade** [comment]
Fixed. thanks for the report.
