### ISSUE TITLE
Persistent across virtual desktops

### ISSUE THREAD

**Issue by addrum** [ArcadeRenegade/SidebarDiagnostics#11]
More of a feature than an issue. In Windows 10 it would be nice to have the option for it to be sticky across virtual desktops (i.e. I move to another virtual desktop and it moves too, staying in the same place).

**Comment by ArcadeRenegade** [comment]
Could you clarify what you mean by virtual desktop?

**Comment by MEGAtheguy** [comment]
Windows 10 has a feature where if you hit the keyboard shortcut Ctrl + Win + D, (navigation between desktops is Ctrl + Win + Right/Left Arrow, or by clicking the task view button next to the search bar) it creates virtual desktops.
http://i.imgur.com/knRePXC.png
http://i.imgur.com/Ytfrfgl.png

**Comment by ArcadeRenegade** [comment]
Interesting. I'll try to implement it. Not sure if it's possible though. Thanks.

**Comment by ArcadeRenegade** [comment]
Looks like someone already made a wrapper library for win10 virtual desktop so we are in luck. 

https://github.com/Grabacr07/VirtualDesktop

The question is, do you want this to be an innate feature or something that can be toggled in a setting?

**Comment by addrum** [comment]
Probably toggled in a setting although in the current state you end up with
a blank space where the sidebar would sit that is unusable so a feature may
be better.

On Fri, 29 Jan 2016 at 00:00 Ryan <notifications@github.com> wrote:

> Looks like someone already made a wrapper library for win10 virtual
> desktop so we are in luck.
>
> https://github.com/Grabacr07/VirtualDesktop
>
> The question is, do you want this to be an innate feature or something
> that can be toggled in a setting?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ArcadeRenegade/SidebarDiagnostics/issues/11#issuecomment-176488062>
> .
>
-- 
Adam

**Comment by ArcadeRenegade** [comment]
I implemented this but it doesn't seem like it's working correctly.

**Comment by ArcadeRenegade** [comment]
It was a bug with getting the correct OS version. This is implemented and working in version 2.2.1

**Comment by addrum** [comment]
Cheers, nice work.

**Comment by addrum** [comment]
FYI getting an error when it first trying to switch VM's but it only happens once. Once the program has been launched it works as works even after restarts.

![image](https://cloud.githubusercontent.com/assets/2855069/12716357/c4432014-c8d7-11e5-9197-2660a4c1459a.png)

**Comment by ArcadeRenegade** [comment]
Thanks. Weird behavior. I'm going to be lazy and throw it into a throw catch InvalidOperationException.

**Comment by ArcadeRenegade** [comment]
I put in an issue with the repo I use to handle virtual desktops. Hopefully they have some insight.
