### ISSUE TITLE
The same date format is listed twice

### ISSUE THREAD

**Issue by Simber1** [ArcadeRenegade/SidebarDiagnostics#110]
**1. Your Operating System**
Windows 10 (UK if this makes any diff)
**2. App Version**
Latest (?) 
**3. Any Relevant Settings**

**4. Steps to Reproduce**
Look at the [Date format](http://i.imgur.com/Y73HXDu.png) drop down?

Edit: Thought I had auto-update on, Didn't. Updated to v3.4.0 now and issue still happens

**Comment by ArcadeRenegade** [comment]
I think this issue is unique to the UK culture. I think it is OK for now.
