### ISSUE TITLE
[Feature Request] Aero Peek Disable And A Few More

### ISSUE THREAD

**Issue by anandisrocking007** [ArcadeRenegade/SidebarDiagnostics#111]
Sir this is one awesome app add and to be honest i have been looking for it for years ever since microsoft left support for the gadget feature. It has feature which to be honest would have made me use two or three software and even then it would not look so good.

I have some ideas of features which could further improve it they are -

1) Option to disable Aero Peek in this App. In Windows Gadgets when we move the mouse to the aero peek bar in the bottom right side everything becomes transparent except for the Sidebar in this way we don't have to minimize the windows when we want to see the PC resource.

2) If it is possible can you add the weather monitor in the sidebar preferably at the top and separated from the time. I have posted some template as example below-

https://s31.postimg.org/6r9ae05uj/simple_flat_weather_widget.png

https://s31.postimg.org/5ptdqux3v/c_Lock_weather_widget.jpg

https://s32.postimg.org/97ub8sxd1/Bright_Weather_Widgets.jpg

https://s31.postimg.org/igv71xjsr/weather_widget_psd_image_2271weather_widget_full.jpg

I have also posted an site where you can get the weather icon below-

http://freedesignfile.com/tag/weather/

You could add the Temperature,Wind Speed And Humidity in it.
If possible you could also make give an option to open the windows default weather app on a click.

3) Ability to scroll or add a button on the sidebar to open to another page. When i first started to use this app the information was so much that it went below the screen and i had no way to view it thus i had to add a minimum of each resource monitoring. ( https://s31.postimg.org/wzwrza2vv/Capture.jpg ) Windows vista had a page changing button like-

https://s32.postimg.org/su44cbcd1/Vista_Sidebar.jpg

4) The Option To remove Space Between The different categories like RAM and CPU.

5)Last of all if possible add an mp3 player which would be able to play playlist from Media Player or VLC.

https://s31.postimg.org/dafioxjwb/t_media_player.jpg

Hope you could implement some of these request especially No 1 and 2 and once again thanks for creating such an AWESOME APP.

**Comment by ArcadeRenegade** [comment]
no. 1 is implemented.

The rest are all out of the scope of the project, at least for now.
I will implement a plugins feature in the future.

**Comment by anandisrocking007** [comment]
Excuse me how to activate the no 1 disable aero peek feature ??????

**Comment by ArcadeRenegade** [comment]
It's enabled by default. What operating system are you using?

**Comment by anandisrocking007** [comment]
Hi i am using windows 10x86
Yes it works if you click on the bar at the right bottom hand side thus everything minimizes except for the sidebar but i am talking about the part in which the mouse hovers over the sidebar andevrything becomes transparent-

http://winsupersite.com/site-files/winsupersite.com/files/archive/winsupersite.com/content/content/128523/win7/aero_peek_01.jpg

**Comment by ArcadeRenegade** [comment]
Yes, that is aero peek. Did you update to 3.4.1?

**Comment by anandisrocking007** [comment]
Sorry did not know it was updated again so fast thanks will check it as soon as I can and if possible try add the weather
