### ISSUE TITLE
Crash when switching workspaces on latest Win10 update

### ISSUE THREAD

**Issue by MichaelGatesDev** [ArcadeRenegade/SidebarDiagnostics#116]
**1. Your Operating System**
Windows 10 Home - LATEST BUILD

**2. App Version**

v3.4.1

**3. Any Relevant Settings**

Nope

**4. Steps to Reproduce**

Step 1: Open program
Step 2: Create 'virtual desktop' (aka workspace)
Step 3: Click to the virtual desktop you just created
Step 4: Crash.

**Comment by ArcadeRenegade** [comment]
Is this an insider build? As a workaround you can go to advanced and
disabled virtual desktop support and disable show in alt tab. It will do
the same thing.

**Comment by MichaelGatesDev** [comment]
Nope it's not an insider build, it was released today.

Thanks, i'll use that for now.

**Comment by rszemplinski** [comment]
+1

**Comment by SubElement** [comment]
+1

**Comment by ArcadeRenegade** [comment]
In the new version, 3.4.2, I removed the virtual desktop library completely.

To allow the Sidebar to persist between different desktops, you can disable "Show in Alt + Tab" instead.
