### ISSUE TITLE
Add in brackets that it can be used in multiple desktop if alt+tab is disabled 

### ISSUE THREAD

**Issue by anandisrocking007** [ArcadeRenegade/SidebarDiagnostics#117]
Hi just to say that since you can only use in multiple virtual desktop in the alt+tab is disable i guess you should write this somewhere in brackets in advance settings preferebally in the bottom or near the option (It might be obvious for people like me who are following your software and its changelog but for new people especially those who download the next version which might come up the changelog would be at the bottom of the page and they would think that it does not support multiwindows)

Secondly i was hoping that you can disable the alt+tab by default as i believe most of the users would like to have it in all the virtual desktop and obviousy the aero peek function is already there.

Obviousy it depends from people to people but i think these small tweaks would make it better......

**Comment by ArcadeRenegade** [comment]
You're right. I should put it in the tooltip or somewhere, for clarity.

I didn't include it in the change log but "Show in Alt + Tab" is disabled by default with the latest release.
