### ISSUE TITLE
WIN+D shortcut makes sidebar useless

### ISSUE THREAD

**Issue by MaxKade** [ArcadeRenegade/SidebarDiagnostics#118]
**1. Your Operating System**
Windows 10 x64 Enterprise
**2. App Version**
Latest
**3. Any Relevant Settings**
General > Reserve Space - OFF
General > Always On Top - OFF
**4. Steps to Reproduce**
1. Start app.
2. Open any app and maximize it.
3. Press WIN+D.
4. Open another app or restore minimized app.
5. Sidebar will be on top of every app.
6. Click on it (sidebar will disappear).
7. Press WIN+D again.
8. You won't see sidebar on desktop.

It's an impressive app, I have discovered it today because I built a new PC and I need to monitor my system status in an easy way but I use WIN+D shortcut a lot so sidebar only disturbs me and I can't use it properly... :(

**Comment by ArcadeRenegade** [comment]
While it's not perfect, the hook is necessary to keep the sidebar visible after a "show desktop" command is issued while "always on top" is disabled. Microsoft made it intentionally nearly impossible to make a window immune to show desktop and this workaround is the only method that works so far. Lots of others users requested this feature so I do not want to remove it.

**Comment by user0706** [comment]
While I'm not familiar with .NET and Windows development, what about this? 
http://stackoverflow.com/questions/10009623/c-keeping-window-visible-through-show-desktop-wind

**Comment by ArcadeRenegade** [comment]
Unfortunately, I tried this but it does not work with WPF only Windows Forms.

**Comment by user0706** [comment]
OK, I understood :(
