### ISSUE TITLE
Drive used space bar doesn't show when drive details are shown

### ISSUE THREAD

**Issue by soapysoap** [ArcadeRenegade/SidebarDiagnostics#12]
![drive1](https://cloud.githubusercontent.com/assets/16939856/12647927/c44b7884-c5be-11e5-886d-f011932501b3.PNG)
![drive2](https://cloud.githubusercontent.com/assets/16939856/12647928/c44d023a-c5be-11e5-8716-570b27cce99f.PNG)

**Comment by ArcadeRenegade** [comment]
This was intentional

**Comment by ArcadeRenegade** [comment]
I'll add it back though. I was hiding the old ugly bars when I could but it looks better now.
