### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by btraas** [ArcadeRenegade/SidebarDiagnostics#120]
Ability to show multiple GPUs, if enabled. (eg dedicated + integrated diagnostics)

**1. Your Operating System**
Windows 10 Pro

**2. App Version**
3.4.2

**3. Any Relevant Settings**
GPU monitoring enabled

**4. Steps to Reproduce**
Settings-->Monitors-->GPU

**Comment by ArcadeRenegade** [comment]
I use Open Hardware Monitor to get GPU data. Unfortunately, they do not support integrated GPUs.
