### ISSUE TITLE
Your Performance Counter cache is corrupted.

### ISSUE THREAD

**Issue by winthropdc** [ArcadeRenegade/SidebarDiagnostics#121]
**1. Your Operating System**
Windows 10 Anniversary

**2. App Version**
v3.4.2

**3. Any Relevant Settings**
Started getting the "Your Performance Counter cache is corrupted." error a few days after the Anniversary update. May or may not be related.

**4. Steps to Reproduce**
On launch, the message appears twice (Drives and Network are not populated). Then again twice every few minutes.

![sidebar1](https://cloud.githubusercontent.com/assets/21116687/17798105/0ea3e53c-6601-11e6-8806-7d05799b70e6.png)

I have run the rebuild steps numerous times and it has no effect.

![sidebar2](https://cloud.githubusercontent.com/assets/21116687/17798109/1546a244-6601-11e6-9206-b8c5a2d00b60.png)

If this cannot be resolved, I will have to stop using the tool, which is a shame as I think it is great.

**Comment by ArcadeRenegade** [comment]
It seems there is something wrong with performance counters on your computer. If running the `lodctr /r` cmd is not working then unfortunately I do not know a solution.

**Comment by winthropdc** [comment]
I followed the steps on this KB

https://support.microsoft.com/en-us/kb/2554336

But I think the actual issue was that the Performance Counter DLL Host Service had been set to Manual start.  I tested and if the service was not running Sidebar Diagnostics gave the errors, if the service was running, the Drive and Network data was displayed.

I have changed the service to start automatically now.

Wonder if the Anniversary Update changed this setting?

**Comment by ArcadeRenegade** [comment]
Weird. Possibly, but no one else has reported this issue yet.

**Comment by ArcadeRenegade** [comment]
I'll add this to the wiki. Thanks.

**Comment by oppalla** [comment]
> I followed the steps on this KB
> 
> https://support.microsoft.com/en-us/kb/2554336
> 
> But I think the actual issue was that the Performance Counter DLL Host Service had been set to Manual start. I tested and if the service was not running Sidebar Diagnostics gave the errors, if the service was running, the Drive and Network data was displayed.
> 
> I have changed the service to start automatically now.
> 



winthropdc thankyou so much for the workaround. after a lot of wasted time it was the only effective solution for the issue.
i'll higly suggest @ArcadeRenegade to put it on the Wiki.
