### ISSUE TITLE
App will randomly not open on start

### ISSUE THREAD

**Issue by Simber1** [ArcadeRenegade/SidebarDiagnostics#122]
About every 1 in 4 times I start my PC the sidebar wont start. Today I noticed 2 in the tray when it didn't open, one responded to right clicks, the other didn't. After right clicking the one which didn't a few times [this](http://i.imgur.com/bA3NPNu.png) error came up.

Also something which is annoy but i doubt you can fix is that the error box goes above the ShareX screenshot capture thing.

**1. Your Operating System**
Windows 10 version 1607

**2. App Version**
3.4.2

**3. Any Relevant Settings**
Have Run at startup on

**4. Steps to Reproduce**
Restart PC over and over again till sidebar doesn't start the right click it when it is in the tray

**Comment by Simber1** [comment]
Still getting this with [this](http://i.imgur.com/mEIxFxx.png) error.

**Comment by campbeb** [comment]
If you open Task Scheduler and click on Task Scheduler Library, how many SidebarStartup tasks do you see?

**Comment by Simber1** [comment]
One




On Sun, Aug 6, 2017 at 3:56 PM +0100, "campbeb" <notifications@github.com> wrote:












If you open Task Scheduler and click on Task Scheduler Library, how many SidebarStartup tasks do you see?
