### ISSUE TITLE
App does not properly recognize 1080 GPU

### ISSUE THREAD

**Issue by DarthRogue** [ArcadeRenegade/SidebarDiagnostics#123]
**1. Your Operating System**
Windows 10 x64 Pro
**2. App Version**
Latest
**3. Any Relevant Settings**
GPU monitoring is active and visible
**4. Steps to Reproduce**
Using this app with a GTX1080 GPU does not properly identify the GPU.  It lists it as a 970, which is what I had when I first started using the application.  But after I upgraded my GPU the sidebar tool continues to see the GPU as a 970 and not a 1080.  I have updated video drivers, rebooted the PC multiple times and reinstalled the diagnostic sidebar app, all of which has yielded no change in application behavior.

**Comment by ArcadeRenegade** [comment]
You can rename hardware in the settings.
