### ISSUE TITLE
Doesn't reserve space on Windows 10

### ISSUE THREAD

**Issue by mightyiam** [ArcadeRenegade/SidebarDiagnostics#126]
Perhaps it has to do with the latest OS update.
v3.4.2

**Comment by ArcadeRenegade** [comment]
Is this an insider build of Win 10?

**Comment by mightyiam** [comment]
Nope. Normal public release updates. Perhaps they do gradual release of
updates...

**Comment by ArcadeRenegade** [comment]
Hmm. So it doesn't reserve space at all? Or is it just buggy.

**Comment by mightyiam** [comment]
Sitting at this computer once again now. It does reserve space. Toggling hide/show doesn't break this. I'll re-open if it happens again.
