### ISSUE TITLE
Sidebar doesn't start automatically when I log in using the laptop's battery

### ISSUE THREAD

**Issue by Entenuki** [ArcadeRenegade/SidebarDiagnostics#129]
I noticed this somewhat recently. I reinstalled Windows 10 due to some weird bug with brightness that simply just wouldn't go away. So I hoped that this bug would get fixed with a reinstall, I was wrong.

The laptop model is Dell 7559. More specifically, this is the i5 Full HD 256GB SSD non-touch version. This one has an i5-6300HQ with a GTX 960M.

**1. Your Operating System**
Windows 10 Pro 1607

**2. App Version**
3.4.2, the latest at the moment I submit this (September 1st, 2016).

**3. Any Relevant Settings**
My monitor settings are: 
- **CPU**: Clock, Temperature, Load and Core Load.  (I couldn't make Voltage and Fan Usage display information so I deactivated those options)
- **RAM**: Load
- **GPU**: Core Clock, VRAM Clock, Core Load, VRAM Load and Temperature.  (I couldn't make Voltage or Fan Usage work here either.)
- **Drives**: Load Bar, Read Rate, Write Rate.
- **Network**: IP Address, External IP Address, Bandwidth In, Bandwidth Out.

**4. Steps to Reproduce**
It happens with either a reboot or a cold boot. The sidebar opens the moment I plug in the charger cable and goes away when I unplug it. It stays with no problem if I open it afterwards either on battery or charging. Opening it manually while I started on battery makes that later when I plug in the charger a second sidebar opens.

This might be a not very important issue, but I like this software so much that I have to report it.

**Comment by ArcadeRenegade** [comment]
fixed in v3.4.5
