### ISSUE TITLE
Showing using keyboard shortcut steals focus

### ISSUE THREAD

**Issue by mightyiam** [ArcadeRenegade/SidebarDiagnostics#132]
**1. Your Operating System**
Windows 10

**2. App Version**
3.4.2

**4. Steps to Reproduce**
1. Set a keyboard shortcut for toggling hide/show
1. Hide
1. Set your focus somewhere. For example, the address bar in the browser.
1. Show: you've lost focus

**Comment by ArcadeRenegade** [comment]
this is fixed in 3.4.3

**Comment by mightyiam** [comment]
Thank you!

**Comment by mightyiam** [comment]
Thank you!
