### ISSUE TITLE
No GPU temp-

### ISSUE THREAD

**Issue by cckruse** [ArcadeRenegade/SidebarDiagnostics#133]
**1. Your Operating System**
W10
**2. App Version**
3.4.2
**3. Any Relevant Settings**
GPU temperature
**4. Steps to Reproduce**
just downloaded it today

GPU temp is coming through in hd64 but not in side bar. any help would be great. thanks

**Comment by ArcadeRenegade** [comment]
Could you try downloading Open Hardware Monitor and seeing if it works there?
If it does not then unfortunately there isn't much I can do about it.

**Comment by cckruse** [comment]
I have the open hardware monitor and it does work in there...that is why i
wasn't sure why the side bar wasn't pulling it in.

**Comment by R1fast** [comment]
Oddly, temps weren't showing for me as well but after I reinstalled the app they are.  Now I'm not seeing voltages though (didn't the first install either... submitted as a separate issue #169 )
