### ISSUE TITLE
Updated from 3.3.5 to 3.4.2, now getting application errors

### ISSUE THREAD

**Issue by eski-dev** [ArcadeRenegade/SidebarDiagnostics#135]
**1. Your Operating System**
Windows 10 Pro
**2. App Version**
3.4.2
**3. Any Relevant Settings**
N/A
**4. Steps to Reproduce**
Updated from 3.3.5 to 3.4.2, Sidebar will not load.

[sidebardiagnostics.txt](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/501946/sidebardiagnostics.txt)

This is a copy of all the event viewer errors I've received. Each error occurs when trying to load the application. I apologize if the issue is not related to the application, but I can't seem to find what the issue might be.

**Comment by Skillzore** [comment]
I havethe same issue after a recent windows 10 update. The application won't start. Uninstalled and downloaded the latest, but even the installer crashes after about 30 seconds.

**Comment by Skillzore** [comment]
![sidebar not working](https://cloud.githubusercontent.com/assets/13891190/19831540/7e44ddb8-9e0c-11e6-8a4c-458f3181e31a.png)
The windows warning says that 
"Sidebar Diagnostics has stopped working
Windows is searching for a solution to the problem..."

**Comment by ArcadeRenegade** [comment]
Could you right click the start menu and click on event viewer. In event viewer, go to Windows Logs > Application. In there, do you see any relevant entries about Sidebar Diagnostics? It would have some more info on why it is failing.

**Comment by Skillzore** [comment]
Found this:

- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" /> 
  <EventID Qualifiers="0">1000</EventID> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Keywords>0x80000000000000</Keywords> 
  <TimeCreated SystemTime="2016-10-29T17:16:34.009122800Z" /> 
  <EventRecordID>16336</EventRecordID> 
  <Channel>Application</Channel> 
  <Computer>SkillzoreTower</Computer> 
  <Security /> 
  </System>
- <EventData>
  <Data>SidebarDiagnostics.exe</Data> 
  <Data>3.4.2.0</Data> 
  <Data>57a40027</Data> 
  <Data>ntdll.dll</Data> 
  <Data>10.0.14393.351</Data> 
  <Data>5801a332</Data> 
  <Data>c0000005</Data> 
  <Data>0000000000030886</Data> 
  <Data>178</Data> 
  <Data>01d232082e847028</Data> 
  <Data>C:\Users\Skillzore\AppData\Local\SidebarDiagnostics\app-3.4.2\SidebarDiagnostics.exe</Data> 
  <Data>C:\WINDOWS\SYSTEM32\ntdll.dll</Data> 
  <Data>482d7189-e5f4-4a03-8264-371213acfe8c</Data> 
  <Data /> 
  <Data /> 
  </EventData>
  </Event>

**Comment by ArcadeRenegade** [comment]
Any detailed error messages?

**Comment by Skillzore** [comment]
All the "names" below are translated from my Swedish windows so might not be the correct names.

Well, the application error only indicates the file C:\WINDOWS\SYSTEM32\ntdll.dll being the source of the error. There is an "exception code" and some "error displacement", both these are just a string of numbers.
But, with every application error for sidebar diagnostic there is also a .NET Runtime error. This one states that there was an unhandled exception in the application that caused the error. Here there also is some "exception code" and "exception address", that are just strings of numbers and some letters. 

I would copy & paste it all but don't think the Swedish would be of much help.

**Comment by ArcadeRenegade** [comment]
Thanks. It's kind of hard to determine what is wrong from this perspective. Doesn't help that the installation and update library wasn't written by me :P

**Comment by ArcadeRenegade** [comment]
Could you try uploading this file, please? It might have more info.

%localappdata%\SidebarDiagnostics\SquirrelSetup.log

**Comment by ArcadeRenegade** [comment]
You can also try deleting the entire %localappdata%\SidebarDiagnostics directory and reinstalling like that.

**Comment by Skillzore** [comment]
Hmm, I removed the %localappdata%\SidebarDiagnostics earlier but it didn't help. Now when I looked I saw %localappdata%\SquirrelLogging or something like that. I removed it and now it installed fine and seems to be working as it should. No crash for like 15 minutes and it always happened within 60 seconds. Very weird. But thanks anyway!
