### ISSUE TITLE
After killing explorer.exe reserve space nolonger works

### ISSUE THREAD

**Issue by Simber1** [ArcadeRenegade/SidebarDiagnostics#137]
**1. Your Operating System**
Windows 10
**2. App Version**
v3.4.2
**3. Any Relevant Settings**
Reserve space has to be on
**4. Steps to Reproduce**
Go into task manager and kill explorer.exe, restart explorer.exe by going file, run new task.
full screen a window on the same monitor as the sidebar and watch it go over it.

**Comment by ArcadeRenegade** [comment]
I mean, issues are bound to happen if you are stopping explorer.exe. Users shouldn't be doing that :)
