### ISSUE TITLE
If sidebar is next to vertical taskbar when system wakes from hibernate its behind the taskbar. 

### ISSUE THREAD

**Issue by LetsOne** [ArcadeRenegade/SidebarDiagnostics#139]
Window 10 - 1607
v3.4.3
Reserve Space is on and Docked left.
Hibernate with it open. http://imgur.com/4fv7XTU

**Comment by ArcadeRenegade** [comment]
Hi, your taskbar is not set to autohide, correct?

**Comment by LetsOne** [comment]
Correct. After reload it looks like it should. http://imgur.com/sKXkwWG
