### ISSUE TITLE
Multilingual

### ISSUE THREAD

**Issue by Zazou89** [ArcadeRenegade/SidebarDiagnostics#14]
Hi,

Thanks for your amazing app ! Do you think you'll provide in the future an option te help you to translate in our language (French / Deutsh...) your app ? 

Thanks :)

**Comment by ArcadeRenegade** [comment]
Localization is planned in the future. 

When I do get to it could I send you a list of strings and could you translate them for me? 

Thanks.

**Comment by AlexandreBT** [comment]
With pleasure !

**Comment by Subnim** [comment]
I can translate it to spanish if 'ya want.

**Comment by ArcadeRenegade** [comment]
Hey guys,

I'm working on localization now. Attached is an excel file which is the text values I have so far. It's not much but it's a good place to start.

Please change the "Text" column to whatever value you think it should be for your language.
The other columns "Property" and "Note" should stay the same.

[Localization.xlsx](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/146099/Localization.xlsx)

**Comment by AlexandreBT** [comment]
Yes, it's a good start ;)

French translation: 
[Localization.xlsx](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/146111/Localization.xlsx)

**Comment by ArcadeRenegade** [comment]
@AlexandreBT Thanks!

I implemented your changes in v3.1.0
If your system locale is set to French in the Windows region settings, you should see your translations automatically.

**Comment by CodingContraption** [comment]
I've got a Dutch translation for you. :)

[Localization.xlsx](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/146315/Localization.xlsx)

**Comment by RememberMeWell** [comment]
@CodingContraption hahah je bent me net voor:) ik wou net die van mij hier gooien;)

**Comment by CodingContraption** [comment]
@RememberMeWell Haha xD. If you want, you could 2nd opinion my translations. 2 see more than 1.

**Comment by RememberMeWell** [comment]
@CodingContraption i would change Update to "Bijwerken" and Close to "Afsluiten". Everything else seems fine:)

**Comment by CodingContraption** [comment]
@RememberMeWell Bijgewerkt, thanks. :)

Updated Dutch translation:
[Localization.xlsx](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/146344/Localization.xlsx)

**Comment by Chris92de** [comment]
This one should be good for de-DE and de-AT, de-CH just needs one change for "Close", it would be "Schliessen" instead of "Schließen".

[Localization DE.xlsx](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/146433/Localization.DE.xlsx)

**Comment by thegreatlp** [comment]
Updated the French translation. For some reason, it wouldn't let me upload the .xlsx file.

[Localization FR.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/146557/Localization.FR.zip)

**Comment by AlexandreBT** [comment]
Yes, "Coeur" is better than "Noyau". Oups I forget to change "Don" by something like you wrote "Faire un don".

**Comment by victordk** [comment]
Danish translation
[Localization DK.xlsx](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/146939/Localization.DK.xlsx)

**Comment by renesdk** [comment]
Danish translation v 2
(corrected some of the translations from victordk)

da and da-DK

[Localization.xlsx](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/147156/Localization.xlsx)

**Comment by congonasty** [comment]
I don't know how many people will find it useful but here's a draft of a Japanese localization! 
[JPLocalization.xlsx](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/147183/JPLocalization.xlsx)

**Comment by ArcadeRenegade** [comment]
Wow thanks for the overwhelming support guys! The open source community is
awesome!

I'll try and upload and finished version of all text to translate as soon
as possible.

Please let me know if your translation can be used for all cultures of your
language or just a specific culture. That way we can cover as many
translations as possible.

**Comment by AlexandreBT** [comment]
You'e to see the quality of your work, it's natural to help. You've created a fantastic & minimalist program!

**Comment by renesdk** [comment]
da and da-DK is the same and can be used for all of Denmark and the Danish language.

**Comment by Bur0k** [comment]
Can't i change the Language back to English? Don't want to read PC Statistics in German

**Comment by LPMorel** [comment]
Having the option to customize the labels ourselves would be nice too, as there are disagreements on the best translation.

**Comment by BernardoRebelo** [comment]
If you need help translating it into Portuguese, lemme know. I can help with that

**Comment by renesdk** [comment]
@ArcadeRenegade I've found an "issue" with you using one string for percentage load.
In Danish the load on the CPU is "Belastning"
But usage percentage of RAM and Disks would be "I brug".

So a suggestion would be separate strings depending on the hardware :)

**Comment by ArcadeRenegade** [comment]
Unfortunately, the localized text data is compiled into a dll. So it would not be possible for the user to edit it manually.

I will add a setting option for Language though.

**Comment by ArcadeRenegade** [comment]
@renesdk thanks your change will be in the next version

**Comment by renesdk** [comment]
@ArcadeRenegade Thanks. I really like how fast you are about getting new changes and suggestions incorporated into the software.

**Comment by Subnim** [comment]
Hello! Here's the spanish translation document. Sorry for taking so long but I just saw that you published the excel file. 
[Localization ES.xlsx](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/149700/Localization.ES.xlsx)

**Comment by Girtablulu** [comment]
Is there any plan to translate the settings menu language?

**Comment by ArcadeRenegade** [comment]
Hi @Girtablulu 

I do plan on it. However I am adding a new charts feature and there will be new text to translate.
Once it is all complete I will post the full excel file of text to translate.

**Comment by ArcadeRenegade** [comment]
@LPMorel if you want to submit a localization for Canadian French I'm okay with that.

**Comment by ArcadeRenegade** [comment]
Here is the complete Excel file of text to translate. I split a lot of stuff up in order to accommodate differences between languages.

It's pretty big, 215 rows. So take your time. Or just do as much as you feel like.

[LocalizationComplete.xlsx](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/158360/LocalizationComplete.xlsx)

**Comment by ArcadeRenegade** [comment]
Remember to just edit the middle "text" column. Thanks :+1:

**Comment by AlexandreBT** [comment]
Maybe it's a better solution to create a dedicated repo for the translation or a solution like Transfiex (https://www.transifex.com) but free.

**Comment by ArcadeRenegade** [comment]
I don't think I'll be able to find free professional translation services.
And my budget for this project is pretty much nonexistent.

I'm just happy that I was able to get all the text into a resource file. I
know it's a lot of work to translate that much text and I honestly don't
think anyone will do it but that's OK as long as the option is there.

**Comment by campbeb** [comment]
It might be beneficial to add the Excel files to the repo that way translators can quickly see what strings need to be translated for a language. Additionally, if it was a text file, then they could fork the repo, edit the file in their browser and submit a PR for the changes. But, I'm guessing that maybe you are using RESX Manager and that's why it is Excel.

**Comment by ArcadeRenegade** [comment]
I see what you mean. I am using resx so I just copy pasted the table viewer
data into excel. I don't know if GitHub supports diffs for xlsx files.
Could use CSV instead.

**Comment by Vassile-D** [comment]
Hey. Here's localization for Chinese (Simplified).

I'm doing it for Chinese (Simplified, China), locale zh-CN/2052, but it also works on Chinese (Simplified, Singapore), locale zh-SG/4100, since people there speak the very same language. Some names may be different for native speakers, so if anyone want to tailor it specifically for 4100 use mine as a template.

[Sidebar Diagnostics Localization (Simplified Chinese, zh-CN).zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/159532/Sidebar.Diagnostics.Localization.Simplified.Chinese.zh-CN.zip)

I'm still working on Chinese (Traditional) and will upload that copy soon.

**Comment by AlexandreBT** [comment]
First try for the French Translation. I tried to use the most appropriate terms.
[LocalizationComplete.xlsx](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/159537/LocalizationComplete.xlsx)

**Comment by ArcadeRenegade** [comment]
Thanks guys you're awesome. I'll add your translations later tonight. 

@Subnim I'll add your Spanish translation for the sidebar text as well. 

For new languages I'm adding them for all cultures of that language. I figure that would work out OK until a new translation gets submitted for a different culture of the same language.

**Comment by ArcadeRenegade** [comment]
Also I'll create a new repository for translations tonight. I'll probably just use CSV so the git diff works.

**Comment by ArcadeRenegade** [comment]
@AlexandreBT & @Vassile-D 

I added your translations. I also added a new text align setting in this new version. I used Google Translate to figure out their text values. Hope they are ok.

SettingsTextAlign	Alignement du texte	
SettingsTextAlignLeft	Gauche
SettingsTextAlignRight	Droite
SettingsTextAlignTooltip	Alignement du texte métrique.


SettingsTextAlign	文本对齐
SettingsTextAlignLeft	左侧
SettingsTextAlignRight	右侧
SettingsTextAlignTooltip	度量标准文本的对齐。

**Comment by ArcadeRenegade** [comment]
And here is the localization repository. Feel free to submit any pull requests.

https://github.com/ArcadeRenegade/SidebarLocalization

**Comment by AlexandreBT** [comment]
All special characters have been deleted, I'll update for you the loc :)

**Comment by Girtablulu** [comment]
I added a pull request for localization for Switzerland (what I know and could) most of this can be used as well for german as well. I'm not 100% if I translated everything correct maybe another german checks it, I have probably do a re translate for labels which aren't correct translated

**Comment by Tepperotta97** [comment]
I didn't understand the Pull Request mechanic, but i translated the Danish localization into Norwegian

[Localization.NO.xlsx](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/171046/Localization.NO.xlsx)

**Comment by renesdk** [comment]
I'm working on the complete Danish translation.
Are there a separate repository for the complete translation, or is that the same as this https://github.com/ArcadeRenegade/SidebarLocalization ?

When done, I'll be adding the xlsx in this thread unless instructed otherwise.

**Comment by ArcadeRenegade** [comment]
That is the correct localization repo.

**Comment by renesdk** [comment]
I've simply not have had time, and won't have time going forward unfortunately to do the full Danish translation.

**Comment by maxleonalbrecht** [comment]
fixed things in the de.local: (0x0007)

https://www.dropbox.com/s/dz90keqz5rb3t7d/Localization.de.csv?dl=0

**Comment by Drake4478** [comment]
Voici la mise à jour Française de Sidebar Diagnostics 3.4.0.

[url=http://mangasoudivers.free.fr/D/L/Traductions/Sidebar-Diagnostics/Localization.fr.zip]Localization.fr.zip[url)

**Comment by dgpmaluco** [comment]
Hello! Thanks for the awesome program.

Here is the Portuguese translation for Portugal. It's good for Portuguese (Brasil) until someone edits it!

0x0816	pt-PT	Portuguese (Portugal)	Portuguese	português (Portugal)	1252	850	PRT	PTG


[Localization.pt.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/404786/Localization.pt.zip)

**Comment by Entenuki** [comment]
For some reason I cannot upload it here, so I give you [the Dropbox link for it](https://www.dropbox.com/s/8rfel312dc01x5o/Localization.es.csv?dl=1).

It's for **es 0x000A**. There was a previous version, but given how it's not updated for the amount of strings in the current version, I decided to do my own translation, hope it is useful for you.

**Comment by test13r** [comment]
Hello! Thanks for the awesome software.

Here is the Russian | Russia | 0x0419 | ru-RU translation.

[Localization.ru-RU.xlsx](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/1282317/Localization.ru-RU.xlsx)

**Comment by test13r** [comment]
I installed the latest version is 3.4.5 but unfortunately, I couldn't find some items in settings to translate (used this file for template: https://github.com/ArcadeRenegade/SidebarLocalization/blob/master/Localization.en.csv). 
Here they are: 

1. Toolbar Mode
2. Hide at startup
3. Colors, Standard/Advanced at colorpicker

and the items of the IP address/Ext. IP address on the Sidebar Diagnostics.
