### ISSUE TITLE
Funky Voltage with Radeon Crimson ReLive Edition

### ISSUE THREAD

**Issue by Styil** [ArcadeRenegade/SidebarDiagnostics#141]
**1. Your Operating System**
Windows 10 Education, Insider Preview 14971
**2. App Version**
3.4.3
**3. Any Relevant Settings**
N/A
**4. Steps to Reproduce**
![Picture of Issue](https://cloud.githubusercontent.com/assets/24415429/21035525/a0f2aa02-bd74-11e6-9e5a-ea7b0d72ab6a.png)

Installed AMD's new ReLive Crimson Drivers. This is what appeared when I installed and rebooted the system.

**Comment by ArcadeRenegade** [comment]
Hmm. And your PC is not on fire, correct?

**Comment by Styil** [comment]
Don't believe so. Hopefully not.

**Comment by kwilt** [comment]
[http://i.imgur.com/rkh35MT.png](url) I also have the same issue.

**Comment by ArcadeRenegade** [comment]
The Open Hardware Monitor team will have to release an update to their library to fix this. Unfortunately, they haven't been very active recently.

**Comment by wowwood** [comment]
I also have this issue.
![image](https://cloud.githubusercontent.com/assets/6392165/22404133/80a4fb16-e622-11e6-9733-bc8d0e997aa5.png)

**Comment by ArcadeRenegade** [comment]
Go to the settings under the advanced tab check the "collapse menu bar" setting.
