### ISSUE TITLE
Newest Windows Update Broke Sidebar

### ISSUE THREAD

**Issue by Styil** [ArcadeRenegade/SidebarDiagnostics#142]
**1. Your Operating System**
![image](https://cloud.githubusercontent.com/assets/24415429/21078653/2a4931dc-bf2c-11e6-8ab0-74d839b3dacb.png)

Note that this was most likely what broke it, as it occurred right after a Windows update. I am on the newest Windows 10 fast preview lane, I understand if you do not want to solve the issue due to this.

**2. App Version**
3.4.3
**3. Any Relevant Settings**
N/A
**4. Steps to Reproduce**

Error:
![image](https://cloud.githubusercontent.com/assets/24415429/21078646/f2e6ce5c-bf2b-11e6-85d0-dc5d3ccabf0e.png)

Occurs upon program startup. Sidebar does appear, but has a frozen loading symbol. Windows will call the program unresponsive once I close the error, at which point it will kill it.

Edit: This is actually very likely a Windows problem, since I got the same error from HandBrake.

**Comment by ArcadeRenegade** [comment]
Oh man this is going to be hard to troubleshoot. Looks like it has something to do with a tablet and stylus? Are you using both?

**Comment by Styil** [comment]
Yep. Tried to launch the program after disconnecting the graphics tablet and it worked. Seems like a Windows issue on my side, not your code. Gonna mark it as closed now.

Thanks mate.

**Comment by ArcadeRenegade** [comment]
Okay, thanks for the report though.
