### ISSUE TITLE
Text/Graphics Drop Shadow + Fully transparent background

### ISSUE THREAD

**Issue by Sidneys1** [ArcadeRenegade/SidebarDiagnostics#143]
I use a utility to make my Windows Taskbar fully transparent - I would love for Sidebar Diagnostics to match.

I can set the background to have a opacity of 0.01, which is close but not fully transparent. 
Additionally, the text now does not show up well on all wallpapers (see attached image). 
There should be an option to enable a drop shadow on the text and images in the sidebar, maybe with a configurable color and opacity of its own.

![2017-01-10_20-17-42](https://cloud.githubusercontent.com/assets/1771233/21831446/e4d628a4-d771-11e6-985a-4093007140bc.jpg)

**Comment by mightyiam** [comment]
I care about this, as well. I see the difference in color, but I don't use a photo in my background so I don't see a need for text shadow, but I do understand.

Let's make this two separate issues. I've opened #192 for the 0.01 minimum opacity. So this issue's name can be changed to "Drop shadow for text and other graphics", how about that?

**Comment by Sidneys1** [comment]
@mightyiam I don't believe that a second issue is necessary - The implementation in #145 allows the text shadow to be disabled, meaning you can achieve both the `0.0` opacity and no shadow.
