### ISSUE TITLE
Can't monitor 7700k Temps

### ISSUE THREAD

**Issue by floxigen** [ArcadeRenegade/SidebarDiagnostics#144]
Windows 10 64bits

version 4.3.3

Temps won't display for new 7700k cpu, only usage

http://i.imgur.com/QGyLySm.png

**Comment by ArcadeRenegade** [comment]
Open Hardware Monitor will have to be updated to support the brand new gen of Intel processors. Had the same problem when Skylake first came out.

**Comment by floxigen** [comment]
https://github.com/openhardwaremonitor/openhardwaremonitor/issues/909

They did now it's working in open hardware monitor

**Comment by ArcadeRenegade** [comment]
👍 I'll do a release tomorrow. Thanks.

**Comment by floxigen** [comment]
Tank you for that !

**Comment by ArcadeRenegade** [comment]
Okay, I did a release. Please update to version 3.4.4. Thanks.

**Comment by floxigen** [comment]
Thank you for that

**Comment by ArcadeRenegade** [comment]
No problem
