### ISSUE TITLE
UI Scaling option changes configuration window scale as well.

### ISSUE THREAD

**Issue by lailoken503** [ArcadeRenegade/SidebarDiagnostics#147]
Windows 10 64-bit Education
V3.4.4
Default setting, except moved sidebar to screen 2, which is a smaller resolution (1280x1024) compared to my main screen.  UI ended up being too big, so re-scaled side bar to something more reasonable.

Right click system tray icon, choose settings. Click on advance tab, either type in new value for UI scale, or slide slider for UI scale.  Settings screen gets it's UI scaled as well as the side bar. Screenshots attached.
![2017-01-24 3](https://cloud.githubusercontent.com/assets/10490157/22273524/1b2656f6-e256-11e6-97da-fe7ef931e887.png)
![2017-01-24](https://cloud.githubusercontent.com/assets/10490157/22273525/1b28fef6-e256-11e6-9677-c2d9fb216f41.png)
![2017-01-24 2](https://cloud.githubusercontent.com/assets/10490157/22273526/1b29a734-e256-11e6-9758-d4c13747755c.png)

**Comment by ArcadeRenegade** [comment]
That setting rescales the entire application. It was for back when I couldn't figure out how to get it working well on high DPI monitors. But since that's fixed I should probably just change it to just scale the sidebar.

**Comment by ArcadeRenegade** [comment]
fixed in v3.4.5
