### ISSUE TITLE
GPU name won't change after upgrade

### ISSUE THREAD

**Issue by Statesheriff** [ArcadeRenegade/SidebarDiagnostics#149]
I upgraded from a 980 Ti to a GTX 1080, uninstalled and installed fresh drivers, etc. But the name of the GPU in sidebar won't change, even though it still shows the diagnostics of the new GPU

**Comment by ArcadeRenegade** [comment]
You can rename it

**Comment by ArcadeRenegade** [comment]
fixed in v3.4.5
