### ISSUE TITLE
Frequency is wrong with the i7-7700K

### ISSUE THREAD

**Issue by MrE3gman** [ArcadeRenegade/SidebarDiagnostics#150]
Windows 10
3.4.4 (latest)
Processor overclocked to 4.7Ghz
The frequency seems to be staying at 1.500 Mhz, ocasionally geting a bit lower or a bit higher (I've seen as much as 2.6 Ghz), even when stresstesting the processor, and when all other tools say it has a higher frequency. The image was done while on an aida64 load.
![eaf6be0ab3b2168bbb376319b131f59e](https://cloud.githubusercontent.com/assets/25480518/22506361/4b40c4ea-e880-11e6-962b-b77e9716b204.png)

**Comment by ArcadeRenegade** [comment]
Could you please open this issue with Open Hardware Monitor? I use this
library for CPU data. Someone might be able to fix the issue there then I
can do a release for sidebar diagnostics with their latest changes.

**Comment by floxigen** [comment]
https://github.com/openhardwaremonitor/openhardwaremonitor/issues/911

They uploaded a fixed version, maybe it will help @ArcadeRenegade

**Comment by ArcadeRenegade** [comment]
okay, thanks. fixed in v3.4.5
