### ISSUE TITLE
Freezes when tethered to phone

### ISSUE THREAD

**Issue by anandisrocking007** [ArcadeRenegade/SidebarDiagnostics#151]
**1. Windows 10 64 and 32 Bit**

**2. 3.4.4**

**3. No Relevant Settings**

**4. Use Tethering**

Hellp sir i have found out that your app freezes whenever i tether from my smartphone (Redmi Note 3 with Snapdragon processor) hope you could look into it also if possible.

Also if possible can you add an option to only use selected networks only as everytime i tether my phone (I also have ethernet also) a new network is shown such as "isatap {DEDEEO-DDDE-DWKS}" or so and thus i have to tether everytime i tether or install a new virtual machine in virtualbox.

**Comment by ArcadeRenegade** [comment]
Please give this fix a try. Users have had this issue before and it seems to be a Windows issue.

https://forum.xda-developers.com/android/general/fix-usb-tethering-lags-freezes-windows-t3039183

I'll look into filtering the isatap adapters from showing up.

**Comment by anandisrocking007** [comment]
Thank you

**Comment by ArcadeRenegade** [comment]
fixed the isatap issue in v3.4.5
