### ISSUE TITLE
Excessive resource usage

### ISSUE THREAD

**Issue by BTGbullseye** [ArcadeRenegade/SidebarDiagnostics#154]
**1. Your Operating System**
Windows 7 x64 Ultimate, no Microsoft updates since April.
**2. App Version**
3.4.5
**3. Any Relevant Settings**
Settings don't appear to affect anything.
**4. Steps to Reproduce**
Run the program.

The problem is that this program is using at a minimum 94MB of RAM, and frequently going as high as 150MB. What is it doing that it requires more RAM than Steam or an open tab in Chrome, not to mention 25x the size of the program with all its assets?

**Comment by ArcadeRenegade** [comment]
It only uses 25-30 MB on my Windows 10 PC. Are you running the .NET 4.6.1 version?

**Comment by BTGbullseye** [comment]
Indeed I am. After a complete restart of my computer, it's down to around 88MB of RAM, but it comes back up to the 94MB after a couple hours and stays there.

**Comment by BTGbullseye** [comment]
Update. It now is starting off at 108MB, and escalates from there.

**Comment by ArcadeRenegade** [comment]
Unfortunately, I do not know how to optimize further for Windows 7. I consistently get 30 MB to 60 MB on Windows 10 64 bit. It may just be that .NET WPF is less optimized on Windows 7.

**Comment by BTGbullseye** [comment]
According to Microsoft, (so take it with a grain of salt) the .NET framework should work identically between versions of Windows, including resource usage.
