### ISSUE TITLE
Nvidia DSR issue

### ISSUE THREAD

**Issue by TheForsak3n0ne** [ArcadeRenegade/SidebarDiagnostics#156]
**1. Your Operating System**
Windows 10 Pro x64
**2. App Version**
3.4.5
**3. Any Relevant Settings**
No
**4. Steps to Reproduce**
When I load a game using Nvidia's DSR (Pushing 4K to 1080p). Sidebar Diag will move to the middle of the screen and cut off half of the items I am monitor. 
![img_20170210_161728](https://cloud.githubusercontent.com/assets/25696957/22846951/c87a143a-efaf-11e6-9f57-184b62a135e1.jpg)

**Comment by Limesterlambo** [comment]
Yeah I've been getting this for ages, I haven't really been bothered too much though as I don't use DSR very much and it always goes back to normal afterwards :)
