### ISSUE TITLE
Went from a great tool, to the biggest pile of shit in 1 update

### ISSUE THREAD

**Issue by MiekHawk** [ArcadeRenegade/SidebarDiagnostics#161]
**1. Your Operating System**
Win10 Pro 64 bit
**2. App Version**
newest
**3. Any Relevant Settings**
none
**4. Steps to Reproduce**
none ... never have I seen such a fucking 180 degree flip on a piece of software. It's like you went full retard after 1 update. WTF is wrong with you  shit4brains? The software now locks up my PC, for sometimes many minutes. WTF could this pile of shit be doing that's completely freezing this PC & the screens flash when it unlocks. 
I've reported your software as virus_ware sent in many complaints this morning about it & am looking to get you removed from this site & any other site you've posted this virus laden garbage on. GTFO off the internet faggot

**Comment by Limesterlambo** [comment]
You probably downloaded some other piece of dodgy software, don't just blame the guy for your isolated problem.

**Comment by campbeb** [comment]
@MiekHawk If you would like whatever your problem is to be looked at, you'll have to be more specific with the Steps to Reproduce.

**Comment by ArcadeRenegade** [comment]
👍 cool story bro
