### ISSUE TITLE
UTC clock option

### ISSUE THREAD

**Issue by matt2hews** [ArcadeRenegade/SidebarDiagnostics#163]
I added UTC to the Time panel in my personal build.  I'm going to find it very helpful for my profession.  Just a suggestion for a future official option.

![screenshot 2017-02-25 20 08 11](https://cloud.githubusercontent.com/assets/23318558/23336198/adafdb6a-fb96-11e6-8fa2-119a50172110.png)

Thanks for the hard work on the project!

**Comment by boxofdeath** [comment]
I was just about to request this exact feature. How did you add this?

**Comment by matt2hews** [comment]
I checked in the updates on my [fork](https://github.com/matt2hews/SidebarDiagnostics).  There are two files I updated: Sidebar.xaml and SidebarModel.cs.  If you take all the changes, it will add the UTC time as well as system uptime.
