### ISSUE TITLE
[Request] Docking to bottom or top

### ISSUE THREAD

**Issue by enstetter** [ArcadeRenegade/SidebarDiagnostics#164]
HI,

SidebarDiagnostics is exactly the tool I was looking for.

But since I want to use it on my secondary screen, which is setup in portrait orientation it would be excellent to dock it to the top or the bottom.

Any chance this will be implemented?

**Comment by ArcadeRenegade** [comment]
This has been requested a lot but unfortunately it is just not feasible for me to do, as getting the layout is difficult. If someone is able to pull it off and make a pull request that I am game.
