### ISSUE TITLE
Sidebar hidden problem

### ISSUE THREAD

**Issue by kuertianshi** [ArcadeRenegade/SidebarDiagnostics#165]
**1. Your Operating System**
Windows 10
**2. App Version**
master
**3. Any Relevant Settings**
SettingsAlwaysOnTop = false  and other default
**4. Steps to Reproduce**
use win log key + d  sometime will hidden sidebar

**Comment by tehflyboy** [comment]
i have the same issue.
Windows 10, App Version 3.4.5, Always On Top = Off.
Sidebar is always hidden when I click 'show desktop'.
