### ISSUE TITLE
Design Bug: Scrollbar takes separate space instead of appearing as overlay: Shrinks mainview

### ISSUE THREAD

**Issue by zekedran** [ArcadeRenegade/SidebarDiagnostics#166]
Scrollbar is set to visible on hover, and when it appears, it creates a new vertical block exclusively for the scrollbar, shrinking the existing (main) layout's width _[so as to maintain same overall width]_ which consequently increases the scroll length. Plus the scrollbar doesn't appear on the extreme right, right padding is present [image attached]

![untitled](https://cloud.githubusercontent.com/assets/8567893/24668877/ea76db36-1985-11e7-99ac-68592c98b4c7.png)

**Proposed Solution:**
Scrollbar's view should be set to what's equivalent to `position: absolute` in CSS, so as to render the scrollbar on top of the main view **in the right padded space** (which I called extreme right previously)

- Operating System: Windows 8
- App Version: 3.4.5

**Comment by ArcadeRenegade** [comment]
This is more of a design choice than a bug. If I let the scrollbar cover the text then the user would have to move their cursor away to read it.

This is also the default WPF behavior for scrollbars anyways.

**Comment by zekedran** [comment]
> If I let the scrollbar cover the text then the user would have to move their cursor away to read it.

Not really, the scrollbar will fit in the **right padding** allocated for the mainview as I mentioned in the _proposed solution_

**Comment by ArcadeRenegade** [comment]
I see what you mean. I'll give it a try.
