### ISSUE TITLE
Crashes in new Windows Creator's Update.

### ISSUE THREAD

**Issue by Bkral** [ArcadeRenegade/SidebarDiagnostics#168]
**1. WIndows 10 Pro 64-bit + Creator's Update

**2. Current Release

**3. Any Relevant Settings**

**4. Does not open at start, task bar icon shows, but when clicked, entire application crashes.

**Comment by edde275** [comment]
Almost the same Issue, the program crashes after just a second. Shows up in the taskbar until I hover over hte icon. Windows 10 Creators update and latest Sidebar verion.

**Comment by campbeb** [comment]
I am running the Creator's Update (Build 15063.13) and the program doesn't crash for me (using my own build).

@Bkral Does it give any message when it crashes?

**Comment by Bkral** [comment]
I seem to have figured it out.

The most recent Riva Statistics Tuner seems to conflict with Sidebar.

**Comment by anvil008** [comment]
Can confirm, the Riva Statistics Tuner causes the issue in Creator's Update.

**Comment by edde275** [comment]
All that needs to be done is to create a profile for the sidebar diagnostics​ exe in rivatuner and disable all functions.

**Comment by ArcadeRenegade** [comment]
I am not familiar with Riva Statistics Tuner, sorry.

**Comment by edde275** [comment]
@ArcadeRenegade you don't need to be, the issue is easily solved by filtering out SidebarDiagnostics in Rivatuner.

**Comment by Redtuzk** [comment]
Can confirm that @edde275 's solution works. Thanks!
