### ISSUE TITLE
Voltage not showing (Vcore, RAM or GPU)

### ISSUE THREAD

**Issue by R1fast** [ArcadeRenegade/SidebarDiagnostics#169]
**1. Your Operating System** Windows 10 Enterprise 64 Bit

**2. App Version** v.3.4.5

**3. Any Relevant Settings** Voltage parameter enabled in app.  Running HWINFO64 as well.

**4. Steps to Reproduce** Enable Voltage parameter in app.

With voltage selected, it does not show in the sidebar.  

![capture](https://cloud.githubusercontent.com/assets/28174023/25552312/01e98f7a-2c4b-11e7-80bb-d576a8b4b0f7.PNG)

**Comment by ArcadeRenegade** [comment]
Unfortunately, Open Hardware Monitor does not have good support for motherboards, which is required for getting voltage. I included the ability to show it just in case it works for some people.

**Comment by R1fast** [comment]
No problem, still a great little app.  Thanks for taking the time to respond!
