### ISSUE TITLE
Ram Name Issue

### ISSUE THREAD

**Issue by sakib371** [ArcadeRenegade/SidebarDiagnostics#17]
It doesn't show name of the memory. Instead, it shows Generic Memory
![capture](https://cloud.githubusercontent.com/assets/16975740/12696896/83435218-c743-11e5-8a78-d0ca41e0678b.PNG)

**Comment by ArcadeRenegade** [comment]
This is a behavior of Open Hardware Monitor I cannot change. Sorry.
