### ISSUE TITLE
cant install program

### ISSUE THREAD

**Issue by Parasol747** [ArcadeRenegade/SidebarDiagnostics#173]
**1.  windows 10**

**2. latest (3.4.5)**

**3. none**

**4. sorry, it wont even install**

http://imgur.com/a/1OMu0

https://pastebin.com/tTXraAki

it was working perfectly for about a year but in the past few days i could not get it to open so i tried to reinstall it but i get this error. thank you

**Comment by Parasol747** [comment]
strange, i had it installed but i definitely uninstalled it before trying to install again. 

either way i reset my pc and as soon as it booted it gave me the setup for the sidebar. weird.

**Comment by ArcadeRenegade** [comment]
Yeah for some reason Open Hardware Monitor sometimes create that .sys file
and keeps an exclusive lock on it. A computer reboot fixes the issue.
