### ISSUE TITLE
External IP Address

### ISSUE THREAD

**Issue by Daisenki** [ArcadeRenegade/SidebarDiagnostics#175]
Hi,

don't know if you already know it, but when you connect to a VPN on Windows 10 and your IP changed to the VPN IP the Sidebar doesn't show anymore a external IP, maybe because it changed, it shows nothing. You need to reload the Sidebar and the external IP shows again with the new IP. 

Btw. How does the Sidebar check the external IP?

**Comment by campbeb** [comment]
The external IP is determined by loading this webpage: https://api.ipify.org/

There is nothing right now that detects a change in the IP address and causes it to reload. It is just loaded one time and assumed not to change (unless you reload manually as you did).

**Comment by Daisenki** [comment]
I like the idea of the external IP check with the Sidebar.

I connect to a VPN via IKEv2 and use a dedicated IP, but sometimes the server doesn't assign the right IP. To see my IP I need to open my Firefox and check it with a website, close it and reconnect. The tool VPNcheck Pro what I use checks only the connection, but not the IP.

If the Sidebar checks the IP in a interval time would be great.

**Comment by oppalla** [comment]
i'm also facing this situation. I use VPN, and when change external IP the SideBar Diagnostics show the previous (first) one
