### ISSUE TITLE
temperature

### ISSUE THREAD

**Issue by mwarner416** [ArcadeRenegade/SidebarDiagnostics#178]
It would be nice to have a option for either Fahrenheit or Celsius.

**Comment by ArcadeRenegade** [comment]
It's there.

**Comment by campbeb** [comment]
@mwarner416 You make the selection on Monitors tab for each individual item.
![sidebardiagnostics_](https://user-images.githubusercontent.com/1089399/29640510-3c59d3c0-882d-11e7-9a11-abafbd39cdd4.png)
