### ISSUE TITLE
CPU load aint accurate at all

### ISSUE THREAD

**Issue by askhavok** [ArcadeRenegade/SidebarDiagnostics#179]
1. Windows 10 / 6700k

2. 3.4.5

3. No relevant settings

4. Compare your load with task manager or openhwm

**Comment by tdespatie** [comment]
Same here, i5-7600k.
Version 3.4.5

**Comment by ArcadeRenegade** [comment]
How inaccurate? Numbers are completely off or just slightly different. The
values will be different when the apps poll just milliseconds away from
each other.

**Comment by tdespatie** [comment]
Roughly 3-4% higher than what task manager reports the load to be consistently.

**Comment by askhavok** [comment]
It's not consistent at all for me. It may be fully accurate sometimes, and may be 30% different other times. The only place it is consistent is during single digit percent usage, the load will not go below 11% ever
