### ISSUE TITLE
Mouse lags/jumps when sidebar values are refreshed

### ISSUE THREAD

**Issue by BondaCB** [ArcadeRenegade/SidebarDiagnostics#180]
Hi, i have used your sidebar on all my computers and I have never had this issue, but this morning i installed it on a fresh windows 10 installation and this issue has popped up. 

**1. Your Operating System**
Windows 10 home

**2. App Version**
3.4.5

**3. Any Relevant Settings**
click through, auto update, toolbar mode

**4. Steps to Reproduce**
Install and move mouse in circles, every time the values in the sidebar are updated, the mouse does a jump. Closing the sidebar solves it.

**Comment by campbeb** [comment]
What all are you monitoring? If you try to turn off monitors one at a time, can you find which one is causing it?

**Comment by gsabater** [comment]
@campbeb Nice sugestion, i have been looking the settings and looks like it's the GPU monitor.

My GPU is a Radeon RX 550 Series, and I have only temperature and fan usage with the `show hardware names` checked.

If i disable either temperature, fan usage, or even both, the mouse issue is still there.
For the moment i will disable the GPU monitoring, i hope to have helped in something.

Thanks

**Comment by ArcadeRenegade** [comment]
thank you for the info. I've been really busy lately but I'll look into it
once I get the chance.
