### ISSUE TITLE
Reserve space doesnt work anymore

### ISSUE THREAD

**Issue by marco-vogt** [ArcadeRenegade/SidebarDiagnostics#185]
Hey there,

been having this issue since I updates my Windows. When i uncheck "reserve space" the computer basically gets unusable. mouse is very laggy, opening an app can take up to 1 min. when i uncheck "reserve space" everything seems to be doing fine.

Win10 64bit, latest updates. newest sidebardiagnostics version

**Comment by mekawasp** [comment]
I'm having similar issues. As soon as I turn off 'reserve space' screen flickers and desktop icons show through windows that are open
