### ISSUE TITLE
Add way to hide network connections?

### ISSUE THREAD

**Issue by mihnt81** [ArcadeRenegade/SidebarDiagnostics#188]
I have multiple network cards in my system and some of them are disabled but still show up on the 'Network' list. I have no need to see the disabled network connections and wish there was a way to hide them from view to prevent the scrollbar from showing up when the sidebar is moused over.

**1. Your Operating System** Windows 10 Pro. V. 1709 Build 16299.214

**2. App Version** 3.4.6

**3. Any Relevant Settings**

**4. Steps to Reproduce**

**Comment by ArcadeRenegade** [comment]
You can unmonitor any device under the Monitors tab in the settings. Just uncheck the "Enabled" checkbox next to the device you want to unmonitor.

![image](https://user-images.githubusercontent.com/13874898/35823097-2eeeef8c-0a63-11e8-8ef5-c106095e601b.png)

**Comment by mihnt81** [comment]
Heh. Sorry about that. Didn't look around hard enough. My bad. Love the program by the way. Very nicely written!
