### ISSUE TITLE
Missing Diagnostics Information - CPU Fan Usage

### ISSUE THREAD

**Issue by UnitEncrypt** [ArcadeRenegade/SidebarDiagnostics#189]
OS: Windows 10 Pro - 10.0.16299 Build 16299

App Version: 3.4.6

As viewable in the attached screen-shot CPU fan usage does not show up in the diagnostics side bar when selected for use in the CPU Metrics in the Sidebar settings.

![nofanusage](https://user-images.githubusercontent.com/8958844/36737934-314bea0a-1bd4-11e8-8998-b1e953400e4a.PNG)

**Comment by veermaharaj** [comment]
Same issue with Ryzen 1500x on a b350 motherboard.
