### ISSUE TITLE
Remove / add an option to set the offset (empty space) on the top of the sidebar

### ISSUE THREAD

**Issue by InacioNeto** [ArcadeRenegade/SidebarDiagnostics#19]
There's about 60 pixels wasted on top of the sidebar. See this picture for reference: http://i.imgur.com/5W9GcNk.png

Maybe add an option to remove it / set it to a certain offset? If the configuration/close buttons are to blame, an option to toggle those or anchor them to the bottom would be good, too.

**Comment by ArcadeRenegade** [comment]
Added an option to collapse the menu bar at the top under "customize". This removes the extra space if your mouse isn't over it.
