### ISSUE TITLE
Background opacity minimum is 0.01

### ISSUE THREAD

**Issue by mightyiam** [ArcadeRenegade/SidebarDiagnostics#192]
**1. Your Operating System**

Windows 10

**2. App Version**

v3.4.6

It should be 0. Otherwise, full transparency does not seem to be possible. There is a slight difference. Here is an example:
![capture](https://user-images.githubusercontent.com/635591/38987059-277a5ba8-43d7-11e8-998b-889d324e7729.PNG)

**Comment by mightyiam** [comment]
It seems that the `0.01` minimum is [here](https://github.com/ArcadeRenegade/SidebarDiagnostics/blob/19a1743a130f2583be31e6ac0b6883252b82262d/SidebarDiagnostics/Settings.xaml#L180). Perhaps changing to `0` would be the only change necessary. Perhaps not. I'm a JavaScript guy.

**Comment by ArcadeRenegade** [comment]
The reason for the 0.01 is because of a bug with WPF where if the
background is completely opaque then you cannot interact with it with the
mouse.

**Comment by ArcadeRenegade** [comment]
If you really want 0 opacity you can modify the .json settings file and
change the BGOpacity property value to 0.

%LOCALAPPDATA%\SidebarDiagnostics\settings.json

**Comment by mightyiam** [comment]
Thanks for the answer. What do we use interaction worth the background for, please? In other words, what will we not be able to do without it?
Could you provide a URL for a WPF bug, or a forum thread about this, for our understanding, please?

**Comment by ArcadeRenegade** [comment]
You won't be able to hover over it, scroll through it, or click on the
settings or close buttons in the top right.

**Comment by mightyiam** [comment]
I tried setting to 0. Yes, I see the issue probably just like you saw it. Not a nice UX.

Did you try [using a `solidcolorbrush`](https://stackoverflow.com/questions/1646346/create-a-fully-transparent-wpf-window-to-capture-mouse-events#comment1528443_1646459)?

**Comment by mightyiam** [comment]
I guess that [this comment](https://stackoverflow.com/questions/1646346/create-a-fully-transparent-wpf-window-to-capture-mouse-events#comment51803422_1646459) pretty much destroys the previous one I linked to.

Is [this answer](https://stackoverflow.com/a/4208083), even though has 12 points, just plain wrong, like [this comment](https://stackoverflow.com/questions/1646346/create-a-fully-transparent-wpf-window-to-capture-mouse-events#comment51803654_4208083) states?

I've read all answers and their comments and it seems that perhaps [this answer](https://stackoverflow.com/a/38545912) could lead to an understanding of the correct implementation, which is implied to be using `Mouse.Capture`. Do you feel that this could be the correct solution, @ArcadeRenegade ?
