### ISSUE TITLE
Indicate cpu load with bar instead of percentage

### ISSUE THREAD

**Issue by veermaharaj** [ArcadeRenegade/SidebarDiagnostics#193]
Is there any chance we can get the processor usage to display with graphs/bars instead of just percentages.

Graphically displaying it is just easier to read.

Just a humble request, not so much a bug.

![capture](https://user-images.githubusercontent.com/17953149/39071635-ccc24e84-44b5-11e8-820f-35358d0657ee.PNG)

**Comment by despotak** [comment]
That would be really helpful.

**Comment by GibStorm** [comment]
Yeah, that would be awesome. +1 from me.
