### ISSUE TITLE
Performance Counter cache is corrupted (solutions doesn't work)

### ISSUE THREAD

**Issue by lifeproofminds** [ArcadeRenegade/SidebarDiagnostics#198]
Hello,
I'm stuggling with this error:
![1](https://user-images.githubusercontent.com/39910965/40922596-4cd3569e-681b-11e8-822a-70bd7e973f2f.PNG)
It suddenly started to appear a while ago and I have no clue why. Reinstall and the solution described in Wiki doesn't work. I tried to follow the steps [here](https://support.microsoft.com/en-us/kb/2554336) (this link is in Wiki) - I checked the registry and I'm not sure what to think about the values - all REG_DWORD had values other than 1, 2 or 4 except one PerfHost "ErrorControl" had value 1. I changed to 0 but without results.

My Event Viewer if that helps:
![2](https://user-images.githubusercontent.com/39910965/40924156-3d12cc68-681f-11e8-93da-d46a55dcf4ae.PNG)

And this error pops up when I launch the sidebar, have first error already in front of me (and sidebar has a loading symbol) and I want to open sidebar's settings (pressing OK makes sidebar to crash and force close):
![3](https://user-images.githubusercontent.com/39910965/40924652-7bbb2720-6820-11e8-9e0a-6a13529a1118.PNG)

**1. Your Operating System**
Windows 10 Pro v1803 (64bit)
**2. App Version**
3.4.6 (and older)
**3. Any Relevant Settings**
No
**4. Steps to Reproduce**
Every time after bringing out laptop from hibernation, launching the app, opening its settings, after some notifications.

**Comment by heyepic** [comment]
Same, issue keeps reappearing. Second command in FAQ works but wake from sleep seems to make the issue reappear for me.
