### ISSUE TITLE
Set network traffic unit to KByte/s and MByte/s

### ISSUE THREAD

**Issue by InacioNeto** [ArcadeRenegade/SidebarDiagnostics#20]
Sorry for the issue spam, I hope it's okay.

Please add an option to display network I/O in bytes/second instead of bits/second (current implementation). It's much more intuitive for some people (me included), and would make for a great addition!

**Comment by ArcadeRenegade** [comment]
It's there dude :P get v2.2.1

**Comment by InacioNeto** [comment]
Oh my, I'm so sorry! Updated!
