### ISSUE TITLE
explorer.exe freezes immediatley after startup

### ISSUE THREAD

**Issue by Commifreak** [ArcadeRenegade/SidebarDiagnostics#202]
**1. Your Operating System**
Win10 (1709 b16299.492)

**2. App Version**
3.4.6

**3. Any Relevant Settings**
Reserve space: No
Always on top: Yes

**4. Steps to Reproduce**
Double click the Symlink, App starts up - explorer.exe freezes now and after a minute it restarts itself - every time :(

Any ideas?

**Comment by Civrock1** [comment]
Same issue here on a new Windows 10 laptop I got at work... when Sidebar Diagnostics is first started, or reloaded, Windows Explorer starts taking up about 30% CPU and becomes essentially unresponsive until force restarted via Task Manager, at which point it's fine... until the next time Sidebar Diagnostics is reloaded one way or another.

**1. Your Operating System**
Win10 (1709 16299.125)

**2. App Version**
3.4.6

**3. Any Relevant Settings**
Reserve space: No
Always on top: No

**4. Steps to Reproduce**
Anything that loads or reloads Sidebar Diagnostics, such as during Startup or by using the in-app Reload option.

**Comment by kyay006** [comment]
I have the same situation.but I found it was because set it on display#2,if on display1 else haven't this question.Hope to be repaired
