### ISSUE TITLE
Reserved space duplicates after unlocking PC

### ISSUE THREAD

**Issue by Galarzaa90** [ArcadeRenegade/SidebarDiagnostics#203]
**1. Your Operating System**
Windows 10 Pro, Build 1803

**2. App Version**
v3.4.6

**3. Any Relevant Settings**
I have two monitors, and I have the sidebar set to the second monitor, with the reserve space setting.

**4. Steps to Reproduce**
1. Boot the system normally
1. Lock the screen (Win + L)
1. Unlock
1. Now the previously reserved space is empty, and the sidebar has reserved another chunk.

This is fixed by closing the application and opening it again.

![image](https://user-images.githubusercontent.com/12865379/43993990-51b6bf98-9d4a-11e8-8d1c-7759f73fa213.png)

**Comment by ArcadeRenegade** [comment]
There must be something else happening as well because this doesn't happen
when I lock and unlock my PC.

**Comment by ArcadeRenegade** [comment]
try with the new 3.5.1 version.
also... auto-update broke with 3.5.0 so you may have to re-install:
https://github.com/ArcadeRenegade/SidebarDiagnostics/releases/tag/3.5.1

**Comment by Galarzaa90** [comment]
Yes, this seems to be fixed now 👌
