### ISSUE TITLE
4k Monitor and scaling causing bar to move to left side and push applications

### ISSUE THREAD

**Issue by jonchen727** [ArcadeRenegade/SidebarDiagnostics#206]
After opening the app reserve space does not work, when I change any settings it sends the bar flying to the left side of my screen even tho its set up to right side, pushing everything to the left. I have tried to disable high dpi settings, the only way for it to work is if I change display scaling to 100%. I am not using the control panel display scaling settings to change the scaling, rather I followed the instructions and used the windows 10 display scaling. 

**1. Your Operating System**
Windows 10 64 bit Home
**2. App Version**
3.4.6
**3. Any Relevant Settings**
4k monitor display scaling > 100% 
**4. Steps to Reproduce**
4k monitor with display scaling >100%

**Comment by cah-98** [comment]
Same here on a 1440p monitor. In the new update (3.5.0) it also makes the program unable to stick to either the left or right side, it goes and stays a bit to the left of the middle of the screen and a bit above the screen (See picture).
![capture2](https://user-images.githubusercontent.com/45916678/50144566-da821000-02af-11e9-8c6b-30c6ca992dc3.PNG)

**Comment by ArcadeRenegade** [comment]
🤔 I dont have a 4k monitor but I will try to replicate with my 4k TV. What
version of windows?

**Comment by ArcadeRenegade** [comment]
Do you have a custom DPI set in windows settings?

**Comment by cah-98** [comment]
Yes i do, it works as it should when i disable the display scaling as said in the first post above. Display scaling above 100% makes this happen. I have Windows 10 Pro ver 1803.

**Comment by ArcadeRenegade** [comment]
Microsoft must have changed monitor scaling behavior in one of the recent Windows releases. I used to work fine on 4k monitors with custom until recently.

**Comment by Jp4Real** [comment]
Same issue here on my second monitor, DPI scalling is active on my frist monitor, bug the sidebar is displayed on the second monitor which has not sacalling enabled, if I turn off scalling completely the issue is resolved. I'll revert to the last update for now since it was working ok then

1. Your Operating System
Windows 10 64 bit Home ver 1803
2. App Version
3.5.0
3. Any Relevant Settings
Monitor 1 : 3440X1440 Scalling to 125%
Monitor 2 : 1920X1080 Scalling to 100%
4. Steps to Reproduce
Monitor 1 : 3440X1440 Scalling to 125%
Monitor 2 : 1920X1080 Scalling to 100%

**Comment by ArcadeRenegade** [comment]
try with the new 3.5.1 version.
also... auto-update broke with 3.5.0 so you may have to re-install:
https://github.com/ArcadeRenegade/SidebarDiagnostics/releases/tag/3.5.1

**Comment by Jp4Real** [comment]
WOW ! this is working perfectly, you sir are awesome and crazy fast. Working perfectly, BTW I LOVE SidebarDiagnostics, I'm totally donating

**Comment by ArcadeRenegade** [comment]
Appreciate it! Thanks!

**Comment by despotak** [comment]
I can confirm that it works on build `18305`. Really appreciated fix.
