### ISSUE TITLE
[Feature Request] hostname header

### ISSUE THREAD

**Issue by boohyaka** [ArcadeRenegade/SidebarDiagnostics#208]
Hi, love your work! Just a simple suggestion/feature request: I think it would be a great idea to be able to display the hostname, maybe as the header of the whole toolbar or something like this?

Your project is amazing for me that manages many computers with remote control and having the hostname displayed would be really come in handy :)

Cheers!

**Comment by ArcadeRenegade** [comment]
Added it :)

![image](https://user-images.githubusercontent.com/13874898/50270399-49fa1b80-03e6-11e9-8dba-aac370e38b05.png)

**Comment by ArcadeRenegade** [comment]
Also if you want to deploy your settings to multiple computers, just edit this JSON file and you can copy it to another computer.

```
%LOCALAPPDATA%\SidebarDiagnostics\settings.json
```
