### ISSUE TITLE
Will not dock to right-side of either screen

### ISSUE THREAD

**Issue by heyepic** [ArcadeRenegade/SidebarDiagnostics#209]
**1. Your Operating System**
Windows 10 64bit
**2. App Version**
Latest
**3. Any Relevant Settings**
4K Main laptop screen (15") second 1440P screen (27")
**4. Steps to Reproduce**
It no longer knows how to dock to either right-most side of either screen. It ends up about 70% from left. I've tried many things, most of which result in it constantly moving around and messing with windows that I have to close it.

Any help? I'm a 2x donater. Thanks!

**Comment by ArcadeRenegade** [comment]
I just updated it to he latest version of .NET framework.

Could you please try the new version? You will have to install .NET framework 4.7.1 

Let me know if the issue persists. Thanks!

**Comment by heyepic** [comment]
Sadly, that's a no go:

**Details**
.NET Framework 4.7.1 or a later update is already installed on this computer.

**Comment by ArcadeRenegade** [comment]
try with the new 3.5.1 version.
also... auto-update broke with 3.5.0 so you may have to re-install:
https://github.com/ArcadeRenegade/SidebarDiagnostics/releases/tag/3.5.1
