### ISSUE TITLE
Sidebar in incorrect position

### ISSUE THREAD

**Issue by saxopwn** [ArcadeRenegade/SidebarDiagnostics#21]
I've got two 4K monitors set to 150% scaling (using the compatible scaling method). Setting the sidebar to appear on the right side of the left monitor reserves the space appropriately but the bar itself appears in the middle of the monitor on the right. The bar itself and the settings menu are also much larger than they were before. I've messed with disabling scaling for high-DPI displays in the comparability menu but haven't had any luck.

**Comment by ArcadeRenegade** [comment]
Could you post a screenshot? Thanks.

**Comment by ArcadeRenegade** [comment]
Also does it work correctly without dpi scaling?

**Comment by saxopwn** [comment]
Turning off DPI scaling didn't change anything. Screenshot is attached.
<img width="3000" alt="sidebarbug" src="https://cloud.githubusercontent.com/assets/16937833/12701011/43b40d94-c7b7-11e5-9a1d-f57bc323fcd8.png">

**Comment by ArcadeRenegade** [comment]
Good god that is a lot to of pixels lol. This is going to be difficult to troubleshoot because I don't have any 4k monitors to replicate it. 

It looks like it's not getting the correct top and right of your second monitors work area. The top looks like the same as your primary monitor. 

I'll have to send you a debug program that will get me some data to work with.

**Comment by saxopwn** [comment]
Cool. Let me know what I can do to help. It seems similar to what this user was experiencing: https://www.reddit.com/r/pcmasterrace/comments/4325tb/updated_my_sidebar_intel_skylake_cpu_support/czhwpgj

Also, I'm running the latest Insider build of Windows 10. I updated the OS and sidebar simultaneously so I'm not sure what broke it.

**Comment by ArcadeRenegade** [comment]
It worked before? Think you could try downloading version 2.1 or 2.0 and seeing if the same thing happen? I made a big change to how it handles monitors then.

Here is a console program that will help debug. It's going to print out a bunch of information about your monitors. If you could copy it and send it to me it'll help.

https://drive.google.com/file/d/0B2nGKa6VrrDOOG1GWndBNk9MbjQ/view?usp=sharing

**Comment by saxopwn** [comment]
```
Monitor Debug Program

Monitor #0

Is Primary: True

Size:
Left: 0
Top: 0
Right: 2560
Bottom: 1440

WorkArea:
Left: 0
Top: 0
Right: 2560
Bottom: 1400

DPIx: 96
DPIy: 96
ScaleX: 1
ScaleY: 1

Emulate Sidebar Left
Left: 0
Top: 0
Right: 180
Bottom: 1400

Emulate Sidebar Right
Left: 2380
Top: 0
Right: 2560
Bottom: 1400

Monitor #1

Is Primary: False

Size:
Left: 2560
Top: -884
Right: 4000
Bottom: 1676

WorkArea:
Left: 2560
Top: -884
Right: 4000
Bottom: 1636

DPIx: 96
DPIy: 96
ScaleX: 1
ScaleY: 1

Emulate Sidebar Left
Left: 2560
Top: -884
Right: 2740
Bottom: 1636

Emulate Sidebar Right
Left: 3820
Top: -884
Right: 4000
Bottom: 1636

Press any key to exit...

```

2.1.1 seems to be sized correctly. It seems like it doesn't reserve quite enough space (moves the active full screen window over but still slightly overlaps) but that not a big deal.

**Comment by saxopwn** [comment]
<img width="3000" alt="sidebarbug2" src="https://cloud.githubusercontent.com/assets/16937833/12701240/95b7395a-c7c0-11e5-8317-7f328af97deb.png">

There's a picture of the overlap.

**Comment by ArcadeRenegade** [comment]
Thanks. Version 2.1.1 does look a lot better.

Does version 2.2.1 look any better with reserve space disabled?

**Comment by saxopwn** [comment]
Turning off "reserve space" (use app bar) just has it cover whatever is behind it.

**Comment by ArcadeRenegade** [comment]
I just realized I missed a crucial step in the monitor debug program.

Could you run this version?

https://drive.google.com/file/d/0B2nGKa6VrrDOOG1GWndBNk9MbjQ/view?usp=sharing

**Comment by ArcadeRenegade** [comment]
Windows Defender is nuking my monitor debug program from orbit sigh

**Comment by saxopwn** [comment]
```
Monitor Debug Program

Monitor #0

Is Primary: True

Size:
Left: 0
Top: 0
Right: 3840
Bottom: 2160

WorkArea:
Left: 0
Top: 0
Right: 3840
Bottom: 2100

DPIx: 144
DPIy: 144
ScaleX: 1.5
ScaleY: 1.5

Emulate Sidebar Left
Left: 0
Top: 0
Right: 270
Bottom: 2100

Emulate Sidebar Right
Left: 3570
Top: 0
Right: 3840
Bottom: 2100

Monitor #1

Is Primary: False

Size:
Left: 3840
Top: -1326
Right: 6000
Bottom: 2514

WorkArea:
Left: 3840
Top: -1326
Right: 6000
Bottom: 2454

DPIx: 144
DPIy: 144
ScaleX: 1.5
ScaleY: 1.5

Emulate Sidebar Left
Left: 3840
Top: -1326
Right: 4110
Bottom: 2454

Emulate Sidebar Right
Left: 5730
Top: -1326
Right: 6000
Bottom: 2454

Press any key to exit...

```

**Comment by ArcadeRenegade** [comment]
OK those values make much more sense now. Thank you.

**Comment by ArcadeRenegade** [comment]
Could you send a screenshot of what v2.2.1 looks like with app bar disabled? I'm lost as to how why this is happening. Sorry for the trouble.

**Comment by saxopwn** [comment]
<img width="3000" alt="sidebarbug3" src="https://cloud.githubusercontent.com/assets/16937833/12701594/ee0b6630-c7ca-11e5-9643-556727399e6a.png">

**Comment by ArcadeRenegade** [comment]
oh so it is in the right position with the app bar disabled. that narrows it down to the app bar code then.

**Comment by ArcadeRenegade** [comment]
Wait that's not the latest version, v2.2.1, though since the drive used space bars are missing. I don't think you're running the latest version.

**Comment by ArcadeRenegade** [comment]
nm your first screenshot is the latest version. sorry.

**Comment by saxopwn** [comment]
<img width="3000" alt="sidebug4" src="https://cloud.githubusercontent.com/assets/16937833/12707012/443127b8-c84b-11e5-9fb0-95ac70781f82.png">

Sorry, just saw your third comment. Disabling appbar doesn't do anything. (And yes, I clicked save lol)

**Comment by ArcadeRenegade** [comment]
Damn :( it's still in the wrong spot.

Taking a closer look at that screenshot, the sidebar is configured to be on your primary monitor (horizontal one). And the sidebar looks like it anchored EXACTLY 50% further right and down than it should be. And I don't think is a coincidence that the screen's DPI values are also exactly 50% bigger than normal too. 

I have an idea, I'll implement a setting for "4k Monitor Support" and enabling it should move the sidebar to the correct position for you.

**Comment by saxopwn** [comment]
That makes perfect sense. I'd ideally have it on my second monitor but it goes offscreen to the right...probably 50% past the width.

**Comment by ArcadeRenegade** [comment]
OK i just released a new version with the aforementioned "4K Monitor Support" option.

Hopefully this works for you.

**Comment by saxopwn** [comment]
That pretty much did it. Reducing the font size and tweaking the width makes it look great. Thanks for all your help!

**Comment by saxopwn** [comment]
Is there any easier way to donate? Patreon's weird.

**Comment by saxopwn** [comment]
![sidebarbug5](https://cloud.githubusercontent.com/assets/16937833/12711718/40339022-c87f-11e5-8b64-81e9b6658bae.jpg)

Just so you know, it's still pushed offscreen when "reserve space" is enabled. Not a high priority issue though.

**Comment by ArcadeRenegade** [comment]
Dang. So close! Does it allocate that width that you see? Could you test with a maximized window on the same screen.

The appbar library was implemented by Microsoft yeaaaaars ago and they haven't updated it on a long time. It has so many quirks after all these different versions of Windows.

Maybe I should just add two slider options:  horizontal offset and vertical offset. 

Also thank you for the donation I really appreciate it. I'll look into other websites that handle them.

**Comment by ArcadeRenegade** [comment]
Btw the space different is actually 66.66%. 

Which is the inverse of your DPI scale. 1/1.50

It appears that the sidebar is 33.33% of its width to the right when "reserve space" is enabled. 

If that's true, then a quick fix would be to move it 33.33% of the sidebar width to the left only when "reserve space" is enabled.

**Comment by saxopwn** [comment]
It does allocate space for the width that you do see. Offset sliders would probably the easiest fit. Would the "reserve space" feature work with those?

**Comment by saxopwn** [comment]
Patreon's just weird because it requires you to make a "paid post" in order for you to receive any donations.

**Comment by ArcadeRenegade** [comment]
Basically the way the appbar library works is you give it a rectangle and edge for the window to dock to. It gives you back an approved rectangle. This approved rectangle is the reserved space.

So what's happening is the program is telling shell32.dll, "hey I want to put my sidebar in this rectangle here". Which is the correct space. But then shell32 is responding "woah you can't go there. go a little to the right." because it thinks that's not an allowed space for the appbar.

Why? I have no idea. This functionality was added in shell32.dll version 4.0 which dates back to 1999. And it was added to windows in XP. Waaaaaaaaaaaaay before high resolution or high dpi monitors even existed. And it seems that Microsoft hasn't bothered to include support for it.

So if we implement a offset slider it might work. But if you go too far to the left or right then it won't recognize what screen edge you are trying to dock to and give up.

**Comment by saxopwn** [comment]
Interesting. Windows is long overdue for an OSX-esque overhaul but they can't because of all their commercial users relying on ancient bits of code. 

Don't put too much time into this because of my specific error- most people haven't moved up to high DPI monitors yet. I really appreciate your help though.

**Comment by ArcadeRenegade** [comment]
It's ok. I'd like to publish it on the Windows 10 App store which means I need to get it as polished up as possible.

I'll switched to paypal.me

**Comment by saxopwn** [comment]
Sweet. Give me the info and I'll switch the donation to there.

**Comment by ArcadeRenegade** [comment]
https://github.com/ArcadeRenegade/SidebarDiagnostics/releases/tag/2.3.1

OK here is the new version with the horizontal and vertical offset settings. Hopefully it works.

https://www.paypal.me/arcaderenegade

**Comment by saxopwn** [comment]
Okay, so the reserve space feature no longer pushes the bar off the screen. Didn't even have to touch the offset settings. However, it doesn't reserve quite enough space. It seems to reserve only about 2/3 of the space required and adjusts this according to the selected sidebar width.

**Comment by ArcadeRenegade** [comment]
That's really odd. Maybe I can have it just multiply the rectangle width sent to the appbar function by your DPI scale (1.5 for your screen). But only if "4K Monitor Support" is enabled.

**Comment by saxopwn** [comment]
That would be my first guess

**Comment by ArcadeRenegade** [comment]
OK I implemented it.

https://github.com/ArcadeRenegade/SidebarDiagnostics/releases/tag/2.3.2

**Comment by saxopwn** [comment]
So originally turning on "reserve space" reserved the appropriate amount but half the bar went offscreen. I started playing with the offset settings to try and fix it. I was able to move it around but not to the right spot. Re-entering an offset of 0 put it in the right spot and it's working perfectly.

Then I changed the order the categories displayed in and it went back to the initial state. Same thing fixed it. I'm assuming it's the odd behavior you mentioned in 2.3.1. 

As far as I'm concerned, we're perfect. I'm happy to test any high DPI-related tweaks you make in the future though.

**Comment by ArcadeRenegade** [comment]
Hmm. That's really odd behavior. I wonder what caused that. It's quirky but at least it (usually) works. 

Thanks for all the help.

**Comment by saxopwn** [comment]
Also, opening a game in fullscreen on the primary monitor pushed it halfway over again. Setting an offset of -90 fixed it. Exiting the game didn't change anything.

No problem!

**Comment by ArcadeRenegade** [comment]
how has it been so far?

**Comment by saxopwn** [comment]
No issues aside from some quirkiness with the reserve space feature.

**Comment by ArcadeRenegade** [comment]
I'm going to close this for now but let me know if you have any more issues.

**Comment by ArcadeRenegade** [comment]
I know this is late but I figured out the core problem and fixed it in v3.2.0

**Comment by saxopwn** [comment]
Beautiful. You’re a hero. What wound up being the problem?

**Comment by ArcadeRenegade** [comment]
Well I realized I could emulate a high DPI monitor by simply changing my primary monitor's Windows scale setting and signing out and back in. 

From there it was just a lot of trial and error. 

Apparently if your app is per monitor DPI aware then the desktop size is directly correlated to the primary monitor's DPI scale. 

Before I was determining the position based on the DPI scale of the monitor the sidebar was on. 

Now it's just based on the primary monitor. 

Added a couple tweaks to get the "reserve space" functionality working and the tray icon context menu in the right place and it was golden.

**Comment by saxopwn** [comment]
I’m impressed!

**Comment by ArcadeRenegade** [comment]
Thanks! I'm just glad it's working correctly. It had high DPI issues ever since I first released it.

**Comment by Yutooop** [comment]
funny this issue is still a thing today :(
