### ISSUE TITLE
Changing resolution causes the sidebar to create reserved space.

### ISSUE THREAD

**Issue by MilkManEX** [ArcadeRenegade/SidebarDiagnostics#210]
1. Your Operating System
Windows 10 Pro Version 1809 (Build 17763.149)

2. App Version
3.5.0

3. Any Relevant Settings
Docked to right side of monitor

4. Steps to Reproduce
Change resolution of main monitor from default resolution to any lower resolution, then change it back. The sidebar will now have created reserved space on the right side of the screen. You can correct it by changing it to dock on the left, saving it, then changing it back.

![image](https://user-images.githubusercontent.com/16171167/50176144-9fdaa080-02cc-11e9-8714-9cc7ca61b8fe.png)
![image](https://user-images.githubusercontent.com/16171167/50176161-ac5ef900-02cc-11e9-833e-a572b1289e83.png)
![image](https://user-images.githubusercontent.com/16171167/50176169-b123ad00-02cc-11e9-9441-fc02f14dfdcc.png)

**Comment by ArcadeRenegade** [comment]
try with the new 3.5.1 version.
also... auto-update broke with 3.5.0 so you may have to re-install:
https://github.com/ArcadeRenegade/SidebarDiagnostics/releases/tag/3.5.1
