### ISSUE TITLE
Flashing/Blinking when games are alt-tabbed

### ISSUE THREAD

**Issue by cars11** [ArcadeRenegade/SidebarDiagnostics#214]
the window flashes (vanishes and comes back) every 1-2 seconds for a couple minutes when i alt tab out of a full screengame
**1. Your Operating System**
win10 1809

**2. App Version**
can't tell you that since there is no info in the settings or in the taskbar menu, but it is the latest as of 03/01/2019
**3. Any Relevant Settings**

**4. Steps to Reproduce**
run bf5 or other full screen game > alt tab out

possible relevant info: running two monitors (monitor 1 is gsync @ 100hz, monitor 2 is 60hz and the one the sidebar is running on)

**Comment by maulpets** [comment]
Same issue with other apps

**Comment by maulpets** [comment]
win10 16299
