### ISSUE TITLE
Bars instead of %

### ISSUE THREAD

**Issue by iFEARR** [ArcadeRenegade/SidebarDiagnostics#22]
Hey, can you add an option to display bars instead of % ( something like drive bars ), it's much easier to read. And maybe a history graph 

Something like this http://i.imgur.com/WcKDZVs.png

**Comment by mclovinnnnn** [comment]
i would also love to get bars in addition to percent symbols. beside that, very good work in my opinion.

**Comment by lephyrus** [comment]
I've just discovered SidebarDiagnostics and like it a lot, thanks @ArcadeRenegade! Providing a "Load Bar" for RAM and CPU, exactly like the one that's available for Drives, would make getting a sense of the system load at a glance so much easier. Here's hoping you will reconsider this fairly minor feature.

**Comment by BlueJimmyy** [comment]
Did this ever get added? It's marked as compelted but I cannot see how to enable it for GPU, RAM, CPU etc?
