### ISSUE TITLE
No longer reading GPU fan speed

### ISSUE THREAD

**Issue by Front0000** [ArcadeRenegade/SidebarDiagnostics#223]
**1. Win10 ver.1809**

**2. 3.5.2**

**3. Gigabyte 2070 fan speed not being read despite it being read in HWinfo**

**4. None**

Recently switched from a 1070 to a 2070 and the fan speed is no longer being read in the sidebar as it used to be.

**Comment by n8v8R** [comment]
**1. WIN 10 Pro x_64 v1809 b 17763.348**
**2. 3.5.2**
**3. P751TM1-G with 2 fans, CPU/GPU fan usage enabled in the app**
**4. installed the app and set the settings but neither fan is being reported**

**Comment by n8v8R** [comment]
_voltage_ for CPU/GPU/RAM are unfortunately _not being displayed_ either, despite being selected in the app's monitor settings.

**Comment by n8v8R** [comment]
meantime updated to W 10 Pro x_64 v 1903 b 18362.116 and the issue is still present.

as mentioned earlier also voltage for CPU/GPU/RAM is a no show and Temperature/Clock stating `No Value`

**Comment by n8v8R** [comment]
I suppose that is a consequence of:

> The WinRing0_1_2_0 service failed to start due to the following error: 
> Windows cannot verify the digital signature for this file. A recent hardware or software change might have installed a file that is signed incorrectly or damaged, or that might be malicious software from an unknown source.

It shows in the Win registry as

`C:\Users\username\AppData\Local\SidebarDiagnostics\app-3.5.2\OpenHardwareMonitorLib.sys`
___
If this is the source development https://github.com/openhardwaremonitor/openhardwaremonitor/tree/master/External/WinRing0 than it seems to have ceased development 7 years ago.

I would reckon that hardware monitor tools, i.e. HWiNFO | HWMonitorPRo, using different code to access  hardware info/sensors and thus are working as expected.
___
Wondering whether SidebarDiagnostics will be updated to reinstate full functionality, else there seems little point in using it.

**Comment by n8v8R** [comment]
Additionally OpenHardwareMonitor beta 8 does not show Fan speeds for my node either and there seem to be plenty of reports https://github.com/openhardwaremonitor/openhardwaremonitor/issues that things may not work well on various systems.

Perhaps OpenHardwareMonitor, which developments seems stalled for some time (beta 8 been release November 6, 2016) is not useful as a hardware monitoring source for SidebarDiagnostics.

**Comment by eddiegalvez** [comment]
+1 I for missing fan speeds in the display

 I do have cpu temp and cpu clock showing though
