### ISSUE TITLE
[feature suggestion] add battery status/info for laptop users

### ISSUE THREAD

**Issue by n8v8R** [ArcadeRenegade/SidebarDiagnostics#224]
It would a nice addition to have on display

- status: loading/discharging/full
- remaining time/percent till flat

**Comment by ArcadeRenegade** [comment]
i ordered a laptop recently. once it arrives i can develop this and test it thoroughly before releasing

**Comment by GibStorm** [comment]
This would be awesome.

**Comment by ntoskrnl4** [comment]
Any update on this? I feel it would be nice to include in this program, as a one-stop spot for seeing everything about your system and thus a laptop's battery would be a part of that.

I attempted to clone/write this myself, but I don't know how to get the Open/LibreHardwareMonitor dependencies.

**Comment by ArcadeRenegade** [comment]
Sorry I've been really busy and probably can't get to this.

You can init submodules by running this command:

`git submodule update --init --recursive`

After the submodule is initialized, if you want to pull latest commits you can run:

`git submodule update --remote`

After you initialize the submodules, open LibreHardwareMonitor and build the LibreHardwareMonitorLib project.

**Comment by ntoskrnl4** [comment]
> Sorry I've been really busy and probably can't get to this.

No worries, that's why I tried to build it myself. Thank you so much for all your hard work on this program, I absolutely love it.

I'll try running/building that this afternoon when I get home, thanks for the tip!

**Comment by ameeno** [comment]
+1 would like this a lot.
