### ISSUE TITLE
Windows zoom at 125%: left pannel hidden on startup

### ISSUE THREAD

**Issue by andreashe** [ArcadeRenegade/SidebarDiagnostics#225]
Windows 10 64

Sidebar 3.5.2

3 Monitors

Changed Windows to 125% zoom. Now the bar on the very left monitor is not shown at startup. Only when I go to settings, set "right", apply, set "left" apply.

Before I did the zoom, it worked.

**Comment by DavidMez** [comment]
same problem when modify anything visual config like color, scale, or something 

V3.5.3 
Win: 10 64Bit
