### ISSUE TITLE
[Feature request] Top/Bottom Dock

### ISSUE THREAD

**Issue by Front0000** [ArcadeRenegade/SidebarDiagnostics#227]
Just wanted to ask if you could add an option to dock it to the top/bottom of your screen for those of us with vertical side monitors. 

I tell all my buddies to use this cause it's great for monitoring temps while playing games.

**Comment by jfevia** [comment]
I second this, I was looking for such an option since the side back is obtrusive in my work area.

**Comment by jfevia** [comment]
It would be helpful to have an idea if what you consider "looking good". Maybe someone can create a pull request once the details are clear.
