### ISSUE TITLE
(Side)bar on the bottom on the screen?

### ISSUE THREAD

**Issue by Tepperotta97** [ArcadeRenegade/SidebarDiagnostics#23]
Is it possible to have it along the bottom of the screen? I use it on my secondary monitor which is 4:3. I need all the horizontal space I can get.

**Comment by ArcadeRenegade** [comment]
I tried to implement this today and the text looked absolutely awful. Couldn't get it to wrap correctly. I'll keep trying but this might not get implemented.

**Comment by ArcadeRenegade** [comment]
Even with the best wrapping I could do. It is very difficult to read.

![image](https://cloud.githubusercontent.com/assets/13874898/13163819/ef8b1b6a-d664-11e5-915d-4802173b506c.png)

**Comment by Tepperotta97** [comment]
I am trying to wrap my brain around finding a solution for the problem. Would you mind keeping this page open and i'll comment at a later time with a solution.

**Comment by WHeesters** [comment]
I was wondering if you've had time to look at this feature request since the last time. I would love for this to be an option. (p.s. loving the sidebar so far:P)

**Comment by ArcadeRenegade** [comment]
It's pretty difficult to implement, honestly. The text doesn't wrap well.

**Comment by Silverbolth** [comment]
Hi
I too would like to be able to put the "sidebar" on the bottom of my 2nd screen
The example shown on your post on Feb 18 is exactly what I'm looking for... the only thing that I would need to do to make it perfect, would be to make the sidebar taller... this way, everything on the same group (CPU, RAM, GPU, etc...) would stack on top of each other, giving more space for each group horizontally, which in return, would probably make it easier for the wraping... 
Could you put the option with a disclosure like "beta feature" or something
please pretty please?
