### ISSUE TITLE
No display on dual screens

### ISSUE THREAD

**Issue by StickIT** [ArcadeRenegade/SidebarDiagnostics#232]
**1. Your Operating System** 
Windows 10

**2. App Version**  
Last one

**3. Any Relevant Settings**
Space reserved on the screen but no display.

**4. Steps to Reproduce**
2 screens with differents resolutions. Work on the left screen but not on the right one.
https://i.ibb.co/9qYz6kZ/Sans-titre.png

**Comment by Tar-rask** [comment]
I can reproduce as well. problem is with Screen #2 
I found the temporary solution is. Dock it on the Right, then back to the Left.

**Comment by ArcadeRenegade** [comment]
What your Windows DPI settings?

https://github.com/ArcadeRenegade/SidebarDiagnostics/wiki/DPI-Settings

**Comment by bnaevil** [comment]
I can confirm this issue. App is set to use Left side of screen #2. Space is reserved on screen, but sidebar does not appear. Changing to dock Right and applying does make it appear on the right (though it is misaligned down by a few hundred pixels), then changing back to Left and applying displays correctly.

Display #2 is 1920x1080 set to 100% scaling. Monitor #1, however, is 4K resolution at 150%.

**Comment by Tar-rask** [comment]
@ArcadeRenegade Using the newer scaling.
Monitors are two different resolutions and two different scalings. Video coming from the same video card (1080ti) one display port one dvi-d (though that shouldn't matter)

**Comment by generix** [comment]
Same issue here after a new monitor purchase using the "newer" Window scaling:
Monitor #1 4k 3840x2160 150% scaling
Monitor #2 1920x1200 100% scaling

Can eventually get it to show up if I mess with scaling on the 2nd monitor, but not right off the bat.
