### ISSUE TITLE
Enhancements Request for 2019

### ISSUE THREAD

**Issue by Mohammednt0** [ArcadeRenegade/SidebarDiagnostics#237]
Good day,

it's 2019 now, the last request for the below enhancements was 3 years ago (2016) , just to check if there is any possible changes

is it possible to add the following features?

- Auto Shutdown: 
it would be very useful if there is "Auto Shutdown Option" for every hardware when its temp gets very high

- sound alerts: 
it would be very nice if there is "sound alert option" for every hardware when its temp gets very high

- Current System Up-Time:
 Is there any chance you could add the current system Up-Time?

- Battery Cell Details, 

- Ethernet Hardware Monitor

- HDD's temperature:
can you use open hardware monitor to get the HDD's temperatures and then match it with logical drives so all logical drive of HDD0 will have the same temperature, is this possible?
if its not possible what about to add option that will give me the choice if i want logical drive view (No Temperature Info) or Disk view (With Temperature Info), Disk view will only show the general information of the disk along with the Temperature, is this possible?

thanks a lot for the software, you made my life easier, Excellent work

**Comment by radcats8** [comment]
for sure I would love Current System Up-Time in this great software.

**Comment by Mohammednt0** [comment]
bad news for us, thanks for your reply, wish you the best
