### ISSUE TITLE
Hotkeys with number pad (and a crash)

### ISSUE THREAD

**Issue by Simber1** [ArcadeRenegade/SidebarDiagnostics#24]
Right now if you set a hot key to a number pad key with num lock on, it will not work with num lock off and visa versa. It counts num pad 0 and num pad ins as 2 different keys in the hot keys bit.

Also i got [this](http://i.imgur.com/EWHoNrT.png) crash when using a reload hot key while it was loading after clicking ok in the options. It can also be caused (on my setup) by mashing a reload hotkey (not 100% of the time).

**Comment by ArcadeRenegade** [comment]
You must be a QA tester 😂

I'll add checks to the hotkeys to prevent null references but I think the behavior with number lock is built into user32.dll RegisterHotKey so I can't fix that.

**Comment by ArcadeRenegade** [comment]
The crash on reload hotkey spam is fixed now.
