### ISSUE TITLE
Sync dark/light theme with Windows 10

### ISSUE THREAD

**Issue by xmha97** [ArcadeRenegade/SidebarDiagnostics#247]
The latest version of windows has a dark theme, which changes elements such as context menus to be light, so if I schedule windows to change to the dark theme automatically at night, it wouldn't affect SidebarDiagnostics, because all elements are skinned.​
![Windows 10 Light Theme](https://user-images.githubusercontent.com/23485114/63882619-9f5fe100-c9e7-11e9-8c65-edd99fc83678.png)

**Comment by amirrammari** [comment]
Yes, that work but I want the background color to also become the color of the taskbar.

![SidebarDiagnostics](https://user-images.githubusercontent.com/23485114/63886570-071a2a00-c9f0-11e9-972f-fece6873074f.png)

**Comment by oppalla** [comment]
its cosmetically but will be nice to improve this feature

**Comment by xmha97** [comment]
@ArcadeRenegade Do you have any plans to add this feature?

**Comment by ArcadeRenegade** [comment]
Sorry I don't have the bandwidth for feature requests at this time but pull requests are welcome.
