### ISSUE TITLE
Stoped working after kb4512941

### ISSUE THREAD

**Issue by meatwar** [ArcadeRenegade/SidebarDiagnostics#249]
Windows 10 Pro x64
App 3.5.3

Same issue in previous 3.5.2, so removing the Windows update it works again.

https://support.microsoft.com/pt-pt/help/4512941/windows-10-update-kb4512941

**Comment by b0xBR** [comment]
Same here!

**Comment by ArcadeRenegade** [comment]
Any error message or error logs?

**Comment by b0xBR** [comment]
Nope, simply when I install, nothing is shown, but it appears on start menu...

**Comment by toth-Daniel** [comment]
Same here :/

**Comment by asaez85** [comment]
> Any error message or error logs?

Nombre de la aplicación con errores: SidebarDiagnostics.exe, versión: 3.5.3.0, marca de tiempo: 0x5d64a3da
Nombre del módulo con errores: d3d9.dll, versión: 10.0.18362.329, marca de tiempo: 0x1ac9a115
Código de excepción: 0xc0000005
Desplazamiento de errores: 0x00000000000ac44e
Identificador del proceso con errores: 0x868
Hora de inicio de la aplicación con errores: 0x01d5635fab70cd24
Ruta de acceso de la aplicación con errores: C:\Users\asaez\AppData\Local\SidebarDiagnostics\app-3.5.3\SidebarDiagnostics.exe
Ruta de acceso del módulo con errores: C:\WINDOWS\SYSTEM32\d3d9.dll
Identificador del informe: 18507f8b-47d5-44e7-affe-6c41a3884d57
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores:

**Comment by ArcadeRenegade** [comment]
You can try the standalone version, this doesn't require installation

**Comment by ArcadeRenegade** [comment]
https://github.com/ArcadeRenegade/SidebarDiagnostics/releases/download/3.5.3/Standalone.zip

**Comment by asaez85** [comment]
Same issue with standalone version:

Nombre de la aplicación con errores: SidebarDiagnostics.exe, versión: 3.5.3.0, marca de tiempo: 0x5d657744
Nombre del módulo con errores: d3d9.dll, versión: 10.0.18362.329, marca de tiempo: 0x1ac9a115
Código de excepción: 0xc0000005
Desplazamiento de errores: 0x00000000000ac44e
Identificador del proceso con errores: 0xe50
Hora de inicio de la aplicación con errores: 0x01d5636ce45f20b3
Ruta de acceso de la aplicación con errores: C:\Programas\Sidebar Diagnostics\SidebarDiagnostics.exe
Ruta de acceso del módulo con errores: C:\WINDOWS\SYSTEM32\d3d9.dll
Identificador del informe: 9e889ded-2ebf-49ca-8e55-473274c21620
Nombre completo del paquete con errores: 
Identificador de aplicación relativa del paquete con errores:

**Comment by toth-Daniel** [comment]
Any news? :) Not trying to be inpatient, just curious if have made any progress :D

**Comment by b0xBR** [comment]
Hi!
After updating RivaTuner to Build20686, SidebarDiag started to work again. For those users whose have RivaTuner installed, please, update and feedback here.

**Comment by toth-Daniel** [comment]
Ah, so that's why it started working even with that Windows update installed :D Yap, that's the fix, update RTSS
