### ISSUE TITLE
Move load % next to bars

### ISSUE THREAD

**Issue by ksarnelli** [ArcadeRenegade/SidebarDiagnostics#25]
In an effort to save vertical space, can the load percentages be displayed next to the horizontal bars?  This would also require load % bars to be added to things like RAM (which makes sense anyway in my opinion). Thanks.

**Comment by ArcadeRenegade** [comment]
Could you elaborate? Do you mean the bars for drive load? Putting load percentage next to the drive load bars would only save about 18 pixels per drive when extra drive details is shown. And extra drive details is optional so if the user chooses it then it is implied it will take up a lot more space. Also putting the text next to the bars would effect the clean vertical alignment of everything. 

Replacing load percentages with bars for the other hardware wouldn't reduce vertical space any either. 

Thanks.

**Comment by ksarnelli** [comment]
Yea, I have a lot of drives and like to see the current R/W speeds so I have the extra details shown.  On a 1440P monitor with font size set to 10 the sidebar still extends off the bottom of the screen.  I suppose with the NIC selection update coming it will help things a bit, but I just thought that since the load % and bar are redundant that they could be on the same horizontal line.

Perhaps another solution would be to allow a more granular selection of details.  I am interested in displaying the read/write speeds of the drives but don't really care about the load/used/free since that can be derived just by looking at the bar.

**Comment by ArcadeRenegade** [comment]
Implemented your second solution.
