### ISSUE TITLE
Hey, I'd Love to Help You Adding a new Language, I Speak Spanish!

### ISSUE THREAD

**Issue by CveraMarquez** [ArcadeRenegade/SidebarDiagnostics#250]
**1. Your Operating System**
Win 10
**2. App Version**
3.5.3
Hello, As you Read on the title i speak Native-Spanish, and i'd love to help this software to be translated on a new language, Because it may help some people, who doesn't speak english very well
by missfortune, i don't know how to Program in any language, is there any form i can help?

**Comment by ixuz** [comment]
Hi @CveraMarquez 

If you want to provide Spanish language support to this software, you can use [this file](https://github.com/ArcadeRenegade/SidebarDiagnostics/blob/master/SidebarDiagnostics/Properties/Resources.resx) as a reference.

Basically, translate each text within the `<value></value>` tags to Spanish.

You can then upload the translated file directly to this issue and I'll try to adopt it into the software.
