### ISSUE TITLE
Doesn't launch after Windows Update KB4515384

### ISSUE THREAD

**Issue by sumsulk** [ArcadeRenegade/SidebarDiagnostics#253]
**1. Your Operating System**
Windows 10 Pro (64-Bit) (1903)
**2. App Version**
V3.5.3
**3. Any Relevant Settings**
All Default Settings
**4. Steps to Reproduce**
Install Windows Update KB4515384 and restart the PC

**Comment by iamjonmiller** [comment]
> **1. Your Operating System**
> Windows 10 Pro (64-Bit) (1903)
> **2. App Version**
> V3.5.3
> **3. Any Relevant Settings**
> All Default Settings
> **4. Steps to Reproduce**
> Install Windows Update KB4515384 and restart the PC

+1

**Comment by iamjonmiller** [comment]
Well, it just started working again...
![2019-09-21 15_16_35-Sidebar](https://user-images.githubusercontent.com/21957977/65379771-d346c300-dc82-11e9-9126-3716ac89c051.png)
