### ISSUE TITLE
Suggestion: Acrylic blur background option

### ISSUE THREAD

**Issue by c16u** [ArcadeRenegade/SidebarDiagnostics#254]
The sidebar should have an optional [Acrylic blur](https://docs.microsoft.com/en-ca/windows/uwp/design/style/acrylic) background.

XAML Islands allows Fluent Design to be implemented in Win32 applications:

> With this process, any Win32 App can use the newest UWP controls and adopt the Fluent Design System, regardless of your app model.

[Source](https://blogs.windows.com/windowsdeveloper/2018/11/02/xaml-islands-a-deep-dive-part-1/)

**Comment by c16u** [comment]
@ArcadeRenegade, @mashed-potatoes, @dknedlik, @campbeb, @KawaiiPotato: Will somebody please evaluate my request? Thanks.

**Comment by ArcadeRenegade** [comment]
Hi @c16u, unfortunately I don't have the bandwidth for updates to Sidebar Diagnostics at the moment but if someone wants to take a hack at it and make a pull request I'm all for it.

**Comment by c16u** [comment]
Has anyone gotten to this yet?

**Comment by mashed-potatoes** [comment]
@c16u You can use this project: [FluentWPF](https://github.com/sourcechord/FluentWPF).

**Comment by Crumdidlyumshis** [comment]
Bump, would love this feature!
