### ISSUE TITLE
Native version request for Linux

### ISSUE THREAD

**Issue by maravento** [ArcadeRenegade/SidebarDiagnostics#255]
Excellent project It would be much better if you could have a native version for Linux (.deb, AppImage, Snap, Flatpak, etc)
Thank you

**Comment by ArcadeRenegade** [comment]
Thank you. Unfortunately, I don't have the time for writing the entire app for Linux but if .NET Core WPF ever supports Linux OS it will be an easy port.

**Comment by javashin** [comment]
@ArcadeRenegade  and with this > https://github.com/AvaloniaUI/Avalonia
