### ISSUE TITLE
Conflict with fences

### ISSUE THREAD

**Issue by Rimpel** [ArcadeRenegade/SidebarDiagnostics#256]
**1. Your Operating System**
Windows 10 with 4 different resolutions monitors.
**2. App Version**
3.5.3
**3. Any Relevant Settings**
did not manage to configure anything
**4. Steps to Reproduce**
Just install on the system with Fences (in my case version 3) already installed.

After the progam loaded objects on screen started to blink, fences disappeared for a while and then tried to appear and disappear again in cycle. All system responsiveness has become very slow, even mouse pointer barely moved. Finally explorer almost freezed and I had to kill SidebarDiagnostics process.

**Comment by pawelkuras** [comment]
I think I am having a similar issue.

Everything seems okay, until I lock my screen and upon unlocking it.  The Sidebar Diagnostics gui appears to resize itself, and the other app next to it takes up the space made available by Sidebar Diagnostics.  Then Sidebar Diagnostics takes up that space again, and pushes the other app back out.  This happens over and over until the machine becomes pretty unresponsive.

I have 2 solutions:
1. move all apps adjacent to Sidebar Diagnostics, away from its edge to let Sidebar Diagnostics lock in
2. kill Sidebar Diagnostics
