### ISSUE TITLE
No reading from Navi

### ISSUE THREAD

**Issue by TrickyDee42** [ArcadeRenegade/SidebarDiagnostics#260]
Win 10 64 latest release

MSI Navi RX 5700 XT evoke

App Version 3.5.3

Readings from the graphic card are non existent. This does seem to be common from all gadgets that I have tried since getting new card.

Any plans to update to look at this issue, as the sidebar look awesome.

**Comment by LordSushiPhoenix** [comment]
I'm having the same issue, it's likely due to [this issue](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/134) with LibreHardwareMonitor.

**Comment by binary100100** [comment]
[LibreHardwareMonitor.Report.txt](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/3748037/LibreHardwareMonitor.Report.txt)

**Comment by TrickyDee42** [comment]
Noob question I'm afraid.

The libre hardware monitor has been updated to now read Navi (RX5700XT) will this install pick up the latest version automatically?

**Comment by ArcadeRenegade** [comment]
Cool. I just need to do a new build and release and your program will update automatically after.

**Comment by TrickyDee42** [comment]
Actually, it may be worth checking what is happening over there first, I'm not quite sure how this all works, and I'm not sure the main version has it yet.

**Comment by ArcadeRenegade** [comment]
Looks like someone fixed it only in their own fork. I'll have to wait until the pull it into the master branch. Then I'll do a new build and release.

**Comment by TrickyDee42** [comment]
The Navi (RX 5770 XT) functions, have now been merged to the main branch.

Build and release away!!

**Comment by JPetovello** [comment]
> 
> 
> The Navi (RX 5770 XT) functions, have now been merged to the main branch.
> 
> Build and release away!!
> 
> @ArcadeRenegade

Yes Please!

**Comment by ArcadeRenegade** [comment]
@TrickyDee42  @JPetovello  could you please try this debug build and let me know if it fixes your issue?

Also I've encountered a bug with this new build where if you change the settings then the app crashes. Does that happen for you?

[Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/3980863/Debug.zip)

**Comment by fishbiscuit13** [comment]
Sorry to jump in but it works fine for me on my 5700, and I'm not getting any crashes changing settings.
![Annotation 2019-12-18 213752](https://user-images.githubusercontent.com/5496516/71147765-aa30c280-21de-11ea-9421-03862d878efa.png)

**Comment by TrickyDee42** [comment]
> @TrickyDee42 @JPetovello could you please try this debug build and let me know if it fixes your issue?
> 
> Also I've encountered a bug with this new build where if you change the settings then the app crashes. Does that happen for you?
> 
> [Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/3980863/Debug.zip)

As soon as I get home from work this evening, i'll install and test.

Thanks for your efforts.

**Comment by JPetovello** [comment]
> 
> 
> @TrickyDee42 @JPetovello could you please try this debug build and let me know if it fixes your issue?
> 
> Also I've encountered a bug with this new build where if you change the settings then the app crashes. Does that happen for you?
> 
> [Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/3980863/Debug.zip)

Just tried it a few minutes ago, and everything looks to be working!

**Comment by TrickyDee42** [comment]
Not sure what's happening on mine then.
The GPU core reading seems to be correct, but jumps around all over the place, a lot more than any other monitor is showing.
The VMem Core is not showing the correct clock1200 when it should be 1750.
It also seems to hog system on machine, causing screen flicker then a black screen that then recovers back to normal.

**Comment by fishbiscuit13** [comment]
@TrickyDee42 What version of the drivers do you have? If you’re on 19.12.2 from last week, you should update to yesterday’s version, it’s much more stable and fixed a lot of black screen issues.

**Comment by TrickyDee42** [comment]
> 
> 
> @TrickyDee42 What version of the drivers do you have? If you’re on 19.12.2 from last week, you should update to yesterday’s version, it’s much more stable and fixed a lot of black screen issues.

I'm running the new one.
When I launch the Debug version of the sidebar, It launches fine, but mouse pointer is spinning blue wheel, and cant select anything, then flash black screen and back to normal.
It's looks like explorer is crashing then recovering.
Is there any output file I can upload to help.
I have an MSI RX5700XT evoke OC

**Comment by TrickyDee42** [comment]
Have checked with Libre Hardware Monitor.

The VRam Clock is reading the GPU SoC value rather than the GPU Memory value.

**Comment by TrickyDee42** [comment]
> 
> 
> Sorry to jump in but it works fine for me on my 5700, and I'm not getting any crashes changing settings.
> ![Annotation 2019-12-18 214019](https://user-images.githubusercontent.com/5496516/71147894-07c50f00-21df-11ea-9f4f-9952d593f28f.png)

Are you getting correct value for VRAM? 1725 on Boost I believe.

**Comment by TrickyDee42** [comment]
> @TrickyDee42 @JPetovello could you please try this debug build and let me know if it fixes your issue?
> 
> Also I've encountered a bug with this new build where if you change the settings then the app crashes. Does that happen for you?
> 
> [Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/3980863/Debug.zip)

I'm wondering if the problems I'm seeing when I launch, and make changes to settings are what you are describing as a crash, or maybe with your system it is causing a full crash.
Clearly something is not working right with this debug version.
@ArcadeRenegade

**Comment by ArcadeRenegade** [comment]
The bug I found was that if you click ok or apply to change settings then the application crashes. What issues are you experiencing?

**Comment by TrickyDee42** [comment]
> The bug I found was that if you click ok or apply to change settings then the application crashes. What issues are you experiencing?

When I first launch the prog, it launches, but my system becomes unresponsive until weirdly I right click on the taskbar, I then get black screen, which then recovers, the explorer window I had open to run exe has closed and system works fine. There is a lot of CPU workload, though I have not established yet if that is connected, or coincidence.
If you see my earlier post, VMem core is reading from wrong value, and the GPU reading is jumping around, which is not seen in a version of libre running at the same time.

**Comment by fishbiscuit13** [comment]
@TrickyDee42 I have mine OC'd to 2000 MHz, it seems to report accurately. Shows around 1960-70 at full load.

**Comment by TrickyDee42** [comment]
> @TrickyDee42 I have mine OC'd to 2000 MHz, it seems to report accurately. Shows around 1940-50 at full load, and matches HWiNFO64 and GPU-Z exactly.

Is that the GPU core, or the Vmem core. As it is the VMem core that is reported incorrectly.
See my earlier post that shows reading from sidebar and libre side by side.

**Comment by fishbiscuit13** [comment]
@TrickyDee42 Yeah you're right, it's reporting SoC clock instead of VRAM.

**Comment by JPetovello** [comment]
Seems everything isn't fine after all, as I've had similar issues as @TrickyDee42

**Comment by TrickyDee42** [comment]
Any update on these issues?

**Comment by ArcadeRenegade** [comment]
Not much I can do unfortunately. If LibreHardwareMonitor is reporting incorrect information that is their library. I can't troubleshoot the crashing because I can't recreate.

**Comment by TrickyDee42** [comment]
> Have checked with Libre Hardware Monitor.
> 
> The VRam Clock is reading the GPU SoC value rather than the GPU Memory value.
> 
> ![Annotation 2019-12-19 211003](https://user-images.githubusercontent.com/38285238/71209649-001b6e00-22a4-11ea-93b3-cb1f068b19b7.png)

Libre is reporting the correct info, but sidebar seems to read wrong value, see image.

**Comment by TrickyDee42** [comment]
Any movement on this, VRAM needs to display GPU Memory value, not GPU SoC value.

@ArcadeRenegade

**Comment by TrickyDee42** [comment]
It seems that once it is running, it runs fine.

Still reading the wrong value from Libre, but if this could be fixed, then definitely usable.

**Comment by JPetovello** [comment]
Could really use a more recent build

**Comment by zstoichev** [comment]
Second that we need new build w/ newer LHM

**Comment by ArcadeRenegade** [comment]
i'll do a new build and release this weekend

**Comment by TrickyDee42** [comment]
> i'll do a new build and release this weekend

Did this not happen. Is the new build going to correct the issue with reporting the incorrect value

![image](https://user-images.githubusercontent.com/38285238/77920908-f936cb00-7296-11ea-8b57-1bce968a6225.png)

**Comment by ArcadeRenegade** [comment]
Hey everyone I released version 3.5.4.

I broke the auto updater in the last version so you will probably have to uninstall and install 3.5.4.
Sorry about that.

The auto updater should work from now on hopefully.

**Comment by TrickyDee42** [comment]
@ArcadeRenegade 
Ryan, the Navi reading is still pulling in the incorrect value, the correct value is in hardware monitor
The sidebar is showing GPU SoC as GPU Memory.

![image](https://user-images.githubusercontent.com/38285238/78012984-b419a400-733d-11ea-9d0e-2defa456768f.png)

Can this be fixed.

R.

**Comment by ArcadeRenegade** [comment]
[Release.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/4408293/Release.zip)

Sure. Could you please try it with this build and let me know if that works as intended?

**Comment by TrickyDee42** [comment]
Perfect!!

**Comment by ArcadeRenegade** [comment]
Cool thanks I'll add it to the next release

**Comment by ArcadeRenegade** [comment]
Released
