### ISSUE TITLE
Not showing the right CPU TEMP

### ISSUE THREAD

**Issue by OptimusPriV** [ArcadeRenegade/SidebarDiagnostics#261]
**Windows 10 **

**Version  3.5.3**

First of all Thank yo keep updating this software.

I got a Ryzen 5 1600x and it seem the ad roughly 15 Celsius on the TEMP Core on the sidebar. I try many other software and i idle like 32c and with your apps i'm a ~49c

Hope you can fix it !

**Comment by dranivil** [comment]
Same problem here with Ryzen 7 2700X

**Comment by dunestorm333** [comment]
Same here, the monitoring software doesn't respect Ryzen's 10C temperature offset.

**Comment by ArcadeRenegade** [comment]
Could you please make a ticket with LibreHardwareMonitor?

**Comment by dunestorm333** [comment]
> 
> 
> Could you please make a ticket with LibreHardwareMonitor?

Will do!

**Comment by ArcadeRenegade** [comment]
Thank you for making that ticket. We found a solution.

Attached is a DEBUG build.
Could you please download this zip, unzip, and run SidebarDiagnostics.exe? If your Ryzen CPU temperature looks with that build, then I will do a proper release.

[Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/3934489/Debug.zip)

**Comment by dranivil** [comment]
> Thank you for making that ticket. We found a solution.
> 
> Attached is a DEBUG build.
> Could you please download this zip, unzip, and run SidebarDiagnostics.exe? If your Ryzen CPU temperature looks with that build, then I will do a proper release.
> 
> [Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/3934489/Debug.zip)

Works!! Can I provide a suggestion for the next version? 
Sound alert when the CPU or GPU (configuration separately) exceeds a set temperature.

**Comment by heelflipp900** [comment]
I just wanted to chime here and confirm that this debug version worked great for my Ryzen 2700x. Thanks!

**Comment by dunestorm333** [comment]
> 
> 
> > Thank you for making that ticket. We found a solution.
> > Attached is a DEBUG build.
> > Could you please download this zip, unzip, and run SidebarDiagnostics.exe? If your Ryzen CPU temperature looks with that build, then I will do a proper release.
> > [Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/3934489/Debug.zip)
> 
> Works!! Can I provide a suggestion for the next version?
> Sound alert when the CPU or GPU (configuration separately) exceeds a set temperature.

I would test it too if my PC wasn't toast :( I will report back once I get it back online.

**Comment by snudel** [comment]
The debug version works as well with my threadripper 1900X
the current stable version shows wrong values. 

thanks for correcting. I am looking forward to the release.

**Comment by ArcadeRenegade** [comment]
Hey everyone I released version 3.5.4.

I broke the auto updater in the last version so you will probably have to uninstall and install 3.5.4.
Sorry about that.

The auto updater should work from now on hopefully.

**Comment by sophiakaile** [comment]
To check cpu temp, i am using HWiNFO...  select temp software
https://top10pcsoftware.com/best-cpu-temperature-monitor-software/
