### ISSUE TITLE
[Feature Request] HDD/SSD temperature

### ISSUE THREAD

**Issue by HumbertoFreitas** [ArcadeRenegade/SidebarDiagnostics#262]
It would be very interesting if the program displayed the temperatures of HDD/SDD.

**Comment by Dr-Flay** [comment]
Agreed, especially in laptops where it can vary a lot.
Some basic SMART info would be useful.

**Comment by oppalla** [comment]
completely agreed

**Comment by eric418hk** [comment]
Completely agreed! Please add HDD/SSD temperature, it is very useful!
