### ISSUE TITLE
[FEATURE REQUEST] Integrate into Windows sidebar

### ISSUE THREAD

**Issue by Sp4iK** [ArcadeRenegade/SidebarDiagnostics#263]
This app is really cool and there are great feature requests here for additional info and stuff, but to be honest when I first saw the screenshot I though it was actually integrated into the notifications area of the Windows sidebar. So I though, that's clever!
That said, it may be to complicated or even not possible to do that, right? Just wanted to throw the idea. Thanks!

**Comment by sumsulk** [comment]
Wasn't Windows Sidebar discontinued a while back?

**Comment by Sp4iK** [comment]
> 
> 
> Wasn't Windows Sidebar discontinued a while back?

Ok, I didn't mean _that_ sidebar, but the notification area of Win10.

Anyway, I was also thinking of an autocollapsible bar, that appears when you leave your mouse at the edge of the screen for say 2 secs.

**Comment by mika76** [comment]
I actually thought that this would be part of the notification bar from the description. Would be awesome if it was an option.
