### ISSUE TITLE
[FEATURE REQUEST] Sort the monitoring metrics (e.g. move GPU temp to the first line)

### ISSUE THREAD

**Issue by xaliber** [ArcadeRenegade/SidebarDiagnostics#266]
Sometimes I have to scan to see my CPU temp, and then scan again to see GPU temp, because it's located on two different places (one is on second line, the other is on bottom). Not immediately noticeable.

Would be nice if we can sort which appears on which line.

**Comment by ArcadeRenegade** [comment]
You can. In the metric options, just drag the metric in the list to sort.

**Comment by xaliber** [comment]
No, that's not what I meant. I don't mean to sort the categories (CPU, GPU, Drives, etc). I want to sort the metrics (Core, VRAM, Temp, etc).

In GPU categories, for example, it always defaults to this order:

Core
VRAM
Core %
VRAM %
Temp

I want it to sort to:

Temp
VRAM
Core
VRAM %
Core %

You can't do that at the moment.

**Comment by ArcadeRenegade** [comment]
oh right, sorry I thought I implemented this already. unfortunately I'm not doing much active development on this project anymore but I will add it to the backlog.

**Comment by xaliber** [comment]
No worries. It already functions great, just a QOL visual preference. I always install this each time I get a new rig. Hope you can continue it when you have the time.

**Comment by ArcadeRenegade** [comment]
Glad you like it.
