### ISSUE TITLE
Changing volume via mouse with the taskbar hidden causes the program and taskbar to reload

### ISSUE THREAD

**Issue by wefalltomorrow** [ArcadeRenegade/SidebarDiagnostics#268]
**1. Your Operating System**
Windows 10 (LTSC - 1809)

**2. App Version**
3.5.3

**3. Any Relevant Settings**
Not too sure

**4. Steps to Reproduce**
Change volume on a mouse with multimedia keys whilst the taskbar is hidden

Additional notes: I have a triple-monitor setup, I'm not sure if that may be apart of this probel as well or not.

This is about the strangest bug I've come across in any application ever. I have a gaming mouse (Ajazz AJ52) with additional buttons on the side that I've set to change the volume. If the taskbar is hidden and I change the volume via my mouse it will cause Sidebar Diagnostics to reload as well as the taskbar seems to (it might be restarting/crashing explorer.exe?). If the taskbar is visible the issue doesn't seem to occur.

GIF of it in action (you can see when I'm changing the volume in the top left corner): https://i.imgur.com/Cb9HYLi.gif

**Comment by ArcadeRenegade** [comment]
That is super weird. I was not able to recreate it though. I turned on auto-hide taskbar, then changed the volume with my mouse, and i didn't get that issue.

**Comment by wefalltomorrow** [comment]
Was the taskbar hidden when you changed the volume? It's really odd haha

**Comment by wefalltomorrow** [comment]
Well it's just unusable for me in this state, having my screen bounce around every time I change volume is incredibly distracting. Are there any alternative softwares?
