### ISSUE TITLE
Sidebar and desktop are flashing

### ISSUE THREAD

**Issue by kingmustard** [ArcadeRenegade/SidebarDiagnostics#269]
Windows 10, Sidebar Diagnostics v3.5.3

This happens no matter which of my two displays I dock it to.

It only makes the desktop flash that the dock is on, though the dock itself always flashes.

It flashes at different rates. Sometimes once per second, sometimes around four times per second.

**Comment by CriticaI** [comment]
Reporting similar issues, difference being that all of my 3 screens have their elements of windows UI flashing. The sidebar still keeps on flashing and rendering bottom bars unusable, with the only way to bring back control being closing Sidebar and restarting explorer manually.

Went through uninstalling RTSS and disabling most of running processes.

**Comment by TrickyDee42** [comment]
I think this may be the same issue I've reported in the 'No readings from Navi' thread.

**Comment by wefalltomorrow** [comment]
Similar issues here.

**Comment by Kiksemanden** [comment]
I have the same problem

**Comment by John-O-Really** [comment]
I've been encountering the same thing, it's intermittant, but doesn't resolve without a restart. 
Triggers seem to include running a fullscreen application, heavy GPU load, or disconnecting my laptop dock. 
I'm running a laptop screen and 3 monitors, happens on all 4. 
My settings include "Reserve Space" - which seems to get caught in a loop. 
I'll try and capture it on video next time it happens
