### ISSUE TITLE
How to get back to change settings?

### ISSUE THREAD

**Issue by ElVandragon** [ArcadeRenegade/SidebarDiagnostics#27]
Hi I love your sidebar but I can't figure out how to get back in and change my hot key for the toggle. I was experimenting the feature and bound it to numPad7 and now when i type in Java when i go to press numpad7 no text comes up and the sidebar disappears. Maybe I'm being silly but how do I get back to the settings to change it?

**Comment by campbeb** [comment]
You should see an icon down in your task bar (near the clock). Right click and settings.

When you get back to the Hotkey section, click Bind and then Bind again and it will clear the hotkey.

**Comment by ElVandragon** [comment]
Thank you!!
