### ISSUE TITLE
New Version ?

### ISSUE THREAD

**Issue by Tiino-X83** [ArcadeRenegade/SidebarDiagnostics#270]
hello to you, I would like to know if an update is planned because this version is quite old and does not support the new Aerial wallpapers: /

Thank you

**Comment by zstoichev** [comment]
Same here. LibreHM has been updated to detect properly newest AMD products, but Sidebar is not.

**Comment by JPetovello** [comment]
> 
> 
> Same here. LibreHM has been updated to detect properly newest AMD products, but Sidebar is not.
> 
> @ArcadeRenegade

LibraHM isn't used any more, it is now Open Hardware Monitor

**Comment by TrickyDee42** [comment]
> > Same here. LibreHM has been updated to detect properly newest AMD products, but Sidebar is not.
> > @ArcadeRenegade
> 
> LibraHM isn't used any more, it is now Open Hardware Monitor

I think you'll find it is the other way around.

**Comment by JPetovello** [comment]
> 
> 
> > > Same here. LibreHM has been updated to detect properly newest AMD products, but Sidebar is not.
> > > @ArcadeRenegade
> > 
> > 
> > LibraHM isn't used any more, it is now Open Hardware Monitor
> 
> I think you'll find it is the other way around.

Oops. You are right.

**Comment by ArcadeRenegade** [comment]
Hey everyone I released version 3.5.4.

I broke the auto updater in the last version so you will probably have to uninstall and install 3.5.4.
Sorry about that.

The auto updater should work from now on hopefully.
