### ISSUE TITLE
Install / save settings somewhere other than AppData?

### ISSUE THREAD

**Issue by reloadz400** [ArcadeRenegade/SidebarDiagnostics#274]
**1. Your Operating System**
18363.418
**2. App Version**
3.5.3
**3. Any Relevant Settings**
Question regarding deployment in domain environment, without RoamingProfiles. 
**4. Steps to Reproduce**
I would simply like to specify where to look/pull settings.json from.  Ideally some directory other than %AppData%.  Perhaps C:\ProgramData ?

The reason being is I would like to push this out to all my workstations, but with identical settings, no matter who is logged-on.  So it's the same settings/configuration for all users, including new user profiles not yet created on each workstation.

**Comment by ArcadeRenegade** [comment]
hi reloadz, the installation & update manager I am using uses %LOCALAPPDATA% to as the installation location, unfortunately I cannot change it.

**Comment by ArcadeRenegade** [comment]
[Standalone_ProgramData.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/4424008/Standalone_ProgramData.zip)

Here is a quick standalone build I made for you that uses C:\ProgramData\SidebarDiagnostics\settings.json as the app settings location.
