### ISSUE TITLE
Doesn't show any info about Radeon RX 5700 XT

### ISSUE THREAD

**Issue by AiAe** [ArcadeRenegade/SidebarDiagnostics#276]
1. Your Operating System
Windows 10
2. App Version
3.5.3
3. Any Relevant Settings
None
4. Steps to Reproduce
None

![SidebarDiagnostics_WQmntHGmC1](https://user-images.githubusercontent.com/3695158/77787474-46812580-7068-11ea-9299-55386d3f223b.png)

**Comment by TrickyDee42** [comment]
Read here

https://github.com/ArcadeRenegade/SidebarDiagnostics/issues/260

Already discussed. But I think this project is very nearly dead unless someone else picks it up.

**Comment by AiAe** [comment]
> Read here
> 
> #260
> 
> Already discussed. But I think this project is very nearly dead unless someone else picks it up.

Thanks I did try to search for issue like this...

Will close this one because its duplicated.
