### ISSUE TITLE
Doesn't show VRAM clock for Radeon RX 480

### ISSUE THREAD

**Issue by rpsgc** [ArcadeRenegade/SidebarDiagnostics#278]
**1. Your Operating System**
Windows 10 (1909)

**2. App Version**
3.5.4

**3. Any Relevant Settings**
VRAM clock metric is enabled

**4. Steps to Reproduce**
Enable VRAM clock metric on RX 480

It was working fine in 3.5.3. Open Hardware Monitor supports (and shows) VRAM clock so it is a bug.

**Comment by ArcadeRenegade** [comment]
Could you please send a screenshot of your VRAM in Libre Hardware Monitor? Does the sensor have "memory" in the name?

**Comment by rpsgc** [comment]
It's called "GPU memory".

![sshot-2020-03-31_191942](https://user-images.githubusercontent.com/6519873/78061125-a50a1480-7384-11ea-8b9a-6126750ef1a6.png)

**Comment by ArcadeRenegade** [comment]
[Release.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/4411236/Release.zip)

Could you please see if it works with this build? Just need to unzip and run SidebarDiagnostics.exe

**Comment by rpsgc** [comment]
Yes, it works now. Thank you very much!

**Comment by ArcadeRenegade** [comment]
I'll make it part of the next release. Thanks.
