### ISSUE TITLE
Fatal error during the update

### ISSUE THREAD

**Issue by vinops** [ArcadeRenegade/SidebarDiagnostics#279]
**1. Your Operating System**

windows 10 64 bit professional (1909)

**2. App Version**

3.5.3

**3. Any Relevant Settings**

**4. Steps to Reproduce**

see screenshot to the problem, during automatic update version 3.5.4

![image](https://user-images.githubusercontent.com/16012414/78033822-2fdc1680-7367-11ea-9975-f6b435697f43.png)

**Comment by ArcadeRenegade** [comment]
Unfortunately I broke the auto updater last version but it should work from now on.
