### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by RememberMeWell** [ArcadeRenegade/SidebarDiagnostics#28]
Sometimes it will give this error message when i boot my pc and then it will give the sidebar has stopped working message.
link to error message: http://i.imgur.com/5gabUGA.png

**Comment by ArcadeRenegade** [comment]
Thanks. Does this error occur every time the program runs at startup? You are running Windows 10, correct?

**Comment by RememberMeWell** [comment]
Yes, I'm running Windows 10 Education. if i have a fresh install the error doesnt occur. After i while it will pop up every time i boot up. If i have more information on when the error starts to show, I will post it here. If you need more information i will gladly provide you that:)

**Comment by ArcadeRenegade** [comment]
Windows 10 Education edition has the virtual desktop functionality, correct?

I'll put in an issue with the repo that I use to handle virtual desktops.

**Comment by RememberMeWell** [comment]
yeah i think it has that functionality, dont know for sure tho. Not running any virtual desktops on my machine

**Comment by addrum** [comment]
I use VD's on an Eduation edition so it definitely has it.

**Comment by ArcadeRenegade** [comment]
Are you still getting this error? I haven't received a response from the dev so I'm thinking of just throwing it into a try catch.

**Comment by addrum** [comment]
Every now and again but not often.

On Tue, 23 Feb 2016, 22:22 Ryan <notifications@github.com> wrote:

> Are you still getting this error? I haven't received a response from the
> dev so I'm thinking of just throwing it into a try catch.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ArcadeRenegade/SidebarDiagnostics/issues/28#issuecomment-187942146>
> .
>
-- 
Adam

**Comment by ArcadeRenegade** [comment]
I added a try catch for this in v3.1.0 but it might have been for the wrong exception type. If it occurs again let me know.

**Comment by RememberMeWell** [comment]
it crashed again for me. http://i.imgur.com/qpqGQ7k.png

**Comment by ArcadeRenegade** [comment]
Thanks. Looks like I was catching the wrong type of exception. It will be fixed in the new version.
