### ISSUE TITLE
Displays incorrect 2nd monitor Left side

### ISSUE THREAD

**Issue by Tar-rask** [ArcadeRenegade/SidebarDiagnostics#281]
Windows 10.
App 3.5.4
Right Monitor #1 Primary. 4k resolution 175% scaling
Left Monitor #2 Secondary, 2560x1600 125% scaling

If I set the program to displaying monitor 2, Dock to the left, it will create the 'space' for it, but display nothing. I have to dock to right, then left for it to display correctly.

If I have settings, dock left screen 2, it will load correctly first time (and settings in screen one). Only with screen 2, dock left, it will not load correctly first.

Pictures of it loading first time from left, (can see how it moved the icons over).

![loadleft](https://user-images.githubusercontent.com/54519667/78078017-f0183c00-7405-11ea-892b-6282fe44b8ca.PNG)
![switch from right](https://user-images.githubusercontent.com/54519667/78078024-f1496900-7405-11ea-90df-9d7a0d981982.PNG)

**Comment by Saffsanity** [comment]
Similar issue, pinging

**Comment by Ardias3k** [comment]
I have that problem too. Monitor 1 has 4K resolution and monitor 2 1920px ... when I switch the sidebar to monitor 2 it is not displayed at all. If I close the settings, the program will open but no longer see any windows.
