### ISSUE TITLE
Cannot install new release

### ISSUE THREAD

**Issue by Nimgarthielle** [ArcadeRenegade/SidebarDiagnostics#283]
Hi, the auto-updater failed so I tried to manually install the last version but it wouldn't work. I tried to uninstall and reinstall, it failed the same way.
You will find attached the file given when fail occurs
[SquirrelSetup.log](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/4413948/SquirrelSetup.log)

**1. Your Operating System**  Windows 10

**2. App Version** 3.5.3 -> 3.5.4

**3. Any Relevant Settings** double screen with 1 vertical screen

**Comment by Nimgarthielle** [comment]
Well actually I can't install any version now XD

**Comment by ArcadeRenegade** [comment]
`2020-04-01 10:47:59> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.UnauthorizedAccessException: L'accès au chemin d'accès 'C:\Users\Cécile\AppData\Local\SidebarDiagnostics\app-3.5.3\OpenHardwareMonitorLib.sys' est refusé.`

thank you for posting the logs. could you please try restarting your PC. then uninstall. restart again. then install latest version?

**Comment by Nimgarthielle** [comment]
I had tried to restart PC but not in this order, it worked thanks for this quick answer :D
Just for you to know : I just had an error message saying it couldn't update but it installed 3.5.4 anyway :)

**Comment by ArcadeRenegade** [comment]
thx hopefully auto updater still works
