### ISSUE TITLE
Make the start menu shortcut available for all users

### ISSUE THREAD

**Issue by xmha97** [ArcadeRenegade/SidebarDiagnostics#285]
**1. Your Operating System**
Microsoft Windows [Version 10.0.18363.752]
**2. App Version**
Sidebar Diagnostics [Version 3.5.5.0]
**3. Any Relevant Settings**

**4. Steps to Reproduce**

Everything installer creating a shortcut to:
"%AppData%\Microsoft\Windows\Start Menu\Programs\Everything\Search Everything.lnk"
![image](https://user-images.githubusercontent.com/23485114/78307643-9b86d500-755b-11ea-9e3a-ccec7199ace8.png)
And other users can't access to Everything app.
I have to copy the shortcuts to another user, manually:
Please make the start menu shortcut available for all users.
You should change on Everything installer to create the shortcut for all users:
"%ProgramData%\Microsoft\Windows\Start Menu\Programs\Everything\Search Everything.lnk"
Thanks

**Comment by ArcadeRenegade** [comment]
i don't have any control over the installer unfortunately. it's all build into the installation/update manager i use.
