### ISSUE TITLE
WiFi signal strength

### ISSUE THREAD

**Issue by TrickyDee42** [ArcadeRenegade/SidebarDiagnostics#286]
Not a bug, a request.

Any chance of adding WiFi signal strength to the available options for the WiFi?

Or is this not possible.

Cheers for all your work.

R

**Comment by TrickyDee42** [comment]
Not sure if this is possible, as that info does not seem to be reported by hardware monitor.

Does the sidebar have to pull all its info from hardware monitor?

**Comment by ArcadeRenegade** [comment]
Sorry, not taking feature requests at this time.
