### ISSUE TITLE
Fan speed not working

### ISSUE THREAD

**Issue by TheTrueBumba** [ArcadeRenegade/SidebarDiagnostics#287]
**1. Your Operating System**

Windos 10

**2. App Version**

3.5.5

**3. Any Relevant Settings**

Asrock Z97 Killer with i7 4790K. Fan speed still showing in Libre Hardware Monitor (Fork from OpenHardwareMonitor)

**4. Steps to Reproduce**

Run in a motherboard with chipset Intel Z97.

I am a average C# developer. May I contribute with the code?

**Comment by TheTrueBumba** [comment]
Hmmm... Checked the motherboard to be sure that I am using the right fan controller and checked the bios. The bios show the controler as "CPU Fan Speed", but LibreHardwareMonitor show as "Fan #2". Maybe a issue with libre. Maybe we need to detect the name of "Fan #2 sensor" and include in the sidebar but without broking another users. How about a .ini file with a sensors list? I will check your code because your project is awesome and very lightweight. Tnxs in advance!
![sidebar](https://user-images.githubusercontent.com/1182236/78472503-b39f5580-770f-11ea-9ae0-88b4f550ca2d.JPG)

**Comment by m33ts4k0z** [comment]
The problem is that the fan speed and fan control are located under a different tab than the CPU. If you look at the code and more specifically in the file Monitoring.cs, you will see that its looking for string containing "CPU" but no such strings exist because all fans are located under the motherboard. Should be fairly easy to fix though.

**Comment by TheTrueBumba** [comment]
Yes. And my new sensor, IS8655E is not detected in both sidebar and librehardwaremonitor. I will help to resolve the issue there and comeback here again.
I will check the code. Thanks in advance.
How we can resolve it? Maybe a setting pointing the correct cpu fan sensor?

**Comment by m33ts4k0z** [comment]
Sorry for the late answer. You could try to recompile the program after editing the Monitoring.cs to look for strings containing the motherboard in order to get some fan speeds. Then you could play around with the correct ones. I believe Fan #2 is always the CPU fan but I'm not sure. I currently have no time to play with it myself.

**Comment by TheTrueBumba** [comment]
And sorry my late feedback. In librehardwaremonitor I helped the developer with a bug with my motherboard. So now I can monitor my fan using the libre widget.
So, I can try to make a push to your sidebar with a great change: every sensor have a pattern. But the CPU Fan is unique on every motherboard brand. If we create a parameter to say what CPU Fan show?
We can do it in two ways:
1 - A .ini file with the name of the sensor. So hardcore users can set the sensor´s name and show on the screen. Its the easy way. Or:
2 - Develop a way to list the fan sensors in sidedbar´s interface and check the CPU Fan sensor.
I took a look in your code. Very simple to understand. My unique problem is WPF: I *never* developed with WPF (I am skilled in MCV).
But I can try and send a push to you. Your product is better than paid ones and deserve more contribution from the community.
And excuse my english. Is not my native language. But we can talk in C# ;)

**Comment by sneville83** [comment]
I am having the same issue with my Fan Speed not showing up. I ran librehardwaremonitor and it is registering the speed of all fans connected to my motherboard, but when I enable them for the sidebar, they do not show up.

I understand that you might be working on it. I wanted to see if this is the case.

**Comment by oppalla** [comment]
my fan usage and voltage also don't work.
asus AZ97M-Plus/BR and i74790k
