### ISSUE TITLE
Sidebar constantly opening and closing (flicker) for minutes

### ISSUE THREAD

**Issue by TheBenBerman** [ArcadeRenegade/SidebarDiagnostics#289]
**1. Your Operating System**
Windows 10
**2. App Version**
3.5.5
**3. Any Relevant Settings**
Default. Changing polling interval does not effect flicker rate 
**4. Steps to Reproduce**
Anytime I login or screens wake up (from sleep, screen off, restart, etc)
**5. Video**
https://youtu.be/wzjKX8lsucE

I've been having this issue for years but I feel like it's much worse now to the point where I'm closing the sidebar because it gets so annoying.
Anytime I login the sidebar flickers open and closed as shown in the video. If I have an application in full screen on the same screen as the sidebar the app flickers too (also shown in video)
This always used to happen but it would blink maybe a few times before it stayed put so it wasn't a big deal. Now it blinks for minutes before it decides to stop and becomes very distracting when I try to use my PC.

Setup: 4x (3+1) 1440p monitors, but also happened when I was only using dual and later triple monitors before I got the 4th 

Please help this is the best app there is for this sort of thing :(

**Comment by ArcadeRenegade** [comment]
#228

**Comment by ArcadeRenegade** [comment]
i've been trying to fix it but i haven't been able to reproduce
