### ISSUE TITLE
Show all Cores

### ISSUE THREAD

**Issue by Valansch** [ArcadeRenegade/SidebarDiagnostics#29]
Hey, i don't know if this is a bug, a missing feature, or something that was done because of reasons i'm not aware of but: The diagnostic only shows 4 cores, instead of 8. So it seams it only shows logical cores:

![image](http://puu.sh/mZhWN/88cd433b68.jpg)

Is this working as intended?

**Comment by ArcadeRenegade** [comment]
Open Hardware Monitor monitors physical hardware. So it only monitors the i7s physical cores, not logical cores.

**Comment by ArcadeRenegade** [comment]
To clarify, I'm using open hardware monitor for data and this is a behavior of their library that I cannot change.

**Comment by Valansch** [comment]
Thanks for the answer, that's what i thought.
