### ISSUE TITLE
[Enhancement] SMART info for drives

### ISSUE THREAD

**Issue by Dr-Flay** [ArcadeRenegade/SidebarDiagnostics#291]
Could you please add basic SMART info for the health rating (and drive temp as requested by another user).
Health rating can be a % so would not take much space.

**Comment by elijahpost** [comment]
Would like to second this feature request. I have 8 drives whose health I'd like to get an at-a-glance view of. Thanks so much!

**Comment by ArcadeRenegade** [comment]
Sorry, not taking feature requests at this time.
