### ISSUE TITLE
LibreHardwareMonitor is broken for Ryzen again

### ISSUE THREAD

**Issue by shadeyg56** [ArcadeRenegade/SidebarDiagnostics#292]
A few days ago my sidebar stopped showing clock speed, the correct voltage, or temperature. Restarting does nothing. Here's a picture of it 
![image](https://user-images.githubusercontent.com/31134255/81204873-7daff400-8f8f-11ea-94fa-0a63d97c2660.png)

**1. Your Operating System**
Windows 10 1909
**2. App Version**
3.5.5
**3. Any Relevant Settings**

**4. Steps to Reproduce**
Just run sidebar. May only affect Ryzen but could affect Intel too, but somebody else would have to confirm this.

**Comment by ArcadeRenegade** [comment]
Do you have the game Valorant installed?

**Comment by shadeyg56** [comment]
Yes, I do

**Comment by ArcadeRenegade** [comment]
Vanguard is blocking it. You'll have to disable Vanguard.

**Comment by Scunkaneli** [comment]
Is there any way to make SidebarDiagnostics be able to read the values while Vanguard is running? HWiNFO for example has no problems showing them while Vanguard is active.

**Comment by ArcadeRenegade** [comment]
It's not something I have control over as they are blocking LibreHardwareMonitor dll

**Comment by ArcadeRenegade** [comment]
Probably because it's unsigned code and I can't afford a code signing certificate

**Comment by Scunkaneli** [comment]
Oh okay that's unfortunate. Thank you

**Comment by hirschmann** [comment]
It should work again with the latest version of Vanguard: https://twitter.com/PlayVALORANT/status/1258493180510519296

**Comment by ArcadeRenegade** [comment]
Yeah I noticed that. Thankfully, Riot came to their senses.

**Comment by Scunkaneli** [comment]
Thanks! I can confirm that it works again on my machine.

**Comment by U3b3** [comment]
![image](https://user-images.githubusercontent.com/68308468/168280204-1df31b45-b730-4657-bb34-68d5b758a573.png)

Blocked again i think , i'm using latest Version 3.6.2

**Comment by ArcadeRenegade** [comment]
That's because of Riot Vanguard anti-cheat. It's installed with the game Valorant.

**Comment by ArcadeRenegade** [comment]
My bad I didn't read the context of the old thread.
