### ISSUE TITLE
[TRANSLATE] TR Language Support

### ISSUE THREAD

**Issue by Taiizor** [ArcadeRenegade/SidebarDiagnostics#296]
I translate for Turkish language support.
Please, I would be glad if you add it.

[Resources.tr.resx.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/4703739/Resources.tr.resx.zip)

**Comment by ArcadeRenegade** [comment]
Hi @Taiizor  thank you for this but could you please do a pull request instead? it would make things easier. thanks

**Comment by Taiizor** [comment]
https://github.com/ArcadeRenegade/SidebarDiagnostics/pull/299
