### ISSUE TITLE
More granular configuration. Limit number of cores, which drives/network connections are shown?

### ISSUE THREAD

**Issue by MostHated** [ArcadeRenegade/SidebarDiagnostics#297]
**1. Your Operating System**
Win 10
**2. App Version**
3.5.5 (I don't see an "About" or "Info" window in app to see it's version info?)
**3. Any Relevant Settings**
Mostly default, minus UI scale lowered a tad
**4. Steps to Reproduce**
I am just wondering if it's possible to add the ability to limit the number of cores shown, perhaps show just an average CPU usage or something? Simiar to how you can select them in the graph view.

 I know it's a silly thing to complain about, but I have too many cores to see much other info. I see that I can scroll down, but it would be nice to fit as much as I can without completely removing an entire section. Same goes for Hard drives, it would be nice if I could select which drives/connections I care to see, as I have scratch/cache drives and such which I don't need to see on there, as well as things like an Xbox wireless adapter.  

![](https://i.imgur.com/sczNgcC.png)

**Comment by ArcadeRenegade** [comment]
@MostHated you can turn off displaying all core clocks in the settings.

![image](https://user-images.githubusercontent.com/13874898/83698691-f0c08080-a5b6-11ea-9269-d3c40fd8ab2f.png)

as well, you can turn off monitoring for certain network devices or drives if you'd like

![image](https://user-images.githubusercontent.com/13874898/83698718-02098d00-a5b7-11ea-8404-59cce64a5dc2.png)
