### ISSUE TITLE
No CPU Clock, Temperature, or Voltage Usage displayed

### ISSUE THREAD

**Issue by xNboydx** [ArcadeRenegade/SidebarDiagnostics#298]
**1. Your Operating System**
Windows 10 pro 1909 
**2. App Version**
3.5.5
**3. Any Relevant Settings**

**4. Steps to Reproduce**

I just built my new computer with an i9-10900k and the program wont display the Clock, Temperature, or Voltage Usage. It only displays the Load and Core Load. Is there something i need to do or is it an issue with the program?
Thanks!

Picture as proof 
https://imgur.com/a/Pg2ZueS

**Comment by ArcadeRenegade** [comment]
Is this the new Intel CPU? LibreHardwareMonitor probably needs to be update to support it.

**Comment by xNboydx** [comment]
Yes it is does that take awhile to happen?

**Comment by hirschmann** [comment]
The latest version of LibreHardwareMonitor should already support Comet Lake-S: https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/commit/fe662558f4d421c0d7ab3113c88590c5510401fc

**Comment by xNboydx** [comment]
@hirschmann  
It does check attached image as proof 
https://imgur.com/a/7Ylv4lU

**Comment by ArcadeRenegade** [comment]
[Release.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/4726659/Release.zip)

@xNboydx  could you please try it with this build? Just need to unzip and run SidebarDiagnostics.exe

**Comment by xNboydx** [comment]
@ArcadeRenegade 

That build did work for the Temp and the clock speeds. Those are what I really wanted however I thought id let you know that voltage still doesn't display and possibly CPU fan speed but i don't have one so i couldn't say for sure. Thank you so much for the quick support that you have given! 

Attached is image as proof 
https://imgur.com/a/XO2KKAF

**Comment by ArcadeRenegade** [comment]
Thanks, I'll do a proper release sometime soon.

**Comment by ArcadeRenegade** [comment]
Also thanks again @hirschmann

**Comment by jschult** [comment]
Just wanted to confirm this is also working for the 10th generation i7-10700k.

**Comment by ArcadeRenegade** [comment]
Published in version 3.5.6
