### ISSUE TITLE
Taskbar on side of screen not handled properly

### ISSUE THREAD

**Issue by campbeb** [ArcadeRenegade/SidebarDiagnostics#3]
If the Windows taskbar is set to left or right, then the display window is too small.
Example:
![image](https://cloud.githubusercontent.com/assets/1089399/12485417/bc8b9274-c02c-11e5-8994-fb60fb3d8833.png)

This also leads to a crash.
Steps:
 * Set Windows taskbar to right side
 * Launch program with AppBar mode on and set to right side
 * Open settings and move to left side
 * Open settings again and move back to right side
 * Unhandled exception crash in             `appbarWindow.Dispatcher.BeginInvoke(DispatcherPriority.ApplicationIdle, new ResizeDelegate(DoResize), appbarWindow, rect);`
 * This is because rect is zero or negative

**Comment by ArcadeRenegade** [comment]
This should be fixed with version 1.2. Could you try it?

**Comment by campbeb** [comment]
The small window and the crash are fixed. I was able to produce one problem.
Steps:
* Set task bar to right side of screen
* Have program in AppBar mode on left side of screen
* Move task bar to left side of scren
* There is double spacing

![image](https://cloud.githubusercontent.com/assets/1089399/12512813/64e55f02-c0e8-11e5-8930-e5255c78d461.png)

This can probably be considered an edge case.

**Comment by ArcadeRenegade** [comment]
Should be fixed in v1.5 as it re-positions itself after an event that changes the screen's work area.
