### ISSUE TITLE
Customize UI Size

### ISSUE THREAD

**Issue by Valansch** [ArcadeRenegade/SidebarDiagnostics#30]
I can't quite fit everything on my 900 pixel high display so i'm suggesting: A way to change the UI size.

**Comment by ArcadeRenegade** [comment]
You can change the font size

**Comment by Valansch** [comment]
Oh, i'm sorry for the spam then. I overread that. Thanks

**Comment by ArcadeRenegade** [comment]
I also just added a "UI Scale" option in the new version
