### ISSUE TITLE
GPU name not updated after upgrade

### ISSUE THREAD

**Issue by pinoaromatico** [ArcadeRenegade/SidebarDiagnostics#302]
**1. Your Operating System**
Windows 10 Pro Version 1909 Build 18363.900

**2. App Version**
3.3.4

**3. Any Relevant Settings**
Manufacturer	NVIDIA
Model	GeForce GTX 1660 SUPER
Device ID	10DE-21C4
Revision	A2
Subvendor	MSI (1462)
Driver version	26.21.14.4614
BIOS Version	90.16.48.00.2e

**4. Steps to Reproduce**

![imagen](https://user-images.githubusercontent.com/67377775/85570902-b9ffe800-b601-11ea-8bd6-a21f78c25f0c.png)

**Comment by ArcadeRenegade** [comment]
Hi you may have to manually rename the video card in the app setting.

**Comment by pinoaromatico** [comment]
Shit bro, sorry to waste your time. Didnt know that was an option! Thanks !

**Comment by ArcadeRenegade** [comment]
No worries. It is a bug. I don't know why it didn't pick up the new hardware name.

**Comment by pinoaromatico** [comment]
cool that you replied within hours! cheers!
