### ISSUE TITLE
Reserved Space Remains after uninstall

### ISSUE THREAD

**Issue by EverYT77** [ArcadeRenegade/SidebarDiagnostics#303]
Hello! I uninstalled the program because it had an error but the reserved space remained. Any one can help?

**Comment by Taiizor** [comment]
In some cases, bugs can occur in the reserved area.
The problem will disappear when you restart your computer.
If you install the application again and close it before uninstalling this time, the problem will be resolved.

**Comment by EverYT77** [comment]
> In some cases, bugs can occur in the reserved space.
> The problem will disappear when you restart your computer.
> If you install the application again and close it before uninstalling this time, the problem will be resolved.

Thanks for the reply! I just started my computer and i noticed that it has disappeared. So i guess this issue was a waste of time :)
