### ISSUE TITLE
May i re-translate Italian versio please?

### ISSUE THREAD

**Issue by nemis16** [ArcadeRenegade/SidebarDiagnostics#306]
![screenshot](https://user-images.githubusercontent.com/49538614/87692628-3d89a080-c78c-11ea-8b50-5d494786866d.PNG)

As you can see in the picture, with the latest and translated italian version, words are too long.
Translation is correct but i would make it shorter, like "Lettura: XXMB/s" instead of "Velocità di Lettura: XXMB/s".
(That means respectively, "Reading", "Reading Speed"). I have to make all the Sidebar text very tiny because of this "bug" (some text remains hidden to the right).
If you send me the translations file i will update it and send it back to you, no problem, i will do it gladly.

Thank you, have a good day.

**Comment by ixuz** [comment]
Hi @nemis16 !
Absolutely! Adjust [Resources.it.resx](https://github.com/ArcadeRenegade/SidebarDiagnostics/blob/master/SidebarDiagnostics/Properties/Resources.it.resx) file and submit your changes as a new Pull-Request.

**Comment by nemis16** [comment]
Sorry, i am unable to make a new pull-request. I dont know GitHub so well.
[Resources.it.resx.txt](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/4937693/Resources.it.resx.txt)

This is the resx file, just remove the .txt extension (github doesn't support resx uploading here).
Take it from here if you don't mind, thank you.

**Comment by ixuz** [comment]
Okay I see, Thank you @nemis16 I'll adopt your adjustment soon.

**Comment by ixuz** [comment]
Suggested changes applied in https://github.com/ArcadeRenegade/SidebarDiagnostics/commit/940d1d05505c77fd016c64ecce798b28f60ac885
