### ISSUE TITLE
Color display for CPU & GPU and colors display for read & write disk activity

### ISSUE THREAD

**Issue by charly6742** [ArcadeRenegade/SidebarDiagnostics#307]
First, many thanks for creating SidebarDiagnostics

I would like to say 

is it possible to add one step color for CPU & GPU temperature ?
exemple : normal text in white and first step over 40° in orange et last step over 50° in red ?

is it possible to add colors for disk activity ?
exemple : normal text in white for no disk activity and green color for line reading activity and red color for line write activity

**Comment by ArcadeRenegade** [comment]
Sorry, not taking feature requests at this time.
