### ISSUE TITLE
Downloaded version 3.5.5 and got 3.5.6 installed

### ISSUE THREAD

**Issue by Gyrobit** [ArcadeRenegade/SidebarDiagnostics#309]
1. Windows 10 Pro 2004
2. App Version 3.5.6
3. None
4. Download version 3.5.5, looked at the properties of setup.exe it say 3.5.5, install, then look at Apps -> uninstall and I see 3.5.6

On the SidebarDiagnostics itself I can't find a version number.
I see that it has automatically updated to 3.5.6 without Kasperksy triggered that there is a Adware virus
Very strange.

Sidebar looks very good

![SidebarDiagnostics version](https://user-images.githubusercontent.com/69162171/89213819-fd1c8600-d5c5-11ea-8263-3d5271d0e086.png)
![SidebarDiagnostics App Version](https://user-images.githubusercontent.com/69162171/89214014-51276a80-d5c6-11ea-9132-fd547c7c497b.png)
![SidebarDiagnostics Auto Updated](https://user-images.githubusercontent.com/69162171/89214906-f55de100-d5c7-11ea-9fb1-e3aa380b59a0.png)

**Comment by ArcadeRenegade** [comment]
It updates itself when you run the application. You can change the setting to disable automatic updates, then uninstall the application, then install the old version.
