### ISSUE TITLE
Temperatures

### ISSUE THREAD

**Issue by ElVandragon** [ArcadeRenegade/SidebarDiagnostics#31]
Hi, I love this application. I was just  wondering if it would be possible so that we could make it so when the temperature of the CPU or GPU exceeds a user defined threshold that it will change the color of the temperature text for that component so that it is easier to see when the temperatures are getting to a dangerous level. Thanks!

**Comment by ArcadeRenegade** [comment]
This is already implemented. Go to the monitors tab and click on CPU or GPU. It will have a text box for temperature alert thresholds.

**Comment by ElVandragon** [comment]
My apologies. Thank you very much for the quick response.
