### ISSUE TITLE
Updating to latest release pukes error and wipes out installed version

### ISSUE THREAD

**Issue by japkov** [ArcadeRenegade/SidebarDiagnostics#311]
**1. Windows 10 x64 PLK freshly upgraded from 1903 to 2004**

**2. 3.5.5 was working fine and it was installed from .exe**

I've tried to update installed 3.5.5 version to 3.5.6 and upon launching installer I'm getting this error:

![image](https://user-images.githubusercontent.com/69731550/90319787-a4d97280-df3b-11ea-9967-c5325f1a5fc8.png)

Log shows this: 

> 2020-08-15 21:07:41> Program: Starting Squirrel Updater: --install .
2020-08-15 21:07:41> Program: Starting install, writing to C:\Users\blankout\AppData\Local\SquirrelTemp
2020-08-15 21:07:42> Program: About to install to: C:\Users\blankout\AppData\Local\SidebarDiagnostics
2020-08-15 21:07:42> Program: Install path C:\Users\blankout\AppData\Local\SidebarDiagnostics already exists, burning it to the ground
2020-08-15 21:07:42> IEnableLogger: Failed to remove existing directory on full install, is the app still running???: System.UnauthorizedAccessException: Odmowa dostepu do sciezki „C:\Users\blankout\AppData\Local\SidebarDiagnostics\app-3.5.5\LibreHardwareMonitorLib.sys”.
   w System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   w System.IO.File.InternalDelete(String path, Boolean checkHost)
   w System.IO.File.Delete(String path)
   w Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   w Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   w System.Threading.Tasks.Task.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Squirrel.Utility.<>c.<<DeleteDirectory>b__19_1>d.MoveNext()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
2020-08-15 21:07:42> Unhandled exception: System.AggregateException: Wystapil przynajmniej jeden blad. ---> System.UnauthorizedAccessException: Odmowa dostepu do sciezki „C:\Users\blankout\AppData\Local\SidebarDiagnostics\app-3.5.5\LibreHardwareMonitorLib.sys”.
   w System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   w System.IO.File.InternalDelete(String path, Boolean checkHost)
   w System.IO.File.Delete(String path)
   w Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   w Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   w System.Threading.Tasks.Task.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Squirrel.Utility.<>c.<<DeleteDirectory>b__19_1>d.MoveNext()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- Koniec sladu stosu wyjatków wewnetrznych ---
   w System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   w System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   w System.Threading.Tasks.Task.Wait()
   w Squirrel.Update.Program.executeCommandLine(String[] args)
   w Squirrel.Update.Program.main(String[] args)
---> (Wyjatek wewnetrzny #0) System.UnauthorizedAccessException: Odmowa dostepu do sciezki „C:\Users\blankout\AppData\Local\SidebarDiagnostics\app-3.5.5\LibreHardwareMonitorLib.sys”.
   w System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   w System.IO.File.InternalDelete(String path, Boolean checkHost)
   w System.IO.File.Delete(String path)
   w Squirrel.Utility.<>c.<DeleteDirectory>b__19_0(String file)
   w Squirrel.Utility.<>c__DisplayClass12_1`1.<ForEachAsync>b__1()
   w System.Threading.Tasks.Task.InnerInvoke()
   w System.Threading.Tasks.Task.Execute()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Squirrel.Utility.<>c.<<DeleteDirectory>b__19_1>d.MoveNext()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Squirrel.Utility.<DeleteDirectory>d__19.MoveNext()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w Squirrel.Utility.<LogIfThrows>d__42.MoveNext()
--- Koniec sladu stosu z poprzedniej lokalizacji, w której wystapil wyjatek ---
   w System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   w System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   w Squirrel.Update.Program.<Install>d__4.MoveNext()<---

Microsoft Installer package doesn't even start but I suspect this might be some issue with post-upgrade to 2004. 

I hope you have some idea what happened here cause I really like your application and I'd like to use it

**Comment by ArcadeRenegade** [comment]
Try restarting your pc first

**Comment by japkov** [comment]
Just did and same error appears for .exe and .msi just stops doing after the initial configuration

**Comment by japkov** [comment]
I'll stick to Standalone version as it seems to be working without any issues.
