### ISSUE TITLE
Bitdefender Antivirus flags as a "Trojan.GenericKD.34223104"

### ISSUE THREAD

**Issue by Tulosi** [ArcadeRenegade/SidebarDiagnostics#313]
1. Windows 10, whatever the latest patch is

2. Whatever the latest version available at this time is

3. N/A

4. Attempt to download and install .exe while bitdefender is running

**Comment by ixuz** [comment]
This issue (BitDefender) is already reported in issue https://github.com/ArcadeRenegade/SidebarDiagnostics/issues/308
