### ISSUE TITLE
Feature Request - Custom Text/Notes

### ISSUE THREAD

**Issue by whyyn0tt** [ArcadeRenegade/SidebarDiagnostics#319]
1. Win 10 2004
2. 3.5.6

Interested in adding the ability to add custom text or notes, preferably at the bottom, below network.

Because of my resolution and size that I like to keep Sidebar, I have a large blank gap at the bottom of the monitor. Currently, I fill this blank space with a Stick Note widget, but it would be great to have this same functionality within Sidebar Diagnostics. Thanks for considering!

**Comment by ArcadeRenegade** [comment]
Sorry, not taking feature requests at this time.
