### ISSUE TITLE
Constant Crashing

### ISSUE THREAD

**Issue by CZonin** [ArcadeRenegade/SidebarDiagnostics#320]
**1. Your Operating System**
Windows 10 Home Version 2004

**2. App Version**
3.5.6

**3. Any Relevant Settings**
Not sure

**4. Steps to Reproduce**
Just having sidebar running, it will crash after a couple of minutes.

**Screenshots of Errors:**
![Screenshot 2020-10-07 073814](https://user-images.githubusercontent.com/67965669/95328418-89238600-0873-11eb-90fc-643a8d2bb1f5.png)
![Screenshot 2020-10-07 073833](https://user-images.githubusercontent.com/67965669/95328420-89238600-0873-11eb-9129-479e8d86d143.png)

**Comment by ArcadeRenegade** [comment]
Seems like you may not be running the program as administrator. Or Performance Monitor service is not running.

**Comment by CZonin** [comment]
> Seems like you may not be running the program as administrator. Or Performance Monitor service is not running.

Didn't realize it had to run as admin. Been running it for like an hour now without it crashing. Thanks!

**Comment by CZonin** [comment]
@ArcadeRenegade Just wondering if you had any suggestions on this. Same issue occurs with the latest version.
