### ISSUE TITLE
Feature Request - Hide/Show when left-clicking on tray icon

### ISSUE THREAD

**Issue by mika76** [ArcadeRenegade/SidebarDiagnostics#321]
**1. Your Operating System**
Windows 10 Prof

**2. App Version**
I don't know - there is no version display anywhere... (maybe there should be an about screen in the settings screen?) but I downloaded a couple of days ago...

**Info**

How about changing visibility when left clicking on the tray icon? Currently the show/hide is hidden in a 3 click menu (tray icon click/visibility click/ show/hide click) and that is not really user friendly. You could also make it the default tray icon menu item and a double-click would do it. Or at least put show hide toggle as an item in the root menu...

**Comment by ArcadeRenegade** [comment]
I think that would be unexpected behavior for most users. You can instead bind a hotkey for show/hide in the settings.
