### ISSUE TITLE
High consumption of RAM

### ISSUE THREAD

**Issue by oppalla** [ArcadeRenegade/SidebarDiagnostics#322]
1. Windows 10 2004 19041.572

2. 3.5.6.0

3. On Task Manager it shows 54mb

4. Using Process Explorer from Sysinternals, it shows 230mb on Private Bytes. If I kill the process, aproximately 200mb are released from my RAM usage... 

I think that there is some leakage, because OpenHardwareMonitor and other similar softwares run with very low RAM usage.

**Comment by ArcadeRenegade** [comment]
Does it grow past 230MB?

**Comment by oppalla** [comment]
I didn't checked anymore.. But I'll keep an eye on it. Anyway, why the question?
Isn't 230mb too much already? :)

Thks @ArcadeRenegade

**Comment by ArcadeRenegade** [comment]
230MB in private bytes does not necessarily mean there is a memory leak. In the Sidebar Diagnostics code, everything is properly disposed of in the C# code and the garbage collector handles the rest. As long as the allocated memory isn't constantly growing while the application runs, or reloading the sidebar, or opening and closing different windows, then there shouldn't be a memory leak.
