### ISSUE TITLE
Server 2012 R2 issue

### ISSUE THREAD

**Issue by brokeDude2901** [ArcadeRenegade/SidebarDiagnostics#325]
**1. Your Operating System**
Server 2012 R2 (6.3.9600)
**2. App Version**
Latest release
**3. Any Relevant Settings**
Default (everything enabled)
**4. Steps to Reproduce**
Stop working randomly **unless I disable all my network devices!**

Is there anything to make 2012 R2 works better?

**Comment by ArcadeRenegade** [comment]
Can you please share an error message?

**Comment by brokeDude2901** [comment]
Turn out it is permission issue with Windows Server 2012 R2 by default. I has to turn off Admin Approval Mode in group policy!

**Comment by ArcadeRenegade** [comment]
hehe it's always group policy... or dns
