### ISSUE TITLE
zh_tw cannot use

### ISSUE THREAD

**Issue by huangwenen** [ArcadeRenegade/SidebarDiagnostics#327]
**1. Your Operating System**
win10 19041

**2. App Version**
3.5.6

**3. Any Relevant Settings**
 zh_tw and zh_cn are the same，cannot change language to zh_tw

**4. Steps to Reproduce**

**Comment by ArcadeRenegade** [comment]
No one has added a translation for zh_tw. Pull requests are welcome.

**Comment by huangwenen** [comment]
I found many traditional language options in the settings, and I thought that language exists...
