### ISSUE TITLE
Feature Request - Hard Drive Temperature

### ISSUE THREAD

**Issue by tomaroberts** [ArcadeRenegade/SidebarDiagnostics#329]
Hi there - just downloaded the program. It's so good, so streamlined and the installation was a breeze - love it!

Would it be possible to get the temperature of the Drives as an option? I ask because I've recently put together a SFF PC and this is suddenly something I'd love to be able to monitor...

Thanks!
Tom

**Comment by ArcadeRenegade** [comment]
Unfortunately drive temp is not available in performance monitor
