### ISSUE TITLE
App fails to run. Can't be deleted because "the file is open in System"

### ISSUE THREAD

**Issue by evanshen2010** [ArcadeRenegade/SidebarDiagnostics#33]
This issue only occurs in 2.4.5 and 2.4.6

When trying to run SD, the cursor in the explorer windows changes to the "Working In Background" cursor (pointer and the "busy" circle), but the app never starts up.

If you try to delete or overwrite SidebarDiagnostics.exe you get an error:
File In Use
The action can't be completed because the file is open in System
Close the file and try again.

Trying to run SD again does nothing different, and restarting the computer is the only way to get it in a delete-able state again.

I'm running Windows 10 64-bit. I also use a program called Clover that wraps the default Windows explorer.

**Comment by ArcadeRenegade** [comment]
Try deleting your user config file.
Go to:

C:\Users\Ryan\AppData\Local\Ryan_Knittel

Delete all folders and files there.

**Comment by evanshen2010** [comment]
Interesting, this worked for 2.4.6 but 2.4.5 and 2.4.7 still suffer from the same issue.

I uninstalled Clover and just used the regular Windows explorer but it didn't seem to change anything.

**Comment by ArcadeRenegade** [comment]
Can you see the program in task manager? It runs but nothing shows up? No tray icon? No sidebar?no error message box?

**Comment by evanshen2010** [comment]
No nothing, can't be found in the task manager either. I'm not even sure it's "running" since the mouse cursor changes to the loading background task cursor. It's like it's trying to start up but gets stuck somewhere.

**Comment by ArcadeRenegade** [comment]
That is really odd. I wish I could be of more help but I've never heard of
this before. It seems like the program isn't even starting so maybe it has
to do with the .NET framework. You could try reinstalling .NET I suppose.

**Comment by ArcadeRenegade** [comment]
If the program isn't starting up but the exe file has an exclusive lock by
"System" then I think it definitely is a .NET issue. System is the main
library of .NET.

**Comment by evanshen2010** [comment]
No worries, my computer has been having weird quirks since upgrading from 8.1. At least some versions are working for me!

I've been meaning to do a clean reinstall, if I ever get around to it I'll come back with more info on whether or not I still run into this.

**Comment by ArcadeRenegade** [comment]
I'm going to close this since it seems to be a user specific issue.
