### ISSUE TITLE
Feature Request: Drive letters on same line as Load Bar

### ISSUE THREAD

**Issue by recursivedecimal** [ArcadeRenegade/SidebarDiagnostics#331]
**1. Your Operating System** Win10-1903

**2. App Version** 3.5.6

I have 4x drives, the 4th doesn't entirely fit. Conserving a few lines of vertical space would be very helpful. I feel that there is enough empty horizontal space next to the Load Bar to not need to use an entire line for 2 characters.

**Comment by ArcadeRenegade** [comment]
If you only have the load bar metric active then that is what it does:

![image](https://user-images.githubusercontent.com/13874898/101079372-3e18ad00-355c-11eb-98f4-356ce2d1c307.png)
