### ISSUE TITLE
Please add Circle diagram for clearly view parameters

### ISSUE THREAD

**Issue by Ygarr** [ArcadeRenegade/SidebarDiagnostics#332]
**1. Your Operating System**
Win10
**2. App Version**
Last 
**4. Steps to Reproduce**
just need option to view parameters dynamic via diagram for perception of information.
Indicative sample in attach
![brave_J99IYqdl0H](https://user-images.githubusercontent.com/14309871/101227651-49c1bc00-36a1-11eb-8aaa-6e50e2df0e04.png)

**Comment by ArcadeRenegade** [comment]
Sorry not taking any new feature requests at this time.
