### ISSUE TITLE
CPU fan not showing

### ISSUE THREAD

**Issue by ahdes** [ArcadeRenegade/SidebarDiagnostics#337]
Hi my CPU fan is not showing. Any help will be useful thanks!

**2. Windows 10 Pro

**3. App Version**
3,5,7

**4. Any Relevant Settings**
![image](https://user-images.githubusercontent.com/17719508/101911410-49727500-3bfb-11eb-95c7-1f09b56ca758.png)
![image](https://user-images.githubusercontent.com/17719508/101911315-26e05c00-3bfb-11eb-976f-7766b1fc577f.png)

**5. Steps to Reproduce**

**Comment by ArcadeRenegade** [comment]
Duplicate
