### ISSUE TITLE
LibreHardwareMonitorLib.sys detected as Trojan.BitCoinMiner

### ISSUE THREAD

**Issue by zapper83** [ArcadeRenegade/SidebarDiagnostics#338]
Sidebar Diagnostics v3.5.6

Malwarebytes did an auto-scan and detected LibreHardwareMonitorLib.sys as Trojan.BitCoinMiner. I'm going to bet this is a false-positive but i would like a confirmation please.

-System Information-
OS: Windows 10 (Build 18362.1198)
CPU: x64
File System: NTFS
User: System

-Blocked Malware Details-
File: 1
Trojan.BitCoinMiner, C:\Users\xxxx\AppData\Local\SidebarDiagnostics\app-3.5.6\LibreHardwareMonitorLib.sys, Quarantined, 945, 886905, 1.0.34027, , ame, , 0C0195C48B6B8582FA6F6373032118DA, 11BD2C9F9E2397C9A16E0990E4ED2CF0679498FE0FD418A3DFDAC60B5C160EE5

**Comment by ArcadeRenegade** [comment]
Plz open a ticket on Libre Hardware Monitor repo
