### ISSUE TITLE
Latest version 3.5.7 contains virus

### ISSUE THREAD

**Issue by Leakysandwich** [ArcadeRenegade/SidebarDiagnostics#341]
Lastest version of sidebar diagnostics released on Dec 8, 2020 v3.5.7 is reported to contain a virus.
**Trojan.GenericKD.44959520**
Blocked by Bitdefender, and used VirusTotal to confim that multiple providers (>50%) has recognised it as a virus.

AutoUpdate to the latest version also caused a critical error in the app (suspected due to the virus) and auto update was disabled.

This is for Windows10 64bit, downloaded from this Github Releases tab.
Please check

**Comment by ArcadeRenegade** [comment]
It is a false positive because the program isn't signed with a code signing certificate. Unfortunately they are expensive and I don't have another recourse.
