### ISSUE TITLE
Can't open settings

### ISSUE THREAD

**Issue by dakicdev** [ArcadeRenegade/SidebarDiagnostics#342]
**1. Is this a feature request?**
No
*If yes then sorry but this project is not taking feature requests at this time.*

**2. Your Operating System**
Windows 10 Pro
**3. App Version**
3.5.7
**4. Any Relevant Settings**
Sidebar on right
Run at startup enabled
Reserve space enabled
Click through enabled
**5. Steps to Reproduce**
I ran setup.exe  from unpacked folder and changed sidebar from second to first monitor and now I can't see settings icon at sidebar. Also is it possible to hide sidebar when opening browser?

**Comment by ArcadeRenegade** [comment]
There should be an icon for the app in the notification tray. Right click it to access the settings again.
