### ISSUE TITLE
Zen 3 Temperature

### ISSUE THREAD

**Issue by Telenice** [ArcadeRenegade/SidebarDiagnostics#348]
I'm not sure why this issue is occurring, I've seen that it has been an issue in the past with Zen 1000 series and it was fixed in 3.5.4. I've tried older versions and the current version but the temperature always seems to be off by around 10C. I'm not sure how to replicate this, it just always appears higher than the actual temperature that is reported by multiple other sources such as Ryzen Master and AI Suite 3. The CPU I'm using is a Ryzen 5 5600X.

![Screenshot_1](https://user-images.githubusercontent.com/81210466/112096867-f6637300-8b96-11eb-94ba-88a0ae3b9130.png)

**Comment by mkpascal** [comment]
I have a similar issue with my Ryzen 9 5900X (Zen 3) with a similar delta (10C).

**Comment by Scorpion3de** [comment]
It´s not an issue. You can take CPU or CPU Package as your Input and they used the packaged one. Why its higher then CPU it self i dont know. But in HWinfo you see both of them.

**Comment by ArcadeRenegade** [comment]
I can only grab temps that are in LibreHardwareMonitor. I think it has CPU or CPU Package but I haven't seen it have both.
