### ISSUE TITLE
Rocket Lake Support

### ISSUE THREAD

**Issue by heyepic** [ArcadeRenegade/SidebarDiagnostics#349]
**1. Is this a feature request?**
No
**2. Your Operating System**
Win10 64-bit
**3. App Version**
Latest
**4. Any Relevant Settings**
None
**5. Steps to Reproduce**
11900K is not showing clock, temps, voltages.

**Comment by Blitzkowicz** [comment]
I'm having the same issue with the 11400f. I can see the core clocks, but not temps, voltages, or fan usage, which are displayed properly on HWMonitor.

**Comment by ArcadeRenegade** [comment]
Could you please raise an issue with LibreHardwareMonitor?

**Comment by heyepic** [comment]
Yep - will do!

**Comment by ArcadeRenegade** [comment]
once they add support for 11900k i will do a new release of sd

**Comment by heyepic** [comment]
Looks like it's been merged on their end and will be in the next release:

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/pull/421/commits/c13c4bb1697c2ae5b450d26f0773bc006f7cdf0d

**Comment by ArcadeRenegade** [comment]
[Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/6449734/Debug.zip)

Could you please see if it works with this debug build? Just need to unzip and run SidebarDiagnostics.exe.

If so I'll do a new release. Thanks.

**Comment by heyepic** [comment]
Yep - that worked. Everything showing good now.

**Comment by heyepic** [comment]
@ArcadeRenegade hey ryan, let me know when that new deploy is ready and I can help re-test for you.

**Comment by ArcadeRenegade** [comment]
So sorry I missed this. I'll release a new version tonight.

**Comment by ArcadeRenegade** [comment]
Just released v3.5.9 sorry for the delay

**Comment by heyepic** [comment]
Working great - thank you!

**Comment by heyepic** [comment]
I'm back again with another CPU upgrade lol. 12900K supports core load and overall load. Missing temperature, clock, voltage, and fan usage. Not sure if librehardware is updated or not.

**Comment by heyepic** [comment]
@ArcadeRenegade just a heads up that LibreHardwareMonitor now supports Alder Lake. If you want to have me test for you, just let me know!

**Comment by ArcadeRenegade** [comment]
Thanks I'll do a build and upload it here for testing.

**Comment by heyepic** [comment]
Figure out anything boss man?

**Comment by ArcadeRenegade** [comment]
Hey, sorry for the delay. Could you please test this debug build out for me?

[Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/7575374/Debug.zip)

**Comment by heyepic** [comment]
No worries man. Looks like that brought temp which is great! Only minor items not pulling now are voltage and fan.

**Comment by ArcadeRenegade** [comment]
Was voltage and fan working for your previous CPU? Voltage support was spotty at best. Fan usually works for most cpu and mobo.

If GPU fan stopped showing up too then that's a problem I'd have to fix first. Do you have nvidia or amd gpu?

**Comment by heyepic** [comment]
The rocket lake build (title of this topic) is a different computer - Just turned it on and you're right, no voltage or fan. Np then. If you get GPU fan working again we are good. Thanks for the help.

GPU is a Nvidia - Aorus 3080. Current released version of SBD shows the fan usage, but not this debug build.

**Comment by ArcadeRenegade** [comment]
Cool thx for looking into that. I'll try to fix the gpu fan issue then upload another test build.

**Comment by heyepic** [comment]
Yo! How's it going? Any idea when this will push?

**Comment by ArcadeRenegade** [comment]
v3.6.0 released

**Comment by ArcadeRenegade** [comment]
Crap I forgot about the GPU fan bug

**Comment by ArcadeRenegade** [comment]
Ok released v3.6.1 with the GPU fan fix
