### ISSUE TITLE
Reorganize drives and internet connections

### ISSUE THREAD

**Issue by AlexandreBT** [ArcadeRenegade/SidebarDiagnostics#35]
Hi,

You are doing a fantastic job, every time I turn on my PC, I pray that a new version is available. You improve day by day your code and that's fine!

I would rearrange my hard drives and Internet connections, is a possible evolution?

**Comment by nicandris** [comment]
Yeah I would agree that sorting the drives would be a nice addition. 
![drives sort](https://cloud.githubusercontent.com/assets/284798/12992967/cdcfc52c-d117-11e5-8bb7-794fda75ed50.png). In this example, I: should be draggable under E: 

Sorry... OCD

**Comment by ArcadeRenegade** [comment]
Yeah that's pretty ugly, sorry. I'll implement a way to order hardware.

**Comment by ArcadeRenegade** [comment]
Implemented
