### ISSUE TITLE
Issue: Chinese (Hong Kong) become Chinese (Simplified)

### ISSUE THREAD

**Issue by linklinesite** [ArcadeRenegade/SidebarDiagnostics#352]
**1. Is this a feature request?**
No
*If yes then sorry but this project is not taking feature requests at this time.*

**2. Your Operating System**
Windows 10 20H2
**3. App Version**
3.5.8
**4. Any Relevant Settings**
No
**5. Steps to Reproduce**
No

The problem:
I selected Chinese (Hong Kong) as my language in my setting, but run out Simplified Chinese Hong Kong should be using Traditional Chinese, I hope that you can change it to Traditional Chinese instead, you can use translator to make it more easy
You can use translator to make it easier

More about Chinese (Traditional) and Chinese (Simplified)
[](https://eriksen.com/language/simplified-vs-traditional-chinese/)

**Comment by ArcadeRenegade** [comment]
Pull requests are welcome
