### ISSUE TITLE
Save settings in 

### ISSUE THREAD

**Issue by yekanchi** [ArcadeRenegade/SidebarDiagnostics#356]
Allow Saving Settings in local file in release binary directory so it works as portable from one OS to another. in a USB-stick and there will be no need for initial asking for configuration.

this is common for people as network administrator willing to use the app from one system to another,

**Comment by ArcadeRenegade** [comment]
Copy this file %LOCALAPPDATA%\SidebarDiagnostics\settings.json

Please use the github search feature before making tickets.
