### ISSUE TITLE
AMD Ryzen 3700x Stats Incorrect

### ISSUE THREAD

**Issue by Wallace4444** [ArcadeRenegade/SidebarDiagnostics#357]
I've noticed today that my AMD Ryzen 7 3700x is not showing correct stats for Clock, Voltage and Temp.

Clock - NaN MHz
Voltage - 1.55V Pinned (doesn't move from this)
Temp - 0C

Load and Core Loads seem to be accurate though.

**2. Your Operating System**
Windows 10 21H1

**3. App Version**
app-3.5.9

**4. Any Relevant Settings**
Nil

**5. Steps to Reproduce**
No real steps per se. I've attempted to restart application, issue persists. Including after a reboot.

**Comment by ArcadeRenegade** [comment]
Could you please test if you get the same numbers happens in LibreHardwareMonitor?

**Comment by Wallace4444** [comment]
hey mate - I don't know what happened but overnight, it seems to have resolved itself.

Nothing changed (no windows updates or anything just PC sleep overnight) so not sure. Strange.

thanks for the quick response though!

**Comment by Zazou89** [comment]
> LibreHardwareMonitor

Same behavior with my 3700X, I think it's a LHM bug : 

![image](https://user-images.githubusercontent.com/206181/129494906-cad30717-4505-47bd-bd6a-bea0c769b9d2.png)
