### ISSUE TITLE
F-Request

### ISSUE THREAD

**Issue by Scorpion3de** [ArcadeRenegade/SidebarDiagnostics#359]
Can you implement Temp-Readings for Water_In and some Fan-Readings as well? This would be great!
In my case i use a ROG Dark Hero Mainboard an i can see all relevant Inputs in HWInfo. So it wouldnt be a pain in the as* i think ;)

Thanks a lot.

**Comment by ArcadeRenegade** [comment]
Sorry, I'm not adding new features right now.
