### ISSUE TITLE
Gap on right side of desk top if monitor is in certain place

### ISSUE THREAD

**Issue by Simber1** [ArcadeRenegade/SidebarDiagnostics#36]
My monitor setup is 3 1 2. if you have the monitor on the right of 3 [like so] (http://i.imgur.com/sqriT6E.jpg) then the icons on the right get moved slightly leaving a cap as highlighted. This happens on both windows 10 and 7. It can be got around in the meanwhile by turning off grid snapping.

**Comment by ArcadeRenegade** [comment]
That's weird. It looks like the same space as your task bar

**Comment by Simber1** [comment]
it's a good bit smaller, I think in the pic I caught the edge of my right monitor

**Comment by Simber1** [comment]
http://i.imgur.com/7WdIKZn.jpg There is a better pic showing the gap

**Comment by Simber1** [comment]
[Here](https://gfycat.com/CraftySecondBasilisk) is a gif of it moving too (because I could). It kinda upset the software too and showed the out line for some reason, most likely related.

**Comment by ArcadeRenegade** [comment]
Are you running any other applications that use the app bar functionality?

**Comment by ArcadeRenegade** [comment]
Such as display fusion.

**Comment by Simber1** [comment]
None what so ever.

**Comment by ArcadeRenegade** [comment]
So enabling grid snapping of desktop icons causes this right? I'll try to replicate.

**Comment by Simber1** [comment]
Any luck?

**Comment by ArcadeRenegade** [comment]
I haven't gotten to it yet.

**Comment by ArcadeRenegade** [comment]
So the right icons are moving slightly left when the sidebar is docked to the left of that screen, correct? 

The only thing I was able to replicate was when the sidebar was on a screen the icons shifted a bit due to the smaller work area of the screen. 

I think this is a behavior of the appbar functionality that I cannot change.

**Comment by ArcadeRenegade** [comment]
I put some icons on the right side and tested things out. And the icons do move around to weird spots but I can't change that unfortunately.

**Comment by Simber1** [comment]
No, the icons move to the left when the bar is docked on the right side of the monitor on the left of the icons. If you think of 3 monitors the bar is on the left on and the icons are on the middle one. The icons on the right of the middle screen move when the bar is on the right side of the left screen. They only move slightly to the left.

**Comment by ArcadeRenegade** [comment]
After testing this out a lot I determined this was a native interaction with the appbar library and Windows desktop. Unfortunately I cannot change it. Sorry :|
