### ISSUE TITLE
It changes the position of icon in the desktop

### ISSUE THREAD

**Issue by SuperMitic** [ArcadeRenegade/SidebarDiagnostics#361]
**1. Is this a feature request?**
No
*If yes then sorry but this project is not taking feature requests at this time.*

**2. Your Operating System**
Windows 11 build 22000.71
**3. App Version**
3.5.9
**4. Any Relevant Settings**
Nothing
**5. Steps to Reproduce**
Everytime i open the app (both with automatic startup or manually) or apply new settings it changes the position of the icon on my desktop and it leaves some blank area. 
![before](https://user-images.githubusercontent.com/87581383/126046153-6c37a1b4-bffb-48b7-b4e2-392f387b3d83.PNG)
![after](https://user-images.githubusercontent.com/87581383/126046155-313dfb49-3648-443a-871b-a7d7f9d5c3d9.PNG)

**Comment by ArcadeRenegade** [comment]
You can try turning "Auto Arrange Icons" on by right clicking your desktop. Otherwise there isn't much I can do as this is how windows behaves with the "app bar" functionality that Sidebar Diagnostics uses.
