### ISSUE TITLE
Incorrect GPU Voltage (1.2 MegaV)

### ISSUE THREAD

**Issue by mark-IV-II** [ArcadeRenegade/SidebarDiagnostics#368]
**1. Is this a feature request?**

No, this is a bug

**2. Your Operating System**

Windows 11 (beta preview, build no: 22000.168)

**3. App Version**

3.5.9 (latest available)

**4. Any Relevant Settings**

core voltage of Integrated GPU (AMD Radeon Vega 8) 

**5. Steps to Reproduce**

Open the app

**Screen shot**
![image](https://user-images.githubusercontent.com/58716239/131239969-49b3eb45-eeba-435a-aa8a-5b2047e48838.png)

**System info**

Device name	LAPTOP-P3VV3A9T
Processor	AMD Ryzen 5 3550H with Radeon Vega Mobile Gfx     2.10 GHz
Installed RAM	8.00 GB (5.94 GB usable)
System type	64-bit operating system, x64-based processor
Secondary GPU Nvidia GeForce GTX 1650 (Core voltage not shown here)

**Comment by ArcadeRenegade** [comment]
Could you please open a ticket on LibreHardwareMonitor? Thanks

**Comment by mark-IV-II** [comment]
Sure, I have opened one - [Issue#525](https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/issues/525)

Thank you

**Comment by mark-IV-II** [comment]
The issue has been fixed now. Thank you
![image](https://user-images.githubusercontent.com/58716239/150623866-264be5e5-dc4b-4321-ac5e-186b1be2e310.png)
