### ISSUE TITLE
Keep on top of desktop

### ISSUE THREAD

**Issue by heyepic** [ArcadeRenegade/SidebarDiagnostics#37]
Absolutely love this program - so first, awesome job.

I use windows key + D often to get back to desktop, but then have to re-load or double-click icon to get to show again. Any way to circumvent this? I'm not sure as I don't know what is allowed.

**Comment by ArcadeRenegade** [comment]
Thanks. 

Unfortunately the only way to prevent it from minimizing when "show desktop" occurs is to enable always on top. 

Microsoft made it so windows can in no way override show desktop behaviors except for the top most flag. I guess to prevent malicious developers from hijacking the desktop. I dunno. 

I believe you can also have it show after a show desktop by hitting your "show" hotkey. It should activate it.

**Comment by ArcadeRenegade** [comment]
Or clicking the tray icon.

**Comment by ArcadeRenegade** [comment]
Left clicking *

**Comment by ArcadeRenegade** [comment]
I think I implemented a fix for this. Could you try with the new version?

**Comment by heyepic** [comment]
Thanks dude! Works great - donation sent.

**Comment by ArcadeRenegade** [comment]
Thanks :)
