### ISSUE TITLE
No CPU temp or Frequency with intel 12700k

### ISSUE THREAD

**Issue by Khorbo** [ArcadeRenegade/SidebarDiagnostics#377]
**1. Is this a feature request?**
No
*If yes then sorry but this project is not taking feature requests at this time.*

**2. Your Operating System**
Win 10 64bit pro
**3. App Version**
3.5.9
**4. Any Relevant Settings**
No
**5. Steps to Reproduce**
Every time cpu temp and frequency is selected
![sidebar](https://user-images.githubusercontent.com/91635994/143972391-15abc54d-745d-446c-ac16-8b8e0cd09ddc.png)

**Comment by ArcadeRenegade** [comment]
Will be fixed with a new release soon please see #349
