### ISSUE TITLE
Pin Top Option for Vertical Monitors

### ISSUE THREAD

**Issue by iamjonmiller** [ArcadeRenegade/SidebarDiagnostics#378]
Big fan and longtime user. I recently reworked my setup for better ergonomics and now stack my second monitor. Horizontal real estate is at a premium in this layout whereas I have probably that top 5-15% that I could spare for SidebarDiagnostics. It would be fantastic to allow top pinning.

![IMG_20211215_183022](https://user-images.githubusercontent.com/21957977/146297132-9b2670e5-8abf-49e7-8203-a22880c23595.jpg)

**Comment by ArcadeRenegade** [comment]
This has been a constantly requested feature. The issue template says we're not taking feature requests at this time.

Unfortunately, I just don't have the time to add new features.

The last time I attempted horizontal mode, I had a hard time having the text wrap and still look good.

I am going to upgrade the app to .NET 6 and UWP soon, I might attempt horizontal mode again after.
