### ISSUE TITLE
CPU Temperature not showing for i9 12th gen

### ISSUE THREAD

**Issue by Klages** [ArcadeRenegade/SidebarDiagnostics#379]
**1. Is this a feature request?**
No
*If yes then sorry but this project is not taking feature requests at this time.*

**2. Your Operating System**
Windows 11 21H2

**3. App Version**
3.5.9

**4. Any Relevant Settings**
No

**5. Steps to Reproduce**
Select Temperature Metric when using an Intel Processor of the 12th generation.

![image](https://user-images.githubusercontent.com/3393617/146548366-acd65599-0b26-45a8-8d74-fbc67d99ebc4.png)

**Comment by wargrinder** [comment]
Not only i9, but i7 too - probably whole 12th gen Intel CPUs are affected. This should be related to LibreHardwareMonitor component, I suppose. By the way, Open Hardware Monitor has the same issue with Alder Lake CPUs - part of metrics including temperature are simply not shown.

**Comment by ArcadeRenegade** [comment]
I just need to do a new release. Sorry been busy.

**Comment by ArcadeRenegade** [comment]
v3.6.0 released
