### ISSUE TITLE
CPU Clock is in MHz instead of GHz

### ISSUE THREAD

**Issue by KevinNguyen298** [ArcadeRenegade/SidebarDiagnostics#38]
It's a pretty small issue, but the clock is in MHz instead of GHz.

**Comment by ArcadeRenegade** [comment]
I can add an option to convert them to GHz

**Comment by KevinNguyen298** [comment]
That would be perfect, thank you!

**Comment by ArcadeRenegade** [comment]
Implemented in v3.0.0
