### ISSUE TITLE
GPU Fan Bug in latest update

### ISSUE THREAD

**Issue by nubgamerz** [ArcadeRenegade/SidebarDiagnostics#380]
**1. Is this a feature request?**

No

**2. Your Operating System**

Windows 10

**3. App Version**

3.6.1

**4. Any Relevant Settings**

GPU: Nvidia Geforce RTX 2070

Fan Speed Monitoring switched on.

Rounding all decimals

**5. Steps to Reproduce**

Latest update has broken the fan speed. It now shows 1000%. Before the update it was working fine.

Switched on "Round all decimals" but made no difference.

![image](https://user-images.githubusercontent.com/26341882/146725034-ff28c96f-74c2-44b0-836d-4273e5d51e5e.png)

**Comment by ArcadeRenegade** [comment]
Can you please run the latest version of Libre Hardware Monitor and take a screenshot of all your GPU metrics for me?

https://github.com/LibreHardwareMonitor/LibreHardwareMonitor/releases

**Comment by victordk** [comment]
Same problem:

Sidebardiagnostics:
![image](https://user-images.githubusercontent.com/2484100/146736977-f03e7b07-e27d-419d-a46b-99ab43c89891.png)

Libre Hardware Monitor:
![image](https://user-images.githubusercontent.com/2484100/146737073-fcec11dc-c5f3-4d0b-924b-f7173198647e.png)

**Comment by ArcadeRenegade** [comment]
Thx looks like Sidebar is pulling the RPM by accident.

**Comment by victordk** [comment]
> Thx looks like Sidebar is pulling the RPM by accident.

And the VRAM utilization seems to be tied to something else too.

**Comment by ArcadeRenegade** [comment]
My VRAM looks okay. What are you getting?

**Comment by ArcadeRenegade** [comment]
Could you please try this Debug build for me and let me know if your fan issue is fixed?
Just need to unzip and run SidebarDiagnostics.exe

[Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/7760341/Debug.zip)

**Comment by ArcadeRenegade** [comment]
@victordk actually thanks I think it is pulling the from VRAM utilization. Can you try with this build and see if it looks accurate?

[Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/7760387/Debug.zip)

**Comment by victordk** [comment]
> @victordk actually thanks I think it is pulling the wrong VRAM utilization. Can you try with this build and see if it looks accurate?
> 
> [Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/7760387/Debug.zip)

![image](https://user-images.githubusercontent.com/2484100/147050619-8e2558ee-b87f-40e7-9ed5-095bb7aa9662.png)

The fan speed seems fine but the VRAM counter is still a bit off.

**Comment by ArcadeRenegade** [comment]
Can you post a screenshot of your metrics in Libre Hardware Monitor for me please?

**Comment by victordk** [comment]
> Can you post a screenshot of your metrics in Libre Hardware Monitor for me please?

![image](https://user-images.githubusercontent.com/2484100/147078192-8c7f9a81-7f41-4b2d-8c9a-8a5fe1183f26.png)

**Comment by daika7ana** [comment]
Using the Debug.zip provided a few posts above, here's a side-by-side:
![debug](https://user-images.githubusercontent.com/11703528/147132347-485235cd-f166-4646-8adc-cf17b119024a.jpg)

**Comment by ArcadeRenegade** [comment]
@victordk in that second debug build I uploaded, it should be pulling Load > GPU Memory Controller for VRAM %.

Is it not?

**Comment by daika7ana** [comment]
I have a feeling the Load > GPU Memory Controller reading is off since Data > GPU Memory Used / GPU Memory Total * 100 is not the same % as GPU Memory Controller %. Unless I am misinterpreting the values shown.

**Comment by victordk** [comment]
> @victordk in that second debug build I uploaded, it should be pulling Load > GPU Memory Controller for VRAM %.
> 
> Is it not?

Those two screenshots is taken with a interval of a couple of minutes - its hard to do 1to1 translations of what refers to what number.

**Comment by ArcadeRenegade** [comment]
> I have a feeling the Load > GPU Memory Controller reading is off since Data > GPU Memory Used / GPU Memory Total * 100 is not the same % as GPU Memory Controller %. Unless I am misinterpreting the values shown.

You're right. I suppose I can try to calculate the percentage using the GPU Memory Used / Total else fall back to Load > GPU Memory Controller.

**Comment by ArcadeRenegade** [comment]
Can you try this debug build? I calculate the GPU VRAM Load based off of GPU Memory Used / Total else falls back to Load > GPU Memory Controller.

[Debug.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/7771607/Debug.zip)

**Comment by daika7ana** [comment]
It seems to be showing the right percentage now.
![debug2](https://user-images.githubusercontent.com/11703528/147300039-f17def27-aa61-462c-bf5c-07bf537918ca.jpg)
2589MB / 11264MB * 100 is 22.9847% so the 23% is accurate.

On a side-note: I have a feeling Load > GPU Memory Controller shows the load of the GPU Memory Controller Unit/Chip as a % of it's total throughput. As you can see in the picture, my Max VRAM used was 2793MB but the GPU Memory Controller spiked to 61% (which would make sense since that was in a game loading screen when it was loading assets into the VRAM).

**Comment by ArcadeRenegade** [comment]
@daika7ana I think you're right about GPU Memory Controller.

Cool I'm going to release this then.

**Comment by ArcadeRenegade** [comment]
Released version 3.6.2
