### ISSUE TITLE
Error after uninstalling

### ISSUE THREAD

**Issue by not-nef** [ArcadeRenegade/SidebarDiagnostics#387]
I tried uninstalling sidebar diagnostics with the windows built-in uninstalling thing. But now when i log into my account after booting up my pc it gives me a huge error:

![image](https://user-images.githubusercontent.com/83908932/151654991-7a9aa7c2-402f-4e63-a9db-6f10f3698129.jpeg)

(Sorry that its in german) 

I am on the latest version of sidebar diagnostics and my os is Windows 11 22000.376

**Comment by ArcadeRenegade** [comment]
Try deleting the `%LOCALAPPDATA%\SidebarDiagnostics` folder. Then delete the Scheduled Task which starts the app on windows startup.

Windows 11 isn't supported at the moment.

**Comment by not-nef** [comment]
@ArcadeRenegade how do i delete that task?

**Comment by ArcadeRenegade** [comment]
Search for Task Scheduler in the start menu

**Comment by not-nef** [comment]
Nevermind, found it thanks a lot
