### ISSUE TITLE
Visibility bug after Win + D

### ISSUE THREAD

**Issue by linoliveira** [ArcadeRenegade/SidebarDiagnostics#39]
After the "show desktop" Win + D command if we click on the desktop the sidebar disappears.
Also, it would be nice if we could do Win + D and the bar would still be visible.

Thanks for the awesome work mate!

**Comment by ArcadeRenegade** [comment]
Unfortunately the only way to prevent show desktop from hiding it is by
either enabled "reserve space" or "always on top". Microsoft intentionally
made it impossible. Aside from a timer activating it every x seconds. But
that is too hacky for me.

**Comment by ArcadeRenegade** [comment]
As a workaround you can left click the tray icon, alt tab to the sidebar
window, or hit a hotkey for "show"

**Comment by linoliveira** [comment]
Thanks for the reply!
"reserve space" does not work on W8.1
The workaround I end up adopting is opening and closing the Start Menu with the Windows Key.

**Comment by ArcadeRenegade** [comment]
I think I implemented a fix for this. Could you try with the new version?

**Comment by linoliveira** [comment]
Amazing! It works flawlessly! Thank you for all the work mate!

**Comment by ArcadeRenegade** [comment]
Nice. np.
