### ISSUE TITLE
Hotkey to switch side/monitor

### ISSUE THREAD

**Issue by niesjoe** [ArcadeRenegade/SidebarDiagnostics#40]
Would it be possble to have a monitor/side switching hotkey?

While gaming I'd like to have SidebarDiagnostics on the left of my secondary screen, while I'd like it on the right side of my primary screen while browsing the web, seein as my secondary screen is pretty much my internet browsing screen.

Thanks.

**Comment by ArcadeRenegade** [comment]
Hmm. One hotkey to toggle right / left edge. And another different hotkey to cycle through monitors?

**Comment by niesjoe** [comment]
Yeah, either that or maybe even two or three presets you could switch to? Either way, a hotkey would be nice to have.

**Comment by ArcadeRenegade** [comment]
Presets are interesting but would require a lot of refactoring to get it to work and I'm worried about breaking something and resetting everyone's settings yet again.

**Comment by ArcadeRenegade** [comment]
Implemented.
