### ISSUE TITLE
Sidebar Diagnostics Portable Issue

### ISSUE THREAD

**Issue by KrisSchneider** [ArcadeRenegade/SidebarDiagnostics#400]
**1. Is this a feature request?** _No._

*If yes then sorry but this project is not taking feature requests at this time.*

**2. Your Operating System** Windows 10

**3. App Version** 3.62

**4. Any Relevant Settings** I have kept most  of my settings the same as the default settings.

**5. Steps to Reproduce**
- Download the StandAlond.zip from the Releases part of this Github Page

- After downloading it. Extract the archive's contents into a folder (I am using a custom context menu from Nilesoft Shell)
![(brave)u4i8i3_06-11-2022](https://user-images.githubusercontent.com/101912712/173178327-358ec5d5-f789-4446-bb00-0df0fda47792.jpg)

- Go into that folder, find `SidebarDiagnostics.exe`. Then click on it, a consent prompt will pop up, make sure to click the "Yes" option.
![(brave)E5Z2k7_06-11-2022](https://user-images.githubusercontent.com/101912712/173178432-b5e92e2e-9051-416c-86bb-d2d729521ef7.jpg)
![(explorer)7769h6_06-11-2022](https://user-images.githubusercontent.com/101912712/173178486-d7a9e5b8-b9a6-45bb-9602-da3f508c1fb7.jpg)

- You should get this error window on your screen:
![(Idle)-Q9I5Y6_06-10-2022](https://user-images.githubusercontent.com/101912712/173178749-02beefd5-c58e-4c66-b766-510254038bae.jpg)

Is there anything anyone can do to help me fix this issue?

**Comment by yippiekahee** [comment]
I copied the contents of standalone.zip en entered SidebarDiagnostics.exe. I get a warning that Windows stopped a potentially dangerous program. After choosing Run anyway, nothing happened. 
SidebarDiagnostics.exe is visible in the Taskmanager though. What happened?

**Comment by KrisSchneider** [comment]
> I copied the contents of standalone.zip en entered SidebarDiagnostics.exe. I get a warning that Windows stopped a potentially dangerous program. After choosing Run anyway, nothing happened.
> SidebarDiagnostics.exe is visible in the Taskmanager though. What might be the issue here?

It could just be an issue with my system exclusively. If you’re not having the same problem as I am, then it’s probably just an issue with my computer.

**Comment by KrisSchneider** [comment]
Hello, I managed to fix my issue. I reset my computer, and it fixed the issue I was having.

**Comment by KrisSchneider** [comment]
Hello, I managed to fix my issue. I reset my computer, and it fixed the issue I was having.
