### ISSUE TITLE
Doesn't read/show some system info, why?

### ISSUE THREAD

**Issue by TestDmitriy** [ArcadeRenegade/SidebarDiagnostics#411]
**1. Is this a feature request?**
NO
*If yes then sorry but this project is not taking feature requests at this time.*

**2. Your Operating System**
WIN11 PRO (x64) 22H2/i9-9900K/MSI z390m EDGE AC/RAM 2x32GB G. SKILL RIPJAWS DDR-3200
**3. App Version**
3.6.2
**4. Any Relevant Settings**
a) Pic1: 
    CPU settings: "Voltage" and "Fan speed" are Marked but doesn't show on Bar. I use Cooler Master AIO (Separate connectors for Pump and Fans)
b) Pic2:
   RAM settings: "Clock" and "Voltage" doesn't shown on Bar too, but selected in Settings.
c) All settings related to GPU, Drives and Network works just fine
**5. Steps to Reproduce**
Open Sidebar Settings->Tab "Monitors"-> CPU/Memory settings (see pic1 and pic2)
![pic1](https://user-images.githubusercontent.com/86534431/202976767-2c50ead8-6af8-434a-93ad-e9dae7765c9d.jpg)
![pic2](https://user-images.githubusercontent.com/86534431/202976775-220e84e5-fe8a-4572-ab31-6642edd807af.jpg)
Thank you!

**Comment by spang21** [comment]
I had a similar issue with some info not being displayed after upgrading to the 13700k CPU. This is because the build of LibreHardwareMonitor that is bundled with SidebarDiagnostics is quite old since the app hasn't been updated in quite some time.

I was able to see fix this by downloading LibreHardwareMonitor and replacing the LibreHardwareMonitorLib.dll file in the Sidebar Diagnostics folder with the LibreHardwareMonitorLib.dll from the LibreHardwareMonitor folder.

**Comment by TestDmitriy** [comment]
I replaced "LibreHardwareMonitorLib.dll" and now i can see CPU Voltage, but rest of "non shown" settings still absent. Thank you for advise Spang21. Hopefully PhyxionNL will check our thread.

**Comment by ArcadeRenegade** [comment]
I'll try to do an update with the latest version of LibreHardwareMonitor this weekend.

**Comment by TestDmitriy** [comment]
Please and huge thank you!

**Comment by rockymtnpatriot** [comment]
> I'll try to do an update with the latest version of LibreHardwareMonitor this weekend.

I just opened Issue #414 for this same issue before seeing this one. I also updated the .dll and now see the missing CPU Metrics. An updated package would be great when you get time. Love this tool!

**Comment by deejayducky** [comment]
> > I'll try to do an update with the latest version of LibreHardwareMonitor this weekend.
> 
> I just opened Issue #414 for this same issue before seeing this one. I also updated the .dll and now see the missing CPU Metrics. An updated package would be great when you get time. Love this tool!

Can I ask how you updated the dll and it's steps, I tried to reproduce and sidebardiag crashed on me till I put the orig dll back in. Which DLL and were are you getting it? I'd like to have the work around till this is updated.

**Comment by rockymtngeek** [comment]
> > > I'll try to do an update with the latest version of LibreHardwareMonitor this weekend.
> > 
> > 
> > I just opened Issue #414 for this same issue before seeing this one. I also updated the .dll and now see the missing CPU Metrics. An updated package would be great when you get time. Love this tool!
> 
> Can I ask how you updated the dll and it's steps, I tried to reproduce and sidebardiag crashed on me till I put the orig dll back in. Which DLL and were are you getting it? I'd like to have the work around till this is updated.

All I did was extract the latest package for LibreHardwareMonitor and took the LibreHardwareMonitorLib.dll from there and replaced the original in the SidebarDiagnostics program folder. Started it up and it could then see my 13th gen CPU correctly.

**Comment by deejayducky** [comment]
Hrm, must be me, what .dll and what filepath are you replacing? Nothing with the same name, the one I tried replacing for a hail mary was openhardwaremonitorlib.dll and that's what gave me the error/crash.

**Comment by rockymtngeek** [comment]
.dll is located in your User\AppData folder:
AppData\Local\SidebarDiagnostics\app-3.6.2
I renamed the original to .old and copied in the new one - LibreHardwareMonitorLib.dll
Go to their repo and download their package, extract and copy/paste. https://github.com/LibreHardwareMonitor/LibreHardwareMonitor 

At this point you may need to uninstall and re-install sidebar diagnostics first.

**Comment by TestDmitriy** [comment]
Yes, try to re-install it and don't forget to run ccleaner for "Register" before new installation.
After last update(actual re-installation) nothing changed, i have the same issue. Info doesn't shown still.
All other programs like "HWiNFO64" can read all sensors with no problem, but not my lovely "SideBar".
ArcadeRenegade, I will make 1 time payment if you can fix it...

Thank you

**Comment by deejayducky** [comment]
> Yes, try to re-install it and don't forget to run ccleaner for "Register" before new installation. After last update(actual re-installation) nothing changed, i have the same issue. Info doesn't shown still. All other programs like "HWiNFO64" can read all sensors with no problem, but not my lovely "SideBar". ArcadeRenegade, I will make 1 time payment if you can fix it...
> 
> Thank you

Didn't need to run cccleaner in my case, but that dll update fixed it, and can see my temps ecc for my 13900k

**Comment by ArcadeRenegade** [comment]
Sorry it took so long. I just published Sidebar Diagnostics v3.6.3 with the latest commit of Libre Hardware Monitor.

**Comment by TestDmitriy** [comment]
After last update i can see Voltage now! Thank you, but still no "Fan usage" and "Clock" and "Voltage" for memory.
I have AIO (from Cooler Master), do you think that could be a reason of NO READING  "Fan usage" for CPU?

**Comment by ArcadeRenegade** [comment]
None of those metrics have ever worked for memory, I should probably remove
them honestly.

**Comment by TestDmitriy** [comment]
Agreed, Memory not so important like CPU.
Thank you again ArcadeRenegade, 
*PM me your info for PayPal transfer
