### ISSUE TITLE
Raptor Lake CPU Metrics not all working

### ISSUE THREAD

**Issue by rockymtngeek** [ArcadeRenegade/SidebarDiagnostics#414]
**1. Is this a feature request?** No

*If yes then sorry but this project is not taking feature requests at this time.*

**2. Your Operating System** Windows 10 22H2

**3. App Version** 3.6.2

**4. Any Relevant Settings** CPU Metrics for Clock & Temperature not working for 13th Gen i7-13700K. Only Load is reporting

**5. Steps to Reproduce** Raptor lake i7-13700K on Asus Z690 upgraded from Alder Lake CPU that was detecting Clock & Temperature is not after upgrading to Raptor Lake. From what I can surmise, this might be due to the version of 
LibreHardwareMonitor in this version of SidebarDiagnostics. That repository has a recent update calling out updates for Raptor Lake & Alder Lake CPU's. Is there a possibility of getting that latest package integrated?

**Comment by ArcadeRenegade** [comment]
I believe it should be working now in v3.6.3 since it uses the latest commit of Libre Hardware Monitor.

**Comment by rockymtngeek** [comment]
> I believe it should be working now in v3.6.3 since it uses the latest commit of Libre Hardware Monitor.

Confirmed, updated and all is functioning correctly on 13th gen. Thanks for the updated build!
