### ISSUE TITLE
Dialog box with Changelog when an update is performed

### ISSUE THREAD

**Issue by soapysoap** [ArcadeRenegade/SidebarDiagnostics#42]
Right now we need to go to the releases page every time there's an update. A box showing the changelog would be nice.

**Comment by ArcadeRenegade** [comment]
I'd like the update process to be as unobtrusive as possible. I would prefer to have no dialogs and such. If you have any other ideas let me know.

**Comment by ArcadeRenegade** [comment]
Actually a setting to just disable showing the change log would be fine.

**Comment by ArcadeRenegade** [comment]
implemented
