### ISSUE TITLE
Bar dissapears when "show desktop" button is pressed.

### ISSUE THREAD

**Issue by Neuen1** [ArcadeRenegade/SidebarDiagnostics#43]
I frequently use show desktop to minimize all my windows and have a look at the temperatures, but the bar dissapears when I press it.

**Comment by ArcadeRenegade** [comment]
Only way to prevent this is to enable always on top. WPF windows cannot be
immune to show desktop otherwise.

**Comment by Neuen1** [comment]
Got it. Thanks for your response.

**Comment by ArcadeRenegade** [comment]
It was difficult but I think I implemented a fix for this. Could you try with the new version?

**Comment by Subnim** [comment]
It works! I'm on Windows 10 Pro x64. This app is now perfect for me :D

**Comment by ArcadeRenegade** [comment]
Excellent :+1:

**Comment by Neuen1** [comment]
It's working for me too! Thank you so much for your dedication.
