### ISSUE TITLE
Error trying to install v3.x "Couldn't acquire lock"

### ISSUE THREAD

**Issue by bdog720** [ArcadeRenegade/SidebarDiagnostics#44]
This has been happening since v3 so I can't update to the latest version, see image below. I've made sure the old version is not running while trying to install the latest update

![image](https://cloud.githubusercontent.com/assets/11171840/13030473/92a9f176-d300-11e5-8c2e-638e71e2bab3.png)

**Comment by ArcadeRenegade** [comment]
I put in an issue with Squirrel.Windows. In the meantime, you can uninstall
the old version and download the new setup.exe and install the new one.

If you still get the error, edit the file:

%localappdata%\SidebarDiagnostics\settings.json

Change

"AutoUpdate":true

To

"AutoUpdate":false

If the file does not exist create it with this content

{"AutoUpdate":false}

**Comment by bdog720** [comment]
Thanks for the quick response!

Still getting the error even after uninstalling the old version. Had to create the settings file but it didn't seem to help either, I did notice that the settings file gets deleted whenever I run the setup.

I've attached the image of the contents of settings and the files location just to make sure I'm not doing it wrong

![image](https://cloud.githubusercontent.com/assets/11171840/13030764/09648de0-d30a-11e5-8372-bec4ac78033f.png)

**Comment by ArcadeRenegade** [comment]
The install is actually succeeding. The error is occurring when the SD app runs.

So do the uninstall. Then reinstall. Install succeeds. Runs my app. App errors. Shows error dialog.

Exit the app. Edit settings.json (you did it right btw). Rerun the app from the desktop or start menu shortcut.

**Comment by bdog720** [comment]
Oh right, awesome it worked! Seriously thanks for the quick response.

Love your app btw, its seriously awesome

**Comment by ArcadeRenegade** [comment]
Let's keep this open because the root issue of not being able to update still exists. And the workaround will help other users with the same issue. I'll let you know when I get a response from the dev who wrote Squirrel.Windows library, which is what the new install / update framework is.

**Comment by ArcadeRenegade** [comment]
No fix yet. But I added a better error handler for this in v3.1.0
