### ISSUE TITLE
Sidebar shifting to another monitor

### ISSUE THREAD

**Issue by ericl619** [ArcadeRenegade/SidebarDiagnostics#45]
can you add the option to auto reload when a monitor is connected/disconnected or on login? The sidebar can shift around to another monitor or have the wrong offset.

example: I'm running 3 monitors but I would also remote login as 1 monitor. When I sign back in from my desktop as 3 monitors, it would shift the sidebar to another monitor.

**Comment by ArcadeRenegade** [comment]
Do you have "reserve space" enabled? It repositions automatically but only
if that is enabled.

**Comment by ArcadeRenegade** [comment]
It should reposition even if "Reserve Space" is disabled now in 3.0.5

**Comment by ericl619** [comment]
thanks, the new version fixed it

**Comment by ArcadeRenegade** [comment]
Cool
