### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Chris92de** [ArcadeRenegade/SidebarDiagnostics#46]
Hey, not sure what version I had installed, but SidebarDiagnostics caused a bluescreen for me earlier today and now I get this error each time I try to start it:

![csrss_2016-02-17_19-17-31](https://cloud.githubusercontent.com/assets/5523125/13119816/4693e456-d5ab-11e5-9586-67fa5246c680.png)

How do I resolve this?

**Comment by ArcadeRenegade** [comment]
Uninstall and reinstall

**Comment by ArcadeRenegade** [comment]
What was your CPU workload when you BSOD? Was it 100%?

**Comment by Chris92de** [comment]
Reinstall fixed the problem, I honestly couldn't tell you now what the CPU usage was, I think it happened when I wanted to toggle the sidebar with my hotkey, might've hit 100% during it, had a bunch of stuff open.

**Comment by ArcadeRenegade** [comment]
Another user reported BSOD when he had 100 percent cpu utilization. It is probably because of the way open hard monitor works as it does a lot of native dll calls. As a workaround close the sidebar if cpu usage is near 100 percent. Crummy workaround but there's not much I can do unfortunately.
