### ISSUE TITLE
CSGO

### ISSUE THREAD

**Issue by derekbbn** [ArcadeRenegade/SidebarDiagnostics#47]
I play csgo at the res 1280x960 and I have 2 monitors. Both 1080p. I use the sidebar on the 2nd monitor, right side. After I close the game the sidebar moves to monitor 1

**Comment by ArcadeRenegade** [comment]
Is the resolution you are playing CSGO at smaller than your Windows resolution?

**Comment by ArcadeRenegade** [comment]
You can try binding the hotkey for "cycle screen" and use that as a workaround.

**Comment by derekbbn** [comment]
Yes I play @ 1280x960 and my windows res is 1080. I'll give that a try though. Thanks

**Comment by ArcadeRenegade** [comment]
I guess when you close CSGO it changes the resolution back to 1080 and the sidebar gets a work area change event and tries to reposition. Idk. I'll try to replicate.

**Comment by Simber1** [comment]
I get the same issue playing in 1440x1080, I just bound a key to reload and hit it everytime I open/close the game. it doesn't change screen instead just moves abit.

**Comment by ArcadeRenegade** [comment]
Might be fixed in v3.2.0
