### ISSUE TITLE
DPI getcore.dll issue

### ISSUE THREAD

**Issue by Maledict** [ArcadeRenegade/SidebarDiagnostics#48]
Hello new user heard about this on reddit I am having an issue with installing this program. 

I get the [following error](http://imgur.com/wIcezM4) while using windows 8 and trying both installs

I read about not using DPI scaling but everything is set to default I have cleartext off and no dpi scaling set in windows. Multiple boots to make sure all settings were set in stone and uninstall/reinstall of both installers.

Things that may conflict: Rainmeter, Display Fusion, Dual monitors one running 1920x1080 other 2560x1440p

*also installed as admin and ran as admin to no effect.

Any and all help would be appreciated

**Comment by ArcadeRenegade** [comment]
Windows 8 or 8.1?

**Comment by Maledict** [comment]
8

**Comment by ArcadeRenegade** [comment]
Oh. I just checked and that function isn't supported in Windows 8 like I thought. Just 8.1 and above. I'll fix it right now.

**Comment by Maledict** [comment]
Cool beans my fault for never updating installed a 3rd party windows button and never needed 8.1.

**Comment by ArcadeRenegade** [comment]
OK try the new version.

**Comment by Maledict** [comment]
Worked like a champ you sir are a miracle worker

**Comment by ArcadeRenegade** [comment]
I just think it's funny that you are the first person to find this error after over a month. You are my only windows 8 user Haha.

**Comment by ArcadeRenegade** [comment]
Glad it works though 👍

**Comment by Maledict** [comment]
#livinginthepast my mother always said I was special
