### ISSUE TITLE
Top screen not working as intended.

### ISSUE THREAD

**Issue by SHEePYTaGGeRNeP** [ArcadeRenegade/SidebarDiagnostics#5]
I have a setup like this: 2 monitors on the left on top of eachother and one on the right.
When I put the sidebardiagnostics on my 3rd ( top left ) monitor the black bar also comes down to my first monitor ( the one on the left ).
Check the image below for more info:
http://i.imgur.com/1d2FlDa.png

It also happends when I put my taskbar on the bottom instead of on the rightside on my top left monitor.

**Comment by ArcadeRenegade** [comment]
This *should* be fixed with version 1.2. Could you try it?

**Comment by SHEePYTaGGeRNeP** [comment]
Yes it worked now ( tested with 1.4 ).
