### ISSUE TITLE
Memory Usage Bug

### ISSUE THREAD

**Issue by campbeb** [ArcadeRenegade/SidebarDiagnostics#50]
- Building from latest commit
- All hardware monitors turned off
- Polling set at 50 seconds

![clipboard01](https://cloud.githubusercontent.com/assets/1089399/13181040/156898f0-d6f9-11e5-9180-cb68147dc34d.jpg)

Memory usage constantly climbs even though there shouldn't be any work being done. It drops down after some time, but each successive cycle hits a higher max than the previous.

**Comment by ArcadeRenegade** [comment]
The Open Hardware Monitor computer object is still opened even if all monitors are disabled. I guess they store data in between updates? I've never seen memory usage go above 100 MB under normal circumstances.

**Comment by campbeb** [comment]
I did some digging and this behavior was introduced in commit 031f4dfe90b43a8c6d3e2c418c632107baf35c0e.

This is always when CPU usage went up.

![image](https://cloud.githubusercontent.com/assets/1089399/13191554/94f2f654-d732-11e5-8ca9-026067944644.png)

WaitForNextMessage looks to be called excessively.

**Comment by ArcadeRenegade** [comment]
Good find. Thank you. I'll check it out when I get home.

**Comment by ArcadeRenegade** [comment]
Think you could show me how to display CPU usage like this?

**Comment by ArcadeRenegade** [comment]
I did a stupid.

http://stackoverflow.com/a/18019496/3185018

> Calling a delegate's EndInvoke() method is required, it causes a 10 minutes resource leak if you don't. It is not required for the Control/Dispatcher.BeginInvoke() methods and you never do so in practice.

What's causing it is this:

`new BindModelHandler(BindModel).BeginInvoke(null, null);`

I didn't realize I needed to call delegate.EndInvoke().

I've replaced it with Task.Run and implemented async Task awaits instead.

**Comment by campbeb** [comment]
The first picture was in Visual Studio.

The second is Process Explorer. Right click the process / Properties / Threads tab.

**Comment by ArcadeRenegade** [comment]
Cool. I replaced delegate.BeginInvoke with Thread.Run and I don't see that WaitForNextMessage call here. Instead I see MILQueryInterface.

![image](https://cloud.githubusercontent.com/assets/13874898/13193416/e0b14f06-d72c-11e5-8113-4465ffc3e9d9.png)

**Comment by ArcadeRenegade** [comment]
I just pushed a new commit with the task.run changes. Could you try it with your Process Explorer?

**Comment by ArcadeRenegade** [comment]
This could also be caused by the animated loading component. It hides after the sidebar is ready but maybe it's still doing stuff while it's hidden.

**Comment by ArcadeRenegade** [comment]
I think the animated loading widget being hidden rather than removed entirely had something to do with it as well. Looks a lot better now. Thanks for the help.

![image](https://cloud.githubusercontent.com/assets/13874898/13194185/fce949ca-d73c-11e5-8423-4b770fcbc39d.png)

**Comment by campbeb** [comment]
Glad you got it narrowed down.

**Comment by ArcadeRenegade** [comment]
It's a lot better on CPU now. It was regularly between 0.8% and 1.2% for me and now it hovers around 0.1% and 0.2%. Thanks a ton.

![image](https://cloud.githubusercontent.com/assets/13874898/13194332/d20f8aa6-d742-11e5-90ab-191bf7af5ac1.png)

**Comment by ArcadeRenegade** [comment]
The memory usage has also gone down as a result. After the garbage collectors cleaned up it dropped down to 28 MB.

![image](https://cloud.githubusercontent.com/assets/13874898/13194347/8c5bb2f4-d743-11e5-9734-54e3a6781e1e.png)
