### ISSUE TITLE
Improper Core Speed Reported

### ISSUE THREAD

**Issue by Daeyx** [ArcadeRenegade/SidebarDiagnostics#51]
Hi there,

I am I have the sidebar reading my core speed improperly. I am currently overclocked at a static 4.2 Ghz, however sidebar diagnostics will read my core speed as flip flopping in between 2.4 Ghz and 4.2 Ghz depending on load. This is the only program that reads this, Intel Speed Step is disabled and the processor does not clock down ever. Not sure why this is as no other monitoring program reports this behavior.

I've included two pictures below showing 2.4 and 4.2 depending on load.

Intel i7 970 Hexacore
Asus X58 sabertooth

![2 4 ghz](https://cloud.githubusercontent.com/assets/17358797/13198052/0673d046-d7c4-11e5-958f-96048fb44e16.jpg)
![4 2 ghz](https://cloud.githubusercontent.com/assets/17358797/13198053/06748b62-d7c4-11e5-95e7-13d0520fa289.jpg)

**Comment by ArcadeRenegade** [comment]
Could you download Open Hardware Monitor and check if the same thing happens?

**Comment by Daeyx** [comment]
Hi Ryan,

It does not. Rock solid 4.2 ghz.

Thank you for responding.

**Comment by ArcadeRenegade** [comment]
Really?? Weird. Technically I'm using a "newer" version of OHM and it may have a regression bug. Can I send that to you to try?

Just trying to confirm the issue is in my code and not theirs. Idk what would cause this.

**Comment by Daeyx** [comment]
Absolutely, please do, I will give it a shot.

**Comment by ArcadeRenegade** [comment]
[OHM_LatestBuild.zip](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/139365/OHM_LatestBuild.zip)

**Comment by Daeyx** [comment]
Well, I feel very stupid now. After renabling my overclocked, I realized I
had c1e enabled in the bios. Very sorry to waste your time!

Everything is accurately reported now!

Thanks again Ryan, this program is a big hit among my colleagues.

**Comment by ArcadeRenegade** [comment]
Haha it's quite alright. Glad you guys like it.
