### ISSUE TITLE
Hide SidebarDiagnostics from alt+tab/win+tab

### ISSUE THREAD

**Issue by edde275** [ArcadeRenegade/SidebarDiagnostics#52]
Is it possible to add an option to hide SidebarDiagnostics from showing up as an application along with other open applications in these menus?

**Comment by ArcadeRenegade** [comment]
Sure

**Comment by ArcadeRenegade** [comment]
I'll implement it

**Comment by edde275** [comment]
Cool, awesome tool by the way!

**Comment by ArcadeRenegade** [comment]
Implemented.
