### ISSUE TITLE
Toolbar mode does not work when in fullscreen mode.

### ISSUE THREAD

**Issue by Valansch** [ArcadeRenegade/SidebarDiagnostics#53]
It neither hides nor push the fullscreen to the left to not overlap:
![image](http://i.imgur.com/J2wg2b3.png)

**Comment by ArcadeRenegade** [comment]
Toolbar mode?

**Comment by ArcadeRenegade** [comment]
Looks like you have "reserve space" off and "always on top" on, correct?

**Comment by Valansch** [comment]
Sorry for the lack of info. I thought the checkbox "Reserve Space" was named Toolbar mode or something like that.

No i have not.
Reserve Space is on and Always On Top is also on.

I managed to reproduce it. It behaves exactly like the taskbar (whose behavior is also not to my liking)
Meaning: If i fullscreen, both bars hide. If i select another window of the browser both bars show.
But when they show, they don't reserve the space anymore, so a part of my fullscreen image is hidden behind the bars. It does not reserve the space anymore if in fullscreen but rather overlays it.

What i thought that the reserve space feature means is that it is ALWAYS there, even if fullscreened. I don't want to uncheck the box "always on top" because i actually want to see it even in fullscreen.

**Comment by ArcadeRenegade** [comment]
I see. Well I have it coded so that when another window goes fullscreen in
that monitor, the sidebar gives up topmost until that window isn't
fullscreen anymore.

Unfortunately, what I don't have control of is being able to keep the space
reserved when another window goes fullscreen. Fullscreen completely
overrides it and takes up all available space.

**Comment by Valansch** [comment]
Yea. I figured that is was something like that. So i will just disable always on top. Thanks

**Comment by ArcadeRenegade** [comment]
There may be a 3rd party tool that can force fullscreen to just use the work area?

**Comment by Valansch** [comment]
Idk, but then again, that would be to much of a hassle so i will just disable always show.
