### ISSUE TITLE
.net framework is not found

### ISSUE THREAD

**Issue by pglira** [ArcadeRenegade/SidebarDiagnostics#54]
As can be seen on the following screenshot, I installed .net framework 4.6, but Sidebar Diagnostics can still not find it:
![image](https://cloud.githubusercontent.com/assets/14214284/13244667/44b5e0ce-da08-11e5-9e27-244ade2748e4.png)

**Comment by ArcadeRenegade** [comment]
You installed .NET 4.6.0. You need .NET 4.6.1.

https://www.microsoft.com/en-us/download/details.aspx?id=49981

**Comment by pglira** [comment]
If I choose Yes here...
![2016_02_23_08_53_15](https://cloud.githubusercontent.com/assets/14214284/13245091/03f97354-da0b-11e5-92a5-6aaff381ff89.png)
...I'm redirected directly to this website...
![2016_02_23_08_53_24](https://cloud.githubusercontent.com/assets/14214284/13245096/0f98ab30-da0b-11e5-9349-f9347a9fcfc2.png)
...where automatically .net 4.6 is downloaded.

However, if I follow your link (or the link to .net 4.6.1 on the upper website) this website appears...
![2016_02_23_08_55_32](https://cloud.githubusercontent.com/assets/14214284/13245118/3ddcea2e-da0b-11e5-9042-d0b4aac4ef2a.png)

**Comment by ArcadeRenegade** [comment]
Please use the .NET 4.5.2 version.

https://github.com/ArcadeRenegade/SidebarDiagnostics/releases/download/3.0.8/Setup_452.exe
