### ISSUE TITLE
Sidebar in wrong place at start up always

### ISSUE THREAD

**Issue by kryptek49** [ArcadeRenegade/SidebarDiagnostics#55]
Hi, first up I've got to say that I love the sidebar, its great!
I'm having this really annoying issue though where at start up the side bar ignores my setting of a -45 Horizontal Offset and goes back to the default 0. In the settings it still says -45, and if I open up the settings and save again then it sets itself back to how it should (without me changing anything)
Is there a fix for this or have I not get it set up properly?

I'm using it on a 1440p monitor but I have all the settings as they should be (I think) so I hope you can help.

Thanks in advance!

**Comment by ArcadeRenegade** [comment]
Does the same thing happen if you close the app and run it again?

**Comment by ArcadeRenegade** [comment]
Also you have "High DPI Support" enabled right? Just checking.

**Comment by kryptek49** [comment]
Yeah I have High DPI Support on, that would have been embarrassing!

If I close the app and open it again it opens in the wrong place again (ignoring my settings)

If I then open the settings and click "save" without changing anything it moves into the right position.

**Comment by kryptek49** [comment]
Here is how I want it to be (after saving), and how it actually opens:

![2](https://cloud.githubusercontent.com/assets/17470839/13315968/b0fc3668-dba5-11e5-8520-1b6e367f8bc2.jpg)
![1](https://cloud.githubusercontent.com/assets/17470839/13315971/b2720b94-dba5-11e5-91e4-05d8e8c39365.jpg)

**Comment by ArcadeRenegade** [comment]
That's really odd. It's going to be hard to troubleshoot because I don't
have a high dpi monitor but I'll see what I can do. Thanks for reporting.

**Comment by kryptek49** [comment]
Thanks, my DPI is 117 which doesnt help I guess, I've got my tv set up as a second monitor so I'l try it on that  to see if a lower DPI helps, if not I'l uninstall it and reinstall and hope for the best. Thanks for your time.

**Comment by kryptek49** [comment]
Okay it works perfectly when using it on my tv with a lower DPI so I dont know if its something to do with that?

**Comment by ArcadeRenegade** [comment]
Yeah it has always had issues with high DPI monitors. I've been able to
slowly fix the issues one by one though.

**Comment by ArcadeRenegade** [comment]
As a temporary workaround you can bind the reload hotkey and hit that
rather than opening up the settings every time

**Comment by ArcadeRenegade** [comment]
You are using Windows 10, correct?

**Comment by ArcadeRenegade** [comment]
I think I figured out the core issue with high dpi monitors. In the next release you shouldn't need an offset at all. 

Out of curiosity, which monitor is the sidebar on? Could you maybe post a full desktop screenshot of your setup?

**Comment by ArcadeRenegade** [comment]
Nm I figured it out. Fixed in v3.2.0

**Comment by kryptek49** [comment]
Sorry about the slow reply I'm working, Yeah its Windows 10, thanks for
your help I hope it works!

**Comment by ArcadeRenegade** [comment]
np. you'll have to set your horizontal and vertical offset back to 0 though

**Comment by kryptek49** [comment]
Thanks, if everything works out now il be happy to donate :)
