### ISSUE TITLE
GPU Clock speed label

### ISSUE THREAD

**Issue by CodingContraption** [ArcadeRenegade/SidebarDiagnostics#56]
I just noticed the Clock speed is labeled "Core" for the GPU, while the Same label is used for the usage of the GPU. Is this a mistake or intentional?

**Comment by ArcadeRenegade** [comment]
Yeah its supposed to be "core clock" and "core load" but I wanted the labels to be as narrow as possible. Maybe it wouldn't look that bad if they were a little wider though.

**Comment by ArcadeRenegade** [comment]
What I mean is I tried to keep the labels short

**Comment by CodingContraption** [comment]
I see. I think Clock and Load might work just fine too, just like the CPU.

**Comment by ArcadeRenegade** [comment]
Well there's also VRAM Clock and Load. Which is why it might get confusing.

**Comment by CodingContraption** [comment]
Ah, I see. Just extending them to the full names might clarify it indeed.
As another idea, maybe you could group them? As in:

Core
  Clock: 0 Mhz
  Load: 0%

VRAM
  Clock: 0 Mhz
  Load: 0%

That way you save horizontal spacing.

**Comment by ArcadeRenegade** [comment]
That's a good idea. I'll try both and let you know.

**Comment by ArcadeRenegade** [comment]
After mulling it over for a while I decided to keep it the way it. That way it saves horizontal and vertical space. I feel like it is fairly easy enough for the user to differentiate between clock load and clock speed because the numbers and measurements are different.

**Comment by ArcadeRenegade** [comment]
Keep it the way it is*

**Comment by CodingContraption** [comment]
Fair enough. Feel free to close the issue. :)

**Comment by ArcadeRenegade** [comment]
Thanks!
