### ISSUE TITLE
[bug] Sidebar invisible

### ISSUE THREAD

**Issue by Valansch** [ArcadeRenegade/SidebarDiagnostics#57]
I have no idea how to reproduce it. I'm pretty sure a restart of the program would if it. I'm not gonna for now in case  you want me to try something to figure out what causes it.

Couple screenshots with settings:

![image](http://puu.sh/nl1RR/52d929b12e.png)
![image](http://puu.sh/nl1Uk/c5f875c58f.jpg)
![image](http://puu.sh/nl27e/dcfce9de24.jpg)
![image](http://puu.sh/nl1ZA/f2e752ee2c.jpg)
![image](https://cloud.githubusercontent.com/assets/10226478/13326103/d8300284-dbe4-11e5-8173-9dc5ccf29699.png)
![image](http://puu.sh/nl2od/3733b08c5b.jpg)

**Comment by ArcadeRenegade** [comment]
It just disappeared randomly?

**Comment by Valansch** [comment]
Yes. Sorry i don't have anything more that i could help you with.
