### ISSUE TITLE
Sidbar going on to other screen

### ISSUE THREAD

**Issue by crackerjam** [ArcadeRenegade/SidebarDiagnostics#58]
So, I've got the sidebar configured to be on my top monitor, almost exactly how I want it. However, the bar is too long, and bleeds down to the monitor below it. 

Screenshot!
![20160225_143128](https://cloud.githubusercontent.com/assets/7827071/13331758/f74909a8-dbcc-11e5-9e75-0c7820d06065.jpg)

Edit: I have no idea why that image is sideways.

**Comment by ArcadeRenegade** [comment]
What dpi is your monitor? If it's above 96 do you have high dpi support
enabled?

**Comment by crackerjam** [comment]
I don't know what the DPI is, but the top is a 22" 1080p monitor, and the bottom a 27" 4k monitor. Having high dpi support enabled or disabled doesn't have any effect.

**Comment by ArcadeRenegade** [comment]
I see. The bottom 4K monitor is your primary monitor in your Windows settings, correct?

**Comment by ArcadeRenegade** [comment]
Could you run my monitor debug program and copy paste the results? The data would be helpful.

https://drive.google.com/open?id=0B2nGKa6VrrDOOG1GWndBNk9MbjQ

**Comment by ArcadeRenegade** [comment]
Also what is your operating system?

**Comment by crackerjam** [comment]
Correct. I'm running Windows 10, and here's the output:

```
Monitor Debug Program

Monitor #0

Is Primary: True

Size:
Left: 0
Top: 0
Right: 3840
Bottom: 2160

WorkArea:
Left: 0
Top: 0
Right: 3840
Bottom: 2100

DPIx: 144
DPIy: 144
ScaleX: 1.5
ScaleY: 1.5

Emulate Sidebar Left
Left: 0
Top: 0
Right: 270
Bottom: 2100

Emulate Sidebar Right
Left: 3570
Top: 0
Right: 3840
Bottom: 2100

Monitor #1

Is Primary: False

Size:
Left: 3840
Top: 492
Right: 5760
Bottom: 1572

WorkArea:
Left: 3840
Top: 492
Right: 5760
Bottom: 1572

DPIx: 96
DPIy: 96
ScaleX: 1
ScaleY: 1

Emulate Sidebar Left
Left: 3840
Top: 492
Right: 4020
Bottom: 1572

Emulate Sidebar Right
Left: 5580
Top: 492
Right: 5760
Bottom: 1572

Monitor #2

Is Primary: False

Size:
Left: 1030
Top: -1080
Right: 2950
Bottom: 0

WorkArea:
Left: 1030
Top: -1080
Right: 2950
Bottom: 0

DPIx: 96
DPIy: 96
ScaleX: 1
ScaleY: 1

Emulate Sidebar Left
Left: 1030
Top: -1080
Right: 1210
Bottom: 0

Emulate Sidebar Right
Left: 2770
Top: -1080
Right: 2950
Bottom: 0

Monitor #3

Is Primary: False

Size:
Left: -1920
Top: 515
Right: 0
Bottom: 1595

WorkArea:
Left: -1920
Top: 515
Right: 0
Bottom: 1595

DPIx: 96
DPIy: 96
ScaleX: 1
ScaleY: 1

Emulate Sidebar Left
Left: -1920
Top: 515
Right: -1740
Bottom: 1595

Emulate Sidebar Right
Left: -180
Top: 515
Right: 0
Bottom: 1595
```

**Comment by ArcadeRenegade** [comment]
Thank you. And which monitor # is it docked to in the settings? It says monitor #3, correct?

**Comment by crackerjam** [comment]
Correct.

**Comment by crackerjam** [comment]
Here are the specific settings I have it using to get it where it's at now:
<img width="209" alt="advanced" src="https://cloud.githubusercontent.com/assets/7827071/13337439/5df9f1a0-dbe9-11e5-8af8-8ea5cade42f2.PNG">
<img width="209" alt="customize" src="https://cloud.githubusercontent.com/assets/7827071/13337441/5dfa2c4c-dbe9-11e5-8583-450a0fa92cdb.PNG">
<img width="207" alt="general" src="https://cloud.githubusercontent.com/assets/7827071/13337440/5dfa4b96-dbe9-11e5-823c-46438be90e6c.PNG">

**Comment by ArcadeRenegade** [comment]
OK one last test. Sorry for the trouble.

Here is another monitor debug app. It'll create a small dragable window that displays it's current location. It's location is based on the top left corner of its window.

Could you please hold left click and drag this window's top left corner, to where your top monitor and primary monitor meet?

Basically drag it to the bottom left corner of your top monitor (where the sidebar currently is).

Maybe also do a test at the top left corner of your top monitor (where the sidebar currently is).

Please post screenshots if you can.

https://drive.google.com/file/d/0B2nGKa6VrrDOeVZnZGpNdmZwVnM/view?usp=sharing

**Comment by crackerjam** [comment]
No worries, happy to help! I apologize in advance for how gigantic these images are.
<img width="3840" alt="shot1" src="https://cloud.githubusercontent.com/assets/7827071/13340661/306357ce-dc00-11e5-8f1e-423d4b990fad.png">
<img width="3840" alt="shot2" src="https://cloud.githubusercontent.com/assets/7827071/13340662/306441f2-dc00-11e5-9b5f-7229fa64c32b.png">

**Comment by ArcadeRenegade** [comment]
Perfect. You just solved the mystery.

The DPI scale of your **primary** monitor needs to be taken into account when determining the position.

Right now it's using the DPI of the monitor it currently is on.

**Comment by ArcadeRenegade** [comment]
Could you do one last test for me? This one will help high DPI users that have "reserve space" enabled. 

Could you enable reserve space and test if the space reserved is correct? 

Maybe open a chrome tab maximize on your top screen and see if they overlap each other at all?

**Comment by ArcadeRenegade** [comment]
Thanks again for the help. It's been difficult without a high dpi monitor.

**Comment by ArcadeRenegade** [comment]
Ok

**Comment by ArcadeRenegade** [comment]
Sorry I hit the wrong button. Everything should be fixed in v3.2.0 now

I figured out how to emulate a high DPI monitor in Windows.

**Comment by crackerjam** [comment]
I just got the update earlier, and it works as expected! Thanks a bunch for this app, it rocks. Also, a suggestion, if you could figure out a way to add graphs for CPU and network utilization, that'd be pretty awesome.

**Comment by ArcadeRenegade** [comment]
Thanks but I think graphs are a little out of scope for the application. It should focus on real-time monitoring. And graphs are available by default in Windows via performance counters, task manager, or performance monitor.

**Comment by ArcadeRenegade** [comment]
The only thing I was worried about was memory usage but if I have the graph start saving the last 30 seconds since it was opened, then the memory usage wouldn't be bad. Maybe I'll implement it.

**Comment by crackerjam** [comment]
Yeah, something like just the last 30 seconds is what I was thinking. I've noticed times when the values for cpu or network jump up and down, which makes it a little difficult to see actual usage levels. Actually, some sort of 5 second average would solve that problem too. Or both the graph and average value with a configurable time period? I have too many ideas. Anyway, awesome app either way, thanks again!

**Comment by luckydonald** [comment]
@crackerjam https://github.com/ArcadeRenegade/SidebarDiagnostics/issues/58#issuecomment-189073881
Great Background!
