### ISSUE TITLE
Freezing for a couple of seconds

### ISSUE THREAD

**Issue by MattVanEy** [ArcadeRenegade/SidebarDiagnostics#59]
Since the latest 2 versions my sidebar freezes from time to time for a couple of seconds (sometimes 2 seconds, had it up to 10 seconds max). In this time its not updating properly. It´s not a big deal, just wanted to share it.

My settings: http://i.imgur.com/DmQVTEQ.jpg
Video of the sidebar freezing: https://www.youtube.com/watch?v=QSkDGQT3dEc&feature=youtu.be

**Comment by ArcadeRenegade** [comment]
I just noticed it myself. I'll have to find the cause.

**Comment by ArcadeRenegade** [comment]
It's because of the loading widget. It will be fixed in the next version.

**Comment by ArcadeRenegade** [comment]
Should be fixed now.

**Comment by MattVanEy** [comment]
Working fine now, thanks for the fast fix
