### ISSUE TITLE
Icon does not show correctly in "hidden" system tray

### ISSUE THREAD

**Issue by guilhermelawless** [ArcadeRenegade/SidebarDiagnostics#6]
In Windows 8.1, and this is how the icon shows in system tray (completely invisible, it's the last icon).
![Hidden in system tray](https://i.gyazo.com/216d1965dea4fd5fc79f08079b33b13e.gif)

In contrast, where not hidden in system tray, here's how it shows.
![Shown in system tray](https://i.gyazo.com/643021cb28c0d88e35d7073083fa696e.png)

Using version **1.4** right now.

**Comment by ArcadeRenegade** [comment]
Odd. I'll put in an issue with the tray icon library I am using.

**Comment by ArcadeRenegade** [comment]
I switched the tray icon to window.forms. Hope it works because I'd rather have not that dependency. Could you test it?

**Comment by DotcomL** [comment]
Still having the issue with v1.5. However, now when I click it, it goes to another state. Here's a GIF:

![gifV1_5](https://i.gyazo.com/b3f25761cf653edc45bcba3514030c94.gif)

**Comment by ArcadeRenegade** [comment]
I just realized it's not actually invisible... It's because the icon is white and your tray popup has a white background as well.

**Comment by ArcadeRenegade** [comment]
Created a new icon which has more color to it. It should be more visible now.
