### ISSUE TITLE
Possibility to select independant statistics under each monitor

### ISSUE THREAD

**Issue by renesdk** [ArcadeRenegade/SidebarDiagnostics#60]
Windows 10 (1511) 64-bit
Sidebar Diagnostics v 3.2.1

It would be a nice addition to be able to select out the few diagnostics you want from each monitor instead of them basically just being on and off (for the most part).

An example could be that under Drives it would be nice to be able to select the statistics individually. Like this:
I would like the 'used percentage' shown, and 'free size (GB)' shown, but the actual 'used size (GB)' hidden.
Under GPU: Be able to choose the statistics individually as I'm not interested in them all at once.

And so on with the rest of the statistics under the other hardware parts.

**Comment by ArcadeRenegade** [comment]
Right now the UI for monitor settings is very packed as it is. But if you can think of a way to integrate it without taking up too much space then sure.

**Comment by renesdk** [comment]
Maybe a single check box at the top of the Monitors tab, with a short description 'If you enable this, additional settings will be shown' and then individual statistics settings will be enabled?

Or you could make an 'Advanced settings' check box under the Advanced settings tab. When enabling this advanced settings are enabled across the application adding more interesting features that normal people might not want or need by default, but the tinkerers might want?

**Comment by ArcadeRenegade** [comment]
implemented
