### ISSUE TITLE
Sidebar flickering

### ISSUE THREAD

**Issue by Iannnr** [ArcadeRenegade/SidebarDiagnostics#61]
**1. Your Operating System**
Windows 10 N 64-bit
**2. App Version**
V3.2.1
**3. Any Relevant Settings**
http://puu.sh/nnlsc/0acb42ce96.png
**4. Steps to Reproduce**
https://i.gyazo.com/b23b809a5917557804b003271ae54afd.gif
Just selecting Apply or OK causes it to flicker, this is currently on my second monitor, sometimes gets fixed by Reloading, sometimes causes this error - http://puu.sh/nnlsc/0acb42ce96.png

**Comment by ArcadeRenegade** [comment]
Could you try moving your taskbar to a different edge and see I'd the same thing happens to the sidebar?

**Comment by ArcadeRenegade** [comment]
If the same thing *

**Comment by ArcadeRenegade** [comment]
Also did the same thing happen in previous versions?

**Comment by ArcadeRenegade** [comment]
Does this still occur?
