### ISSUE TITLE
[Feature Request] NIC - Internet Traffic Only

### ISSUE THREAD

**Issue by SubElement** [ArcadeRenegade/SidebarDiagnostics#62]
I usually run another application to monitor my network called DU Meter. I has a function where you can monitor just INTERNET traffic over a NIC.

Is it possible to have this feature in Sidebar Diagnostics?

Thanks!

**Comment by ArcadeRenegade** [comment]
I can't find this specific metric in Windows Performance Counters. But if it's there then it's possible. Otherwise it won't unfortunately.

**Comment by ArcadeRenegade** [comment]
Not possible, unfortunately.
