### ISSUE TITLE
Sidebar freezes while using USB tethering from my phone.

### ISSUE THREAD

**Issue by NikoPennanen** [ArcadeRenegade/SidebarDiagnostics#63]
**1. Windows 10 64bit**

**2. Latest**

**3. None**

**4. Connect phone to PC and enable USB tethering. The sidebar freezes. It starts working again if I disable the tethering.**

**Comment by ArcadeRenegade** [comment]
Is it an android phone? Could you download open hardware monitor and test
if the same thing happens?

**Comment by campbeb** [comment]
I can confirm this behavior on Windows 10 64bit with latest commit with Android phone.

I can make it go away if I disable Network monitoring (other than it will freeze again when I try to open settings).

It seems to be hanging in `NetworkMonitor::Update` at 
```C#
            if (!PerformanceCounterCategory.InstanceExists(ID, CATEGORYNAME))
```

**Comment by campbeb** [comment]
For what it's worth, Windows Task Manager exhibits the same type of behavior when I turn on USB tethering. The displays in the Performance tab stop updating for a bit and then finally come back to life, but updating no more than every 5-10 seconds even on High speed.

**Comment by campbeb** [comment]
@NikoPennanen I was able to fix my issues with some help from here: http://forum.xda-developers.com/android/general/fix-usb-tethering-lags-freezes-windows-t3039183

@ArcadeRenegade This is a Windows / driver issue, not your program.

**Comment by ArcadeRenegade** [comment]
Thanks again @campbeb! You're my hero!

**Comment by ArcadeRenegade** [comment]
Added to the wiki.
