### ISSUE TITLE
Enhancement: Aligned Text

### ISSUE THREAD

**Issue by Vassile-D** [ArcadeRenegade/SidebarDiagnostics#64]
It would be great to have an option to toggle aligned text.

Instead of showing:

`Core: 135 MHz`
`VRAM: 300 MHz`
`Temp: 35 C`
`Fan: 40%`
`Read: 50 kB/s`
`Write: 10.36 kB/s`

The aligned version is better for quick-glancing on this widget and know what's going on:

`Core:____135_MHz`
`VRAM:____300_MHz`
`Temp:_____35_C`
`Fan:______40_%`
`Read:_____50_kB/s`
`Write:_10.36_kB/s`

(Underscores indicate spacing.)

This requires either using a fixed-width (monospaced) font and add proper white-spaces, or having separated columns of texts (textboxes) and making the second column start at a fixed position.

**Comment by ArcadeRenegade** [comment]
This is a good idea and it would be relatively easy to implement.

Just separate the textbox for the metric into two. One for the label and
another for the value. If it's align right then set the value textbox to
horizontal alignment right.

**Comment by ArcadeRenegade** [comment]
implemented

**Comment by ArcadeRenegade** [comment]
It's in the settings under the customize tab. In case you have trouble finding it.
