### ISSUE TITLE
Windows 10 Volume Menu appears below the sidebar then flickers and comes up

### ISSUE THREAD

**Issue by veermaharaj** [ArcadeRenegade/SidebarDiagnostics#68]
Windows 10 Volume Menu appears below the sidebar then flickers and comes up above the sidebar.

It should come up above the sidebar by default.

**Comment by ArcadeRenegade** [comment]
I was able to replicate. This only occurs when "Reserve Space" is enabled.

Unfortunately this isn't something I can really resolve. Seems like a bug with the Windows operating system.
