### ISSUE TITLE
Bug report on network speed.

### ISSUE THREAD

**Issue by KarlOfDuty** [ArcadeRenegade/SidebarDiagnostics#69]
Hello, I have found a bug. The alert thing on network doesn't work over 1023kB/s, as it then switches to checking for x number of MB/s instead of x number of kB/s;

**1. Your Operating System**
Windows 10 Pro
**2. App Version**
3.3.4
**3. Any Relevant Settings**
Network speed alert at any number with speeds above 1MB/s
**4. Steps to Reproduce**
Step 1: Put alert limit to 500
Step 2: Make speed go over 1MB/s
Step 3: ???
Step 4: Profit

**Comment by ArcadeRenegade** [comment]
thanks for the report. fix in v3.3.5
