### ISSUE TITLE
Setting the BGOpacity to 0 prevents you from opening the Settings Dialog again

### ISSUE THREAD

**Issue by JakobWe** [ArcadeRenegade/SidebarDiagnostics#7]
Apparantly the menu buttons only appear if your mouse hovers over a visible UI Element, which means that with BGOpacity 0 you can only make the menu buttons appear by hovering your mouse over text. A quick workaround is to set the Opacity to 0.01, which still looks fully transparent, but allows you to open the menu again.

**Comment by ArcadeRenegade** [comment]
I was looking into this yesterday and found no way to make the window register hit events on the entire background if it is completely transparent. The only workaround is to set the opacity to 0.01 like you said but I'm worried that might be slightly noticeable.

**Comment by hollywoodscotty** [comment]
You can set the opacity to 0 and still access via task manager. I didn't know it was there, but after I found out I even prefer to not have the X and Cog in the corner.

**Comment by ArcadeRenegade** [comment]
Implemented a workaround by setting the minimum opacity value to 0.01
