### ISSUE TITLE
[Feature Request] Option to disable metric labels

### ISSUE THREAD

**Issue by cptnfool** [ArcadeRenegade/SidebarDiagnostics#71]
When I have my CPU metric enabled, I know it's model number isn't going to change; an option to hide that line (so I can fit more metrics on the screen without scrolling) would be great!

Similarly for the GPU and Network metrics, I'd like to hide the name of my Graphics card.

This part might be a separate issue/FR, but I'd also like the ability to have the time simply be on the same line as the clock icon, without the word 'Time' visible.

Thanks!

**Comment by ArcadeRenegade** [comment]
You can disable the name of the hardware by unchecking the "Show Hardware Names" option under the "Monitors" tab.

![image](https://cloud.githubusercontent.com/assets/13874898/14095574/a1a31fa8-f516-11e5-83a2-3679e50f60ba.png)

You can disable specific metrics by clicking the "Metrics" dropdown and unchecking whatever metrics you do not want.

![image](https://cloud.githubusercontent.com/assets/13874898/14095611/e22aef10-f516-11e5-88fc-2d4f3b2f4f62.png)

As for the time issue, I would prefer to keep it as is and not have to implement another time setting.

**Comment by cptnfool** [comment]
Hmm, I missed those options, thanks.

While I wish there was customizability, I can see why you want to keep the UI as simple as possible for time.

Thanks!
