### ISSUE TITLE
[enhancement] More conspicuous alert 

### ISSUE THREAD

**Issue by HughParsonage** [ArcadeRenegade/SidebarDiagnostics#72]
I love this application, but the alert font color seems too inconspicuous for some kinds of alerts.

For example, if my CPU temperature reached > 90°C, I'd like to know about it instantly, not just sporadically as I cast my eye to the right of the screen. 

Suggested enhancements:

- Two levels of alerts, one the current alert (red font color) and the other for 'immediate' alerts.
- For the 'immediate alert', the background color should blink or perhaps change to red

**Comment by ArcadeRenegade** [comment]
having two different alert values would require a lot of code refactoring. how about having the alert blink white / red instead?

**Comment by HughParsonage** [comment]
Yeah, that would be perfect for me. My suggestion was only there because some might prefer to keep the old format.

**Comment by ArcadeRenegade** [comment]
I ran into a technical problem while implementing this. It works fine if I hardcode a static alert color like red but I can't get it to work with the users custom alert color from the settings.

**Comment by HughParsonage** [comment]
Could it be a checkbox 'Blink red on alert condition'? i.e. don't give the user the option yet

**Comment by ArcadeRenegade** [comment]
implemented
