### ISSUE TITLE
App Title gets stuck in top of corner

### ISSUE THREAD

**Issue by addrum** [ArcadeRenegade/SidebarDiagnostics#73]
**1. Windows 10**

**2. 3.3.5**

Not sure how to replicate this as it happens really intermitently.

![image](https://cloud.githubusercontent.com/assets/2855069/14366733/2dbd789c-fd0c-11e5-9a48-9f2e4406f778.png)

If you look in the top left corner, the label (?) or something is stuck in the top corner and the only way to remove it is to restart.

**Comment by ArcadeRenegade** [comment]
I applied a new update for the library I use to handle the tray icon. Might be fixed .now.
