### ISSUE TITLE
Font size 14 not available from the config menu

### ISSUE THREAD

**Issue by hpcchkop** [ArcadeRenegade/SidebarDiagnostics#74]
In the Config menu there is no Option to pick font size 14.
If you set it via the config .json it works fine.

**Comment by ArcadeRenegade** [comment]
Could you provide some more information? I cannot replicate the bug.

Please provide:
- Windows OS Version
- Steps to reproduce
- Screenshot

**Comment by hpcchkop** [comment]
[DxDiag.txt](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/211115/DxDiag.txt)
![fontsize](https://cloud.githubusercontent.com/assets/6873862/14402303/ccf2130c-fe31-11e5-8ac8-126f5c3d454f.png)
![fontsize3](https://cloud.githubusercontent.com/assets/6873862/14402324/92689534-fe32-11e5-881e-951b028567c3.png)
![fontsize2](https://cloud.githubusercontent.com/assets/6873862/14402323/8dfb99d8-fe32-11e5-9438-9125d21dc756.png)

Steps to Reproduce:
1. Choose any font size other than 14.
2. Restart the App.
3. The font size Option that should be 14 will be replaced by a second one of the one selected before.

Observations:
If I select size 18 and restart the app - not the 5th entry of the combo box will be the active one but the "clone" 3rd one (that should be 14.
If i set font size 14 via the settings.json and restart the app, the middle option will be 14 like it should be.

![fontsize4](https://cloud.githubusercontent.com/assets/6873862/14402341/1f188f16-fe33-11e5-8c14-74b881f6a180.png)

**Comment by ArcadeRenegade** [comment]
Was able to reproduce. Thanks.

**Comment by ArcadeRenegade** [comment]
fixed
