### ISSUE TITLE
Auto update error.

### ISSUE THREAD

**Issue by hpcchkop** [ArcadeRenegade/SidebarDiagnostics#75]
**1. Your Operating System**
Windows 10 Pro 64-bit (10.0, Build 10586) (10586.th2_release_sec.160223-1728)
**2. App Version**
Started about 1-2 months ago
**3. Any Relevant Settings**
Auto Update enabled
**4. Steps to Reproduce**
When a new update is released, the app throws an error when starting.
![untitled](https://cloud.githubusercontent.com/assets/6873862/14403196/4a6e9c08-fe4e-11e5-9688-b2b064fe4fdf.png)
Auto Update gets disabled in the process.

When updating manually via Right-Click -> Update the app updates like normal.

**Comment by ArcadeRenegade** [comment]
Should be fixed now.
