### ISSUE TITLE
Suggestion: Make the teperature alert blinking optional.

### ISSUE THREAD

**Issue by Neuen1** [ArcadeRenegade/SidebarDiagnostics#77]
I used this feature to be able to see my temperatures more easily, setting the temperature alert to 1 degree so it would stay colored differently from the rest of the text.Now with the blinking it's not possible for me to do it anymore, could you make a toggle for this option?

**Comment by ArcadeRenegade** [comment]
OK sorry about that I'll implement a toggle setting

**Comment by Neuen1** [comment]
Thank you! You are rally doing an awesome work with this software, I'm loving it and really appreciate you listen to suggestions.

**Comment by ArcadeRenegade** [comment]
implemented.

**Comment by ArcadeRenegade** [comment]
Glad you like it.
