### ISSUE TITLE
Error Installing v.3.3.6

### ISSUE THREAD

**Issue by tuddsfn** [ArcadeRenegade/SidebarDiagnostics#78]
I've been having troubles installing the latest version on my computer that I've never had before. It keeps giving me a "Installation has failed" error (http://i.imgur.com/HtUc8h6.png). Searching through the error file has proven fruitless for me, maybe someone else can find the solution? The error log is attached. Many thanks!

**1. Your Operating System**
Windows 10 (64bit)
**2. App Version**
v3.3.6
**3. Any Relevant Settings**
N/A (?)
**4. Steps to Reproduce**
Running Setup.exe

[ErrorLog.txt](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/212131/ErrorLog.txt)

**Comment by ArcadeRenegade** [comment]
It is because you are getting the bug with open hardware monitor where it
creates the .sys file and keeps an exclusive lock on it. Try restarting
your PC and trying the install again.

**Comment by tuddsfn** [comment]
Well I guess that should have been my first troubleshooting step, because it worked! Thanks!

**Comment by ArcadeRenegade** [comment]
Cool! Glad that worked.
