### ISSUE TITLE
Some parameters such as VRAM load will not show up even when active.

### ISSUE THREAD

**Issue by Xalte** [ArcadeRenegade/SidebarDiagnostics#81]
**1. Your Operating System**
Windows 10
**2. App Version**
3.3.7
**3. Any Relevant Settings**
Turned on all GPU parameters in settings, core clock, VRAM load, ect.
**4. Steps to Reproduce**
After having these settings be on, it will not produce the following information on the sidebar, VRAM load and voltage. Am running an Asus Radeon R9 390.

**Comment by ArcadeRenegade** [comment]
Some metrics are not available on some hardware. Please download Open Hardware Monitor and check if the metric is visible there. If it is, then I will take a look; otherwise that hardware metric is just not supported by OHM.
