### ISSUE TITLE
[Feature Request] Drive Activity Graphs

### ISSUE THREAD

**Issue by brtwrst** [ArcadeRenegade/SidebarDiagnostics#84]
Back with Win 7 i was using a Gadget called "Drive Activity"
it showed a r/w activity histogram for my HDDs.
Pic: http://i.computer-bild.de/imgs/2/6/8/9/6/5/9/Screenshot-1-Drive-Activity-227x158-6073040ae1aaf38c.jpg

this would be awesome to have in the side bar. # # @

**Comment by ArcadeRenegade** [comment]
Unfortunately, I do not know how to draw graphs like this in WPF.

**Comment by lijamez** [comment]
I would also like to see graphs but for basically everything. Network, disk activity, GPUs, RAM, CPU, etc.

**Comment by apparle** [comment]
I'd also like to see a live graph on the sidebar.
