### ISSUE TITLE
Update suggestions

### ISSUE THREAD

**Issue by bobbydoors** [ArcadeRenegade/SidebarDiagnostics#85]
Windows 10 PRO

3.3.7

None

None

Hi!
I was reading that someone added the option to start hidden. I would also like to use the same option so it would be great to add that in the next update. Also, is it possible to add monitoring module for fan speed (case fans connected to fan headers - I can monitor these through HWMonitor). And last but not least, an option to be able to click on modules to start corresponding actions (CPU-Starts TaskManager, Disks-Opens the disk etc.) would be also awesome. 

By the way, I absolutely love the sidebar and everything you did. Keep it up.

**Comment by ArcadeRenegade** [comment]
Getting data about system fans is very difficult. Even SpeedFan, which has been around for a very long time, does not work with a lot of motherboards. A lot of motherboard manufacturers make this data very difficult if not impossible to obtain.

As for the interactivity, maybe in a future major update. Right now I want to keep the scope as a simple hardware monitor. There are a lot of great plugins, actions, etc that could be integrated but developing them is too big of a task for me right now.

**Comment by ArcadeRenegade** [comment]
HWMonitor can get the fan info because it is owned by CPUID and they developer their own very powerful system monitoring SDK. Unfortunately, it is not open source and their licensing is targeted to enterprises. Making it very expensive.

**Comment by bobbydoors** [comment]
Thanks for your response!
I already received the update with start hidden feature, thanks.
One thing though... Is it possible to view the sidebar (when needed via hotkey) while playing a game (fullscreen ofc)? 

Thanks.

**Comment by ArcadeRenegade** [comment]
I haven't tested. But it should be possible.

**Comment by ArcadeRenegade** [comment]
I'm using the native Windows functions to handle the hotkeys. I don't really have control over which video games allows [RegisterHotKey](https://msdn.microsoft.com/en-us/library/windows/desktop/ms646309(v=vs.85).aspx) to work.
