### ISSUE TITLE
[Feature Request] IP Address of network interface

### ISSUE THREAD

**Issue by setriva** [ArcadeRenegade/SidebarDiagnostics#86]
Hello, I just found this app and it's very useful, thank you very much for this.
I was wondering if it's possible to add the IP address of the network interfaces (if any) as a new metric to the network monitor. I was looking at the code to see if I can do it myself, but I don't have much experience with C#.
Thank you in advance.

**Comment by ArcadeRenegade** [comment]
Unfortunately this is not available using the methods I use to get NIC info.

https://technet.microsoft.com/en-us/library/jj574079.aspx

**Comment by dknedlik** [comment]
I have coded up a fix for this if you are interested.  I have it locally on a branch off of today's master.  I would need the ability to commit and I could create a pull request.

In the implementation I have it will display the IPV4 address for any connection that has an assigned address.  If the adapter is not up, it will not display any information.  I have attached a screenshot below.

![2016-05-02 1](https://cloud.githubusercontent.com/assets/6331754/14974671/8b48fb8e-10bd-11e6-8345-c898c2b2f2e7.png)

**Comment by ArcadeRenegade** [comment]
Nice. You should be able to make a pull request. But you have to first fork the repo and apply your changes to that, I think.

**Comment by dknedlik** [comment]
I'll give it some more effort. I created a branch off master, then committed my changes to that branch, but github is refusing to allow me to push that branch back to the server.  I was assuming I did not have write access to the repository. Let me see what I can figure out.

**Comment by ArcadeRenegade** [comment]
http://stackoverflow.com/a/14680805

**Comment by ArcadeRenegade** [comment]
You need to fork the entire repository. Not create a branch off of master. You do not have rights to push commits to ArcadeRenegade/SidebarDiagnostics. So you have to fork it to dknedlik/SidebarDiagnostics, apply your changes to it, then submit a pull request (on your fork's webpage).

**Comment by dknedlik** [comment]
Thanks for the link and information. I have created the pull request now.  Hopefully you find the code useful.  Let me know if you would like modifications.  I tried to keep everything within your design pattern the best I could.

**Comment by ArcadeRenegade** [comment]
Implemented thanks to the help of @dknedlik
