### ISSUE TITLE
Enhancement Request: Additional modules (Processes, Email...)

### ISSUE THREAD

**Issue by Civrock1** [ArcadeRenegade/SidebarDiagnostics#87]
Just discovered this tool via [Reddit](https://www.reddit.com/r/Windows10/comments/4h8qgq/spent_all_night_doing_this_but_im_finally_using/d2obs0q) and instantly fell in love. I want to completely replace Rainmeter with SidebarDiagnostics and I was able to do so with all modules but 2... **Processes** and **Gmail**.
- **Processes**: I guess this could be bundled under CPU. It basically shows the names of the Top 3 processes based on CPU usage.
- **Email**: This pulls emails from my Gmail account and shows the subject line only. I primarily use this to see if I got new emails and if they're important or not. This module in the Rainmeter skin I'm using allows for the entry of the login using the app password which needs to be setup from within one's Google account.

How difficult or time intensive would it be to add these modules respectively monitors to SidebarDiagnostics? I'd very much appreciate if this could be considered for a future release.

As a minor side request, would it be possible to make all font sizes available? Size 10 is too small but 12 feels too big... 11 would be ideal for me.

Thanks and thank you for this excellent tool!

**Comment by ArcadeRenegade** [comment]
Plugins was an enhancement I was considering but just developing the infrastructure to support plugins is a major task. If I have time in the future I will do it but for now I think the sidebar will stay within the scope of a simple hardware monitoring tool.
