### ISSUE TITLE
Setup.exe Installation fails 

### ISSUE THREAD

**Issue by LucianMp** [ArcadeRenegade/SidebarDiagnostics#88]
**1. Windows 10

When I run the setup.exe after a few seconds a pop up comes saying "Installation has failed"
"There was an error while installing the application".

Sorry for the long length of the Logs, I have no idea why its so big.
[SquirrelSetup.pdf](https://github.com/ArcadeRenegade/SidebarDiagnostics/files/246347/SquirrelSetup.pdf)

**Comment by ArcadeRenegade** [comment]
There is a lot of exceptions in your log. Most are "access to the path _x_ was denied". Could you try right-clicking Setup.exe and running it as administrator? Does your user account not have access to the folder %localappdata%?

**Comment by LucianMp** [comment]
Well I am the only user on this laptop and I tried what you told me running it as administrator, still doesn't work. Earlier today it gave me a different error but somehow got installed but I changed one setting and it disappeared, it would be running but it wouldn't show, so I tried to revert the setting but now the setting wouldnt open either! I mean a window would open and on my taskbar the icon would come but there would be nothing. When i hovered my mouse over it which should show in a small window whats in it, nothing was there there, it wasnt blank but the window was maybe half a cm big, just big enough to have the settings and 'X' key. So I tried uninstalling and reinstalling but now I'm back to square 1.

**Comment by ArcadeRenegade** [comment]
Does the folder %localappdata% exist for you? What about %localappdata%\SidebarDiagnostics?

**Comment by LucianMp** [comment]
Yes, and yes. Both those folders exist.

**Comment by LucianMp** [comment]
In that folder I clicked update.exe then ran the installation file, the same error came but the sidebar launched and I was able to change the settings. It seems to be working now. 
Thank you for your help! I'll post with an update if anything happens when I restart.

**Comment by LucianMp** [comment]
Alright I restarted the laptop now. It still works. But need to manually launch it, it doesnt auto start on startup.
Thank you for all your help ^ ^

**Comment by ArcadeRenegade** [comment]
You can manually create a scheduled task to run it when you log in. That is what the program usually does. Glad it works.

**Comment by LucianMp** [comment]
It works perfectly now. Thanks for all the help!
