### ISSUE TITLE
malware detected virustotal

### ISSUE THREAD

**Issue by trackd** [ArcadeRenegade/SidebarDiagnostics#89]
virustotal.com specifically the Rising, Qihoo-360 engines tag this as Malware.

https://virustotal.com/en/file/eb8c36cdf98e41ad6d2769a3c925994dfd08adf44036f7deb91f05f7c61de136/analysis/

Just a heads up.

Don't really know if you can classify this as an issue, didn't see any other way to notify you.

**Comment by ArcadeRenegade** [comment]
Thanks. Not much I can do about false positives unfortunately.
