### ISSUE TITLE
Unable to uninstall

### ISSUE THREAD

**Issue by skjetne** [ArcadeRenegade/SidebarDiagnostics#90]
**1. Your Operating System**
windows 10 1511 Build 10586

**2. App Version**
3.3.7
**3. Any Relevant Settings**
Changed no setting
**4. Steps to Reproduce**
Installed it and tried but decided to uninstall.
Uninstalled via control panel and everything worked fine. 

Program is still installed, but now removed from the uninstall page.

![image](https://cloud.githubusercontent.com/assets/17202764/14985254/f037eddc-1146-11e6-9f1c-9d635a32581f.png)

![image](https://cloud.githubusercontent.com/assets/17202764/14985285/193c5182-1147-11e6-99a4-1f5c5eafc2f0.png)

**Comment by ArcadeRenegade** [comment]
You will have to delete this folder %localappdata%\SidebarDiagnostics and delete the Start Menu and Desktop shortcuts manually.
