### ISSUE TITLE
Graph resetting the monitors

### ISSUE THREAD

**Issue by Silver-Golden** [ArcadeRenegade/SidebarDiagnostics#92]
In the picture below I set it up to monitor the net connections but it always reverts back to this state after a time.
![image](https://cloud.githubusercontent.com/assets/7858375/15073057/3dcb879e-138f-11e6-8cc8-1994611ee47e.png)

**1. Your Operating System**
Windows 10 64
**2. App Version**
v3.3.8 (and previous versions)
**3. Any Relevant Settings**
None I can think of
**4. Steps to Reproduce**
Select what you want for the graph and after a period of time it shall revert back to the default options, stopping the graph

**Comment by ArcadeRenegade** [comment]
This will happen after a hardware change event. Did any hardware get
removed, added, enabled, or disabled?

**Comment by luckydonald** [comment]
As this also happens when starting games in fullscreen mode,  you can't monitor there.

**Comment by luckydonald** [comment]
Maybe it could try to reselect that graph, if the hardware is still present.
