### ISSUE TITLE
[Feature Request] Day of the week.

### ISSUE THREAD

**Issue by jiraph** [ArcadeRenegade/SidebarDiagnostics#94]
It's just a small thing, but if you could make the sidebar show the day of the week that would be great. thanks :)

**Comment by ArcadeRenegade** [comment]
You can change the date format to include day of week.

![image](https://cloud.githubusercontent.com/assets/13874898/15170114/b5cca1d6-16f7-11e6-9e37-6795427a9d0e.png)
