### ISSUE TITLE
Performance Counter cache is corrupted not fixing.

### ISSUE THREAD

**Issue by shadowdog95** [ArcadeRenegade/SidebarDiagnostics#98]
Edit: I thought my Issue was removed when my account got flagged as non human and did not see the old one was posted until I posted this one
**1. Your Operating System**
Windows 8.1

**2. App Version**
V3.3.8
**3. Any Relevant Settings**
Occured after a fresh install
**4. Steps to Reproduce**
None
![error](https://cloud.githubusercontent.com/assets/19439036/15412580/49712de2-1dee-11e6-98d7-812c3d8a93a8.png)

**Comment by ArcadeRenegade** [comment]
Make sure you are running CMD as administrator.
