### ISSUE TITLE
Switch Hotkeys for Reserve Space and Always on Top

### ISSUE THREAD

**Issue by rierei** [ArcadeRenegade/SidebarDiagnostics#99]
Add bind options to toggle Reserve Space and Always on Top would be nice for quickly check the hardware while something occupying the screen.

**Comment by ArcadeRenegade** [comment]
The "Show" hotkey will show the sidebar and activate it (bringing it forward). Effectively doing the same thing.

I did add a new hotkey to toggle reserve space though.

**Comment by rierei** [comment]
@ArcadeRenegade Thanks for implementing reserve space hotkey!

I've suggested toggle always on top because could be useful when using a fullscreen program. Can be nice for games too as an monitoring hardware overlay.
